#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
50 Vehicles (vahan) with all 33 language translations.
10 FREE (id 1-10), 40 PREMIUM (id 11-50).
"""

VEHICLES = [
    # 1-10 FREE
    {"num": 1, "en": "Car", "hi": "कार", "bn": "গাড়ি", "te": "కారు", "mr": "मोटार गाडी", "ta": "மகிழுந்து", "gu": "કાર", "ur": "کار", "kn": "ಕಾರು", "ml": "കാർ", "pa": "ਕਾਰ", "or": "କାର", "as": "গাড়ী", "es": "Coche", "fr": "Voiture", "de": "Auto", "ar": "سيارة", "zh": "汽车", "ru": "Автомобиль", "pt": "Carro", "ja": "車", "ko": "자동차", "it": "Auto", "tr": "Araba", "nl": "Auto", "pl": "Samochód", "id": "Mobil", "th": "รถยนต์", "vi": "Xe hơi", "fa": "خودرو", "ne": "गाडी", "si": "මෝටර් රථය"},
    {"num": 2, "en": "Bus", "hi": "बस", "bn": "বাস", "te": "బస్సు", "mr": "बस", "ta": "பேருந்து", "gu": "બસ", "ur": "بس", "kn": "ಬಸ್ಸು", "ml": "ബസ്", "pa": "ਬੱਸ", "or": "ବସ୍", "as": "বাছ", "es": "Autobús", "fr": "Autobus", "de": "Bus", "ar": "حافلة", "zh": "公共汽车", "ru": "Автобус", "pt": "Ônibus", "ja": "バス", "ko": "버스", "it": "Autobus", "tr": "Otobüs", "nl": "Bus", "pl": "Autobus", "id": "Bis", "th": "รถเมล์", "vi": "Xe buýt", "fa": "اتوبوس", "ne": "बस", "si": "බස් රථය"},
    {"num": 3, "en": "Bicycle", "hi": "साइकिल", "bn": "সাইকেল", "te": "సైకిల్", "mr": "सायकल", "ta": "மிதிவண்டி", "gu": "સાયકલ", "ur": "سائیکل", "kn": "ಸೈಕಲ್", "ml": "സൈക്കിൾ", "pa": "ਸਾਈਕਲ", "or": "ସାଇକେଲ", "as": "চাইকেল", "es": "Bicicleta", "fr": "Bicyclette", "de": "Fahrrad", "ar": "دراجة هوائية", "zh": "自行车", "ru": "Велосипед", "pt": "Bicicleta", "ja": "自転車", "ko": "자전거", "it": "Bicicletta", "tr": "Bisiklet", "nl": "Fiets", "pl": "Rower", "id": "Sepeda", "th": "จักรยาน", "vi": "Xe đạp", "fa": "دوچرخه", "ne": "साइकल", "si": "පාපැදිය"},
    {"num": 4, "en": "Motorcycle", "hi": "मोटरसाइकिल", "bn": "মোটরসাইকেল", "te": "మోటార్ సైకిల్", "mr": "मोटारसायकल", "ta": "மோட்டார் சைக்கிள்", "gu": "મોટરસાયકલ", "ur": "موٹر سائیکل", "kn": "ಮೋಟಾರ್ ಸೈಕಲ್", "ml": "മോട്ടോർസൈക്കിൾ", "pa": "ਮੋਟਰਸਾਈਕਲ", "or": "ମୋଟରସାଇକେଲ", "as": "মটৰচাইকেল", "es": "Motocicleta", "fr": "Motocyclette", "de": "Motorrad", "ar": "دراجة نارية", "zh": "摩托车", "ru": "Мотоцикл", "pt": "Motocicleta", "ja": "オートバイ", "ko": "오토바이", "it": "Motocicletta", "tr": "Motosiklet", "nl": "Motorfiets", "pl": "Motocykl", "id": "Sepeda Motor", "th": "มอเตอร์ไซค์", "vi": "Xe máy", "fa": "موتورسیکلت", "ne": "मोटरसाइकल", "si": "යතුරුපැදිය"},
    {"num": 5, "en": "Train", "hi": "रेलगाड़ी", "bn": "রেলগাড়ি", "te": "రైలు", "mr": "आगगाडी", "ta": "தொடர்வண்டி", "gu": "રેલગાડી", "ur": "ریل گاڑی", "kn": "ರೈಲು", "ml": "തീവണ്ടി", "pa": "ਰੇਲਗੱਡੀ", "or": "ରେଳଗାଡ଼ି", "as": "ৰে'লগাড়ী", "es": "Tren", "fr": "Train", "de": "Zug", "ar": "قطار", "zh": "火车", "ru": "Поезд", "pt": "Trem", "ja": "列車", "ko": "기차", "it": "Treno", "tr": "Tren", "nl": "Trein", "pl": "Pociąg", "id": "Kereta Api", "th": "รถไฟ", "vi": "Tàu hỏa", "fa": "قطار", "ne": "रेलगाडी", "si": "දුම්රිය"},
    {"num": 6, "en": "Airplane", "hi": "हवाई जहाज़", "bn": "উড়োজাহাজ", "te": "విమానం", "mr": "विमान", "ta": "விமானம்", "gu": "વિમાન", "ur": "ہوائی جہاز", "kn": "ವಿಮಾನ", "ml": "വിമാനം", "pa": "ਹਵਾਈ ਜਹਾਜ਼", "or": "ଉଡ଼ାଜାହାଜ", "as": "উৰাজাহাজ", "es": "Avión", "fr": "Avion", "de": "Flugzeug", "ar": "طائرة", "zh": "飞机", "ru": "Самолёт", "pt": "Avião", "ja": "飛行機", "ko": "비행기", "it": "Aereo", "tr": "Uçak", "nl": "Vliegtuig", "pl": "Samolot", "id": "Pesawat Terbang", "th": "เครื่องบิน", "vi": "Máy bay", "fa": "هواپیما", "ne": "हवाईजहाज", "si": "ගුවන් යානය"},
    {"num": 7, "en": "Helicopter", "hi": "हेलिकॉप्टर", "bn": "হেলিকপ্টার", "te": "హెలికాప్టర్", "mr": "हेलिकॉप्टर", "ta": "ஹெலிகாப்டர்", "gu": "હેલિકોપ્ટર", "ur": "ہیلی کاپٹر", "kn": "ಹೆಲಿಕಾಪ್ಟರ್", "ml": "ഹെലികോപ്റ്റർ", "pa": "ਹੈਲੀਕਾਪਟਰ", "or": "ହେଲିକପ୍ଟର", "as": "হেলিকপ্তাৰ", "es": "Helicóptero", "fr": "Hélicoptère", "de": "Hubschrauber", "ar": "مروحية", "zh": "直升机", "ru": "Вертолёт", "pt": "Helicóptero", "ja": "ヘリコプター", "ko": "헬리콥터", "it": "Elicottero", "tr": "Helikopter", "nl": "Helikopter", "pl": "Helikopter", "id": "Helikopter", "th": "เฮลิคอปเตอร์", "vi": "Trực thăng", "fa": "بالگرد", "ne": "हेलिकप्टर", "si": "හෙලිකොප්ටරය"},
    {"num": 8, "en": "Boat", "hi": "नाव", "bn": "নৌকা", "te": "పడవ", "mr": "नाव", "ta": "படகு", "gu": "હોડી", "ur": "کشتی", "kn": "ದೋಣಿ", "ml": "തോണി", "pa": "ਕਿਸ਼ਤੀ", "or": "ଡଙ୍ଗା", "as": "নাও", "es": "Barco", "fr": "Bateau", "de": "Boot", "ar": "قارب", "zh": "小船", "ru": "Лодка", "pt": "Barco", "ja": "ボート", "ko": "보트", "it": "Barca", "tr": "Tekne", "nl": "Boot", "pl": "Łódź", "id": "Perahu", "th": "เรือ", "vi": "Thuyền", "fa": "قایق", "ne": "डुङ्गा", "si": "බෝට්ටුව"},
    {"num": 9, "en": "Ship", "hi": "पानी का जहाज़", "bn": "জাহাজ", "te": "ఓడ", "mr": "जहाज", "ta": "கப்பல்", "gu": "વહાણ", "ur": "بحری جہاز", "kn": "ಹಡಗು", "ml": "കപ്പൽ", "pa": "ਸਮੁੰਦਰੀ ਜਹਾਜ਼", "or": "ଜାହାଜ", "as": "জাহাজ", "es": "Buque", "fr": "Navire", "de": "Schiff", "ar": "سفينة", "zh": "轮船", "ru": "Корабль", "pt": "Navio", "ja": "船", "ko": "배", "it": "Nave", "tr": "Gemi", "nl": "Schip", "pl": "Statek", "id": "Kapal Laut", "th": "เรือเดินสมุทร", "vi": "Tàu thủy", "fa": "کشتی", "ne": "पानीजहाज", "si": "නෞකාව"},
    {"num": 10, "en": "Auto Rickshaw", "hi": "ऑटो रिक्शा", "bn": "অটোরিকশা", "te": "ఆటో రిక్షా", "mr": "रिक्षा", "ta": "ஆட்டோ ரிக்ஷா", "gu": "રીક્ષા", "ur": "آٹو رکشہ", "kn": "ಆಟೋ ರಿಕ್ಷಾ", "ml": "ഓട്ടോറിക്ഷ", "pa": "ਆਟੋ ਰਿਕਸ਼ਾ", "or": "ଅଟୋ ରିକ୍ସା", "as": "অটো ৰিক্সা", "es": "Mototaxi", "fr": "Tuk-tuk", "de": "Autorikscha", "ar": "توك توك", "zh": "机动三轮车", "ru": "Моторикша", "pt": "Autorriquixá", "ja": "オートリキシャ", "ko": "오토릭샤", "it": "Ape car", "tr": "Tuk-tuk", "nl": "Autoriksja", "pl": "Autoriksza", "id": "Bajaj", "th": "ตุ๊กตุ๊ก", "vi": "Xe lam", "fa": "توک توک", "ne": "अटोरिक्सा", "si": "ත්‍රිරෝද රථය"},

    # 11-50 PREMIUM
    {"num": 11, "en": "Truck", "hi": "ट्रक", "bn": "ট্রাক", "te": "లారీ", "mr": "ट्रक", "ta": "சரக்குந்து", "gu": "ખટારો", "ur": "ٹرک", "kn": "ಲಾರಿ", "ml": "ലോറി", "pa": "ਟਰੱਕ", "or": "ଟ୍ରକ", "as": "ট্ৰাক", "es": "Camión", "fr": "Camion", "de": "LKW", "ar": "شاحنة", "zh": "卡车", "ru": "Грузовик", "pt": "Caminhão", "ja": "トラック", "ko": "트럭", "it": "Camion", "tr": "Kamyon", "nl": "Vrachtwagen", "pl": "Ciężarówka", "id": "Truk", "th": "รถบรรทุก", "vi": "Xe tải", "fa": "کامیون", "ne": "ट्रक", "si": "ලොරිය"},
    {"num": 12, "en": "Tractor", "hi": "ट्रैक्टर", "bn": "ট্রাক্টর", "te": "ట్రాక్టర్", "mr": "ट्रॅक्टर", "ta": "டிராக்டர்", "gu": "ટ્રેક્ટર", "ur": "ٹریکٹر", "kn": "ಟ್ರಾಕ್ಟರ್", "ml": "ട്രാക്ടർ", "pa": "ਟਰੈਕਟਰ", "or": "ଟ୍ରାକ୍ଟର", "as": "ট্ৰেক্টৰ", "es": "Tractor", "fr": "Tracteur", "de": "Traktor", "ar": "جرار", "zh": "拖拉机", "ru": "Трактор", "pt": "Trator", "ja": "トラクター", "ko": "트랙터", "it": "Trattore", "tr": "Traktör", "nl": "Tractor", "pl": "Traktor", "id": "Traktor", "th": "รถแทรกเตอร์", "vi": "Máy kéo", "fa": "تراکتور", "ne": "ट्र्याक्टर", "si": "ට්‍රැක්ටරය"},
    {"num": 13, "en": "Ambulance", "hi": "एम्बुलेंस", "bn": "অ্যাম্বুলেন্স", "te": "అంబులెన్స్", "mr": "रुग्णवाहिका", "ta": "ஆம்புலன்ஸ்", "gu": "એમ્બ્યુલન્સ", "ur": "ایمبولینس", "kn": "ಆಂಬ್ಯುಲೆನ್ಸ್", "ml": "ആംബുലൻസ്", "pa": "ਐਂਬੂਲੈਂਸ", "or": "ଆମ୍ବୁଲାନ୍ସ", "as": "এম্বুলেন্স", "es": "Ambulancia", "fr": "Ambulance", "de": "Krankenwagen", "ar": "سيارة إسعاف", "zh": "救护车", "ru": "Скорая помощь", "pt": "Ambulância", "ja": "救急車", "ko": "구급차", "it": "Ambulanza", "tr": "Ambulans", "nl": "Ambulance", "pl": "Karetka", "id": "Ambulans", "th": "รถพยาบาล", "vi": "Xe cứu thương", "fa": "آمبولانس", "ne": "एम्बुलेन्स", "si": "ගිලන් රථය"},
    {"num": 14, "en": "Fire Engine", "hi": "दमकल गाड़ी", "bn": "দমকল গাড়ি", "te": "అగ్నిమాపక వాహనం", "mr": "अग्निशामक बंब", "ta": "தீயணைப்பு வண்டி", "gu": "લાયબંબો", "ur": "فائر انجن", "kn": "ಅಗ್ನಿಶಾಮಕ ವಾಹನ", "ml": "തീവണ്ടി സർവീസ് വാഹനം", "pa": "ਅੱਗ ਬੁਝਾਊ ਗੱਡੀ", "or": "ଦମକଳ ଗାଡ଼ି", "as": "দমকল গাড়ী", "es": "Camión de bomberos", "fr": "Camion de pompiers", "de": "Feuerwehrauto", "ar": "سيارة إطفاء", "zh": "消防车", "ru": "Пожарная машина", "pt": "Carro de bombeiros", "ja": "消防車", "ko": "소방차", "it": "Autopompa", "tr": "İtfaiye aracı", "nl": "Brandweerwagen", "pl": "Wóz strażacki", "id": "Pemadam Kebakaran", "th": "รถดับเพลิง", "vi": "Xe cứu hỏa", "fa": "ماشین آتش‌نشانی", "ne": "दमकल", "si": "ගිනි නිවන රථය"},
    {"num": 15, "en": "Police Car", "hi": "पुलिस कार", "bn": "পুলিশের গাড়ি", "te": "పోలీస్ కారు", "mr": "पोलीस गाडी", "ta": "காவல்துறை வாகனம்", "gu": "પોલીસ વાન", "ur": "پولیس کار", "kn": "ಪೊಲೀಸ್ ಕಾರು", "ml": "പോലീസ് കാർ", "pa": "ਪੁਲਿਸ ਕਾਰ", "or": "ପୋଲିସ ଗାଡ଼ି", "as": "পুলিচ গাড়ী", "es": "Coche de policía", "fr": "Voiture de police", "de": "Polizeiauto", "ar": "سيارة شرطة", "zh": "警车", "ru": "Полицейская машина", "pt": "Viatura policial", "ja": "パトロールカー", "ko": "경찰차", "it": "Auto della polizia", "tr": "Polis arabası", "nl": "Politiewagen", "pl": "Radiowóz", "id": "Mobil Polisi", "th": "รถตำรวจ", "vi": "Xe cảnh sát", "fa": "ماشین پلیس", "ne": "प्रहरी गाडी", "si": "පොලිස් රථය"},
    {"num": 16, "en": "School Bus", "hi": "स्कूल बस", "bn": "স্কুল বাস", "te": "స్కూల్ బస్సు", "mr": "शाळेची बस", "ta": "பள்ளிப் பேருந்து", "gu": "સ્કૂલ બસ", "ur": "سکول بس", "kn": "ಶಾಲಾ ಬಸ್ಸು", "ml": "സ്കൂൾ ബസ്", "pa": "ਸਕੂਲ ਬੱਸ", "or": "ସ୍କୁଲ ବସ୍", "as": "স্কুল বাছ", "es": "Autobús escolar", "fr": "Bus scolaire", "de": "Schulbus", "ar": "حافلة مدرسية", "zh": "校车", "ru": "Школьный автобус", "pt": "Ônibus escolar", "ja": "スクールバス", "ko": "스쿨버스", "it": "Scuolabus", "tr": "Okul servisi", "nl": "Schoolbus", "pl": "Autobus szkolny", "id": "Bus Sekolah", "th": "รถโรงเรียน", "vi": "Xe buýt trường học", "fa": "اتوبوس مدرسه", "ne": "विद्यालय बस", "si": "පාසල් බස් රථය"},
    {"num": 17, "en": "Scooter", "hi": "स्कूटर", "bn": "স্কুটার", "te": "స్కూటర్", "mr": "स्कूटर", "ta": "ஸ்கூட்டர்", "gu": "સ્કૂટર", "ur": "اسکوٹر", "kn": "ಸ್ಕೂಟರ್", "ml": "സ്കൂട്ടർ", "pa": "ਸਕੂਟਰ", "or": "ସ୍କୁଟର", "as": "স্কুটাৰ", "es": "Escúter", "fr": "Scooter", "de": "Roller", "ar": "سكوتر", "zh": "踏板车", "ru": "Скутер", "pt": "Lambretinha", "ja": "スクーター", "ko": "스쿠터", "it": "Scooter", "tr": "Skuter", "nl": "Scooter", "pl": "Skuter", "id": "Skuter", "th": "สกู๊ตเตอร์", "vi": "Xe tay ga", "fa": "اسکوتر", "ne": "स्कुटर", "si": "ස්කූටරය"},
    {"num": 18, "en": "Van", "hi": "वैन", "bn": "ভ্যান", "te": "వ్యాన్", "mr": "व्हॅन", "ta": "வேன்", "gu": "વાન", "ur": "وین", "kn": "ವ್ಯಾನ್", "ml": "വാൻ", "pa": "ਵੈਨ", "or": "ଭ୍ୟାନ", "as": "ভেন গাড়ী", "es": "Furgoneta", "fr": "Fourgonnette", "de": "Transporter", "ar": "شاحنة صغيرة", "zh": "面包车", "ru": "Фургон", "pt": "Furgão", "ja": "ワンボックスカー", "ko": "승합차", "it": "Furgone", "tr": "Minibüs", "nl": "Bestelwagen", "pl": "Furgonetka", "id": "Mobil Van", "th": "รถตู้", "vi": "Xe van", "fa": "ون", "ne": "भ्यान", "si": "වෑන් රථය"},
    {"num": 19, "en": "Taxi", "hi": "टैक्सी", "bn": "ট্যাক্সি", "te": "టాక్సీ", "mr": "टॅक्सी", "ta": "வாடகைக்கார்", "gu": "ટેક્સી", "ur": "ٹیکسی", "kn": "ಟ್ಯಾಕ್ಸಿ", "ml": "ടാക്സി", "pa": "ਟੈਕਸੀ", "or": "ଟ୍ୟାକ୍ସି", "as": "টেক্সী", "es": "Taxi", "fr": "Taxi", "de": "Taxi", "ar": "تاكسي", "zh": "出租车", "ru": "Такси", "pt": "Táxi", "ja": "タクシー", "ko": "택시", "it": "Taxi", "tr": "Taksi", "nl": "Taxi", "pl": "Taksówka", "id": "Taksi", "th": "แท็กซี่", "vi": "Taxi", "fa": "تاکسی", "ne": "ट्याक्सी", "si": "ටැක්සිය"},
    {"num": 20, "en": "Metro Train", "hi": "मेट्रो ट्रेन", "bn": "মেট্রো রেল", "te": "మెట్రో రైలు", "mr": "मेट्रो", "ta": "மெட்ரோ ரயில்", "gu": "મેટ્રો ટ્રેન", "ur": "میٹرو ٹرین", "kn": "ಮೆಟ್ರೋ ರೈಲು", "ml": "മെട്രോ ട്രെയിൻ", "pa": "ਮੈਟਰੋ ਰੇਲ", "or": "ମେଟ୍ରୋ ଟ୍ରେନ", "as": "মেট্ৰ' ৰে'ল", "es": "Metro", "fr": "Métro", "de": "U-Bahn", "ar": "مترو الأنفاق", "zh": "地铁", "ru": "Метро", "pt": "Metrô", "ja": "地下鉄", "ko": "지하철", "it": "Metropolitana", "tr": "Metro", "nl": "Metro", "pl": "Metro", "id": "Kereta Bawah Tanah", "th": "รถไฟฟ้า", "vi": "Tàu điện ngầm", "fa": "مترو", "ne": "मेट्रो रेल", "si": "මෙට්‍රෝ දුම්රිය"},
    {"num": 21, "en": "Bullet Train", "hi": "बुलेट ट्रेन", "bn": "বুলেট ট্রেন", "te": "బుల్లెట్ రైలు", "mr": "बुलेट ट्रेन", "ta": "புல்லட் ரயில்", "gu": "બુલેટ ટ્રેન", "ur": "بلٹ ٹرین", "kn": "ಬುಲೆಟ್ ರೈಲು", "ml": "ബുള്ളറ്റ് ട്രെയിൻ", "pa": "ਬੁਲੇਟ ਟਰੇਨ", "or": "ବୁଲେଟ ଟ୍ରେନ", "as": "বুলেট ৰে'ল", "es": "Tren bala", "fr": "Train à grande vitesse", "de": "Hochgeschwindigkeitszug", "ar": "قطار رصاصة", "zh": "高铁", "ru": "Скоростной поезд", "pt": "Trem-bala", "ja": "新幹線", "ko": "고속철도", "it": "Treno ad alta velocità", "tr": "Hızlı tren", "nl": "Hogesnelheidstrein", "pl": "Pociąg ekspresowy", "id": "Kereta Cepat", "th": "รถไฟหัวกระสุน", "vi": "Tàu siêu tốc", "fa": "قطار سریع‌السیر", "ne": "बुलेट रेल", "si": "බුලට් දුම්රිය"},
    {"num": 22, "en": "Tram", "hi": "ट्राम", "bn": "ট্রাম", "te": "ట్రామ్", "mr": "ट्राम", "ta": "ட்ராம் வண்டி", "gu": "ટ્રામ", "ur": "ٹرام", "kn": "ಟ್ರಾಮ್", "ml": "ട്രാം", "pa": "ਟਰਾਮ", "or": "ଟ୍ରାମ", "as": "ট্ৰাম", "es": "Tranvía", "fr": "Tramway", "de": "Straßenbahn", "ar": "ترام", "zh": "有轨电车", "ru": "Трамвай", "pt": "Bonde", "ja": "路面電車", "ko": "트램", "it": "Tram", "tr": "Tramvay", "nl": "Tram", "pl": "Tramwaj", "id": "Trem", "th": "รถราง", "vi": "Xe điện mặt đất", "fa": "تراموا", "ne": "ट्राम", "si": "ට්‍රෑම් රථය"},
    {"num": 23, "en": "Hot Air Balloon", "hi": "गरम हवा का गुब्बारा", "bn": "গরম বাতাসের বেলুন", "te": "హాట్ ఎయిర్ బెలూన్", "mr": "उष्ण हवेचा फुगा", "ta": "சூடான காற்று பலூன்", "gu": "ગરમ હવાનું બલૂન", "ur": "گرم ہوا کا غبارہ", "kn": "ಬಿಸಿ ಗಾಳಿಯ ಬಲೂನ್", "ml": "ഹോട്ട് എയർ ബലൂൺ", "pa": "ਗਰਮ ਹਵਾ ਵਾਲਾ ਗੁਬਾਰਾ", "or": "ବେଲୁନ ଯାନ", "as": "গৰম বতাহৰ বেলুন", "es": "Globo aerostático", "fr": "Montgolfière", "de": "Heißluftballon", "ar": "منطاد هواء ساخن", "zh": "热气球", "ru": "Воздушный шар", "pt": "Balão de ar quente", "ja": "気球", "ko": "열기구", "it": "Mongolfiera", "tr": "Sıcak hava balonu", "nl": "Heteluchtballon", "pl": "Balon na gorące powietrze", "id": "Balon Udara", "th": "บอลลูนลมร้อน", "vi": "Khinh khí cầu", "fa": "بالن هوای گرم", "ne": "हट एयर बेलुन", "si": "උණුසුම් වායු බැලූනය"},
    {"num": 24, "en": "Submarine", "hi": "पनडुब्बी", "bn": "ডুবোজাহাজ", "te": "జలాంతర్గామి", "mr": "पानबुडी", "ta": "நீர்மூழ்கிக் கப்பல்", "gu": "સબમરીન", "ur": "آبدوز", "kn": "ಜಲಾಂತರ್ಗಾಮಿ", "ml": "മുങ്ങിക്കപ്പൽ", "pa": "ਪਣਡੁੱਬੀ", "or": "ବୁଡ଼ାଜାହାଜ", "as": "ডুবোজাহাজ", "es": "Submarino", "fr": "Sous-marin", "de": "U-Boot", "ar": "غواصة", "zh": "潜水艇", "ru": "Подводная лодка", "pt": "Submarino", "ja": "潜水艦", "ko": "잠수함", "it": "Sottomarino", "tr": "Denizaltı", "nl": "Onderzeeër", "pl": "Okręt podwodny", "id": "Kapal Selam", "th": "เรือดำน้ำ", "vi": "Tàu ngầm", "fa": "زیردریایی", "ne": "पनडुब्बी", "si": "සබ්මැරීනය"},
    {"num": 25, "en": "Rocket", "hi": "रॉकेट", "bn": "রকেট", "te": "రాకెట్", "mr": "रॉकेट", "ta": "ராக்கெட்", "gu": "રોકેટ", "ur": "راکٹ", "kn": "ರಾಕೆಟ್", "ml": "റോക്കറ്റ്", "pa": "ਰਾਕੇਟ", "or": "ରକେଟ", "as": "ৰকেট", "es": "Cohete", "fr": "Fusée", "de": "Rakete", "ar": "صاروخ", "zh": "火箭", "ru": "Ракета", "pt": "Foguete", "ja": "ロケット", "ko": "로켓", "it": "Razzo", "tr": "Roket", "nl": "Raket", "pl": "Rakieta", "id": "Roket", "th": "จรวด", "vi": "Tên lửa", "fa": "موشک", "ne": "रकेट", "si": "රොකට්ටුව"},
    {"num": 26, "en": "Space Shuttle", "hi": "अंतरिक्ष यान", "bn": "মহাকাশযান", "te": "అంతరిక్ష నౌక", "mr": "अंतराळयान", "ta": "விண்கலம்", "gu": "અવકાશયાન", "ur": "خلائی جہاز", "kn": "ಬಾಹ್ಯಾಕಾಶ ನೌಕೆ", "ml": "ബഹിരാകാശ പേടകം", "pa": "ਪੁਲਾੜ ਯਾਨ", "or": "ମହାକାଶଯାନ", "as": "মহাকাশযান", "es": "Transbordador espacial", "fr": "Navette spatiale", "de": "Raumfähre", "ar": "مكوك فضاء", "zh": "航天飞机", "ru": "Космический челнок", "pt": "Ônibus espacial", "ja": "スペースシャトル", "ko": "우주왕복선", "it": "Navetta spaziale", "tr": "Uzay mekiği", "nl": "Ruimteveer", "pl": "Prom kosmiczny", "id": "Pesawat Ulang Alik", "th": "กระสวยอวกาศ", "vi": "Tàu con thoi", "fa": "شاتل فضایی", "ne": "अन्तरिक्ष यान", "si": "අභ්‍යවකාශ ෂටලය"},
    {"num": 27, "en": "Yacht", "hi": "नौका (यॉट)", "bn": "ইয়ট", "te": "విలాస పడవ", "mr": "याच", "ta": "உல்லாசப் படகு", "gu": "યાટ", "ur": "یاٹ", "kn": "ವಿಲಾಸಿ ದೋಣಿ", "ml": "യാച്ച്", "pa": "ਯਾਚ", "or": "ୟଟ୍", "as": "ইয়ট", "es": "Yate", "fr": "Yacht", "de": "Jacht", "ar": "يخت", "zh": "游艇", "ru": "Яхта", "pt": "Iate", "ja": "ヨット", "ko": "요트", "it": "Yacht", "tr": "Yat", "nl": "Jacht", "pl": "Jacht", "id": "Kapal Pesiar Kecil", "th": "เรือยอชท์", "vi": "Du thuyền nhỏ", "fa": "قایق بادبانی تفریحی", "ne": "याट", "si": "යොට් යාත්‍රාව"},
    {"num": 28, "en": "Jet Ski", "hi": "जेट स्की", "bn": "জেট স্কি", "te": "జెట్ స్కీ", "mr": "जेट स्की", "ta": "ஜெட் ஸ்கை", "gu": "જેટ સ્કી", "ur": "جیٹ اسکی", "kn": "ಜೆಟ್ ಸ್ಕೀ", "ml": "ജെറ്റ് സ്കീ", "pa": "ਜੈਟ ਸਕੀ", "or": "ଜେଟ ସ୍କି", "as": "জেট স্কী", "es": "Moto acuática", "fr": "Motomarine", "de": "Jetski", "ar": "دراجة مائية", "zh": "水上摩托", "ru": "Гидроцикл", "pt": "Moto aquática", "ja": "水上オートバイ", "ko": "제트스키", "it": "Moto d'acqua", "tr": "Jet ski", "nl": "Waterscooter", "pl": "Skuter wodny", "id": "Jet Ski", "th": "เจ็ตสกี", "vi": "Mô tô nước", "fa": "جت‌اسکی", "ne": "जेट स्की", "si": "ජෙට් ස්කී"},
    {"num": 29, "en": "Hovercraft", "hi": "होवरक्राफ्ट", "bn": "হোভারক্রাফট", "te": "హోవర్‌క్రాఫ్ట్", "mr": "होव्हरक्राफ्ट", "ta": "ஹோவர்கிராப்ட்", "gu": "હોવરક્રાફ્ટ", "ur": "ہوور کرافٹ", "kn": "ಹೋವರ್‌ಕ್ರಾಫ್ಟ್", "ml": "ഹോവർക്രാഫ്റ്റ്", "pa": "ਹੋਵਰਕ੍ਰਾਫਟ", "or": "ହୋଭରକ୍ରାଫ୍ଟ", "as": "হভাৰক্ৰাফ্ট", "es": "Aerodeslizador", "fr": "Aéroglisseur", "de": "Luftkissenboot", "ar": "حوامة", "zh": "气垫船", "ru": "Судно на воздушной подушке", "pt": "Hovercraft", "ja": "ホバークラフト", "ko": "공기부양정", "it": "Hovercraft", "tr": "Hoverkraft", "nl": "Luchtkussenvaartuig", "pl": "Poduszkowiec", "id": "Kapal Melayang", "th": "เรือโฮเวอร์คราฟต์", "vi": "Tàu đệm khí", "fa": "هواناو", "ne": "होभरक्राफ्ट", "si": "හොවර්ක්‍රාෆ්ට්"},
    {"num": 30, "en": "Bulldozer", "hi": "बुलडोज़र", "bn": "বুলডোজার", "te": "బుల్డోజర్", "mr": "बुलडोझर", "ta": "புல்டோசர்", "gu": "બુલડોઝર", "ur": "بلڈوزر", "kn": "ಬುಲ್ಡೋಜರ್", "ml": "ബുൾഡോസർ", "pa": "ਬੁਲਡੋਜ਼ਰ", "or": "ବୁଲଡୋଜର", "as": "বুলড'জাৰ", "es": "Bulldózer", "fr": "Bulldozer", "de": "Planierraupe", "ar": "جرافة", "zh": "推土机", "ru": "Бульдозер", "pt": "Bulldozer", "ja": "ブルドーザー", "ko": "불도저", "it": "Bulldozer", "tr": "Buldozer", "nl": "Bulldozer", "pl": "Spychacz", "id": "Buldoser", "th": "รถปราบดิน", "vi": "Xe ủi", "fa": "بولدوزر", "ne": "बुलडोजर", "si": "බුල්ඩෝසරය"},
    {"num": 31, "en": "Excavator", "hi": "जेसीबी / खुदाई मशीन", "bn": "খননকারী যন্ত্র", "te": "ఎక్స్‌కవేటర్", "mr": "उत्खनन यंत्र", "ta": "மண் அள்ளும் இயந்திரம்", "gu": "જેસીબી", "ur": "کھدائی والی مشین", "kn": "ಅಗೆಯುವ ಯಂತ್ರ", "ml": "മണ്ണുമാന്തി യന്ത്രം", "pa": "ਖੁਦਾਈ ਵਾਲੀ ਮਸ਼ੀਨ", "or": "ମାଟି ଖୋଳା ମେସିନ", "as": "খান্দা যন্ত্ৰ", "es": "Excavadora", "fr": "Pelleteuse", "de": "Bagger", "ar": "حفارة", "zh": "挖掘机", "ru": "Экскаватор", "pt": "Escavadeira", "ja": "ショベルカー", "ko": "굴착기", "it": "Escavatore", "tr": "Ekskavatör", "nl": "Graafmachine", "pl": "Koparka", "id": "Ekskavator", "th": "รถขุด", "vi": "Máy xúc", "fa": "بیل مکانیکی", "ne": "उत्खनन मेसिन", "si": "කැනීම් යන්ත්‍රය"},
    {"num": 32, "en": "Crane Truck", "hi": "क्रेन गाड़ी", "bn": "ক্রেন গাড়ি", "te": "క్రేన్ ట్రక్", "mr": "क्रेन वाहन", "ta": "கிரேன் வாகனம்", "gu": "ક્રેન વાન", "ur": "کرین ٹرک", "kn": "ಕ್ರೇನ್ ವಾಹನ", "ml": "ക്രെയിൻ ലോറി", "pa": "ਕ੍ਰੇਨ ਟਰੱਕ", "or": "କ୍ରେନ ଗାଡ଼ି", "as": "ক্ৰেন গাড়ী", "es": "Camión grúa", "fr": "Camion-grue", "de": "Kranwagen", "ar": "شاحنة رافعة", "zh": "起重机卡车", "ru": "Автокран", "pt": "Caminhão-guindaste", "ja": "クレーン車", "ko": "크레인트럭", "it": "Autogrù", "tr": "Vinçli kamyon", "nl": "Kraanwagen", "pl": "Żuraw samochodowy", "id": "Truk Derek", "th": "รถเครน", "vi": "Xe cần cẩu", "fa": "کامیون جرثقیل", "ne": "क्रेन गाडी", "si": "ක්‍රේන් රථය"},
    {"num": 33, "en": "Dump Truck", "hi": "डंपर ट्रक", "bn": "ডাম্পার", "te": "డంప్ ట్రక్", "mr": "डंपर", "ta": "டிப்பர் லாரி", "gu": "ડમ્પર", "ur": "ڈمپر", "kn": "ಟಿಪ್ಪರ್ ಲಾರಿ", "ml": "ടിപ്പർ ലോറി", "pa": "ਡੰਪ ਟਰੱਕ", "or": "ଡମ୍ପର", "as": "ডাম্পাৰ", "es": "Camión volquete", "fr": "Camion benne", "de": "Muldenkipper", "ar": "شاحنة قلابة", "zh": "自卸车", "ru": "Самосвал", "pt": "Caminhão basculante", "ja": "ダンプカー", "ko": "덤프트럭", "it": "Camion ribaltabile", "tr": "Damperli kamyon", "nl": "Kiepwagen", "pl": "Wywrotka", "id": "Truk Jungkit", "th": "รถดัมพ์", "vi": "Xe ben", "fa": "کامیون کمپرسی", "ne": "डम्पर", "si": "ඩම්පර් ලොරිය"},
    {"num": 34, "en": "Cement Mixer", "hi": "सीमेंट मिक्सर", "bn": "সিমেন্ট মিক্সার", "te": "సిమెంట్ మిక్సర్", "mr": "सिमेंट मिक्सर गाडी", "ta": "சிமெண்ட் கலவை வண்டி", "gu": "સિમેન્ટ મિક્સર", "ur": "سیمنٹ مکسر", "kn": "ಸಿಮೆಂಟ್ ಮಿಕ್ಸರ್", "ml": "സിമന്റ് മിക്സർ", "pa": "ਸੀਮਿੰਟ ਮਿਕਸਰ", "or": "ସିମେଣ୍ଟ ମିକ୍ସର", "as": "চিমেণ্ট মিক্সাৰ", "es": "Hormigonera", "fr": "Bétonnière", "de": "Betonmischer", "ar": "خلاطة خرسانة", "zh": "水泥搅拌车", "ru": "Бетономешалка", "pt": "Caminhão betoneira", "ja": "ミキサー車", "ko": "레미콘", "it": "Betoniera", "tr": "Beton mikseri", "nl": "Betonmolenwagen", "pl": "Betoniarka", "id": "Truk Pengaduk Semen", "th": "รถโม่ปูน", "vi": "Xe trộn bê tông", "fa": "کامیون مخلوط‌کن بتن", "ne": "सिमेन्ट मिक्सर", "si": "සිමෙන්ති මිශ්‍රණ රථය"},
    {"num": 35, "en": "Road Roller", "hi": "रोड रोलर", "bn": "রোড রোলার", "te": "రోడ్ రోలర్", "mr": "रोड रोलर", "ta": "சாலை உருளை", "gu": "રોડ રોલર", "ur": "روڈ رولر", "kn": "ರೋಡ್ ರೋಲರ್", "ml": "റോഡ് റോളർ", "pa": "ਰੋਡ ਰੋਲਰ", "or": "ରୋଡ ରୋଲର", "as": "ৰ'ড ৰ'লাৰ", "es": "Aplanadora", "fr": "Rouleau compresseur", "de": "Straßenwalze", "ar": "مدحلة الطرق", "zh": "压路机", "ru": "Дорожный каток", "pt": "Rolo compressor", "ja": "ロードローラー", "ko": "로드롤러", "it": "Rullo compressore", "tr": "Silindir", "nl": "Wals", "pl": "Walec drogowy", "id": "Mesin Penggilas", "th": "รถบดถนน", "vi": "Xe lu", "fa": "غلتک راه‌سازی", "ne": "रोड रोलर", "si": "රෝලරය"},
    {"num": 36, "en": "Forklift", "hi": "फ़ोर्कलिफ़्ट", "bn": "ফর্কলিফট", "te": "ఫోర్క్‌లిఫ్ట్", "mr": "फोर्कलिफ्ट", "ta": "சுமை தூக்கி வண்டி", "gu": "ફોર્કલિફ્ટ", "ur": "فورک لفٹ", "kn": "ಫೋರ್ಕ್‌ಲಿಫ್ಟ್", "ml": "ഫോർക്ക് ലിഫ്റ്റ്", "pa": "ਫੋਰਕਲਿਫਟ", "or": "ଫୋର୍କଲିଫ୍ଟ", "as": "ফৰ্কলিফ্ট", "es": "Carretilla elevadora", "fr": "Chariot élévateur", "de": "Gabelstapler", "ar": "رافعة شوكية", "zh": "叉车", "ru": "Вилочный погрузчик", "pt": "Empilhadeira", "ja": "フォークリフト", "ko": "지게차", "it": "Carrello elevatore", "tr": "Forklift", "nl": "Heftruck", "pl": "Wózek widłowy", "id": "Forklift", "th": "รถโฟล์คลิฟต์", "vi": "Xe nâng", "fa": "لیفتراک", "ne": "फोर्कलिफ्ट", "si": "ෆෝක්ලිෆ්ට් රථය"},
    {"num": 37, "en": "Go Kart", "hi": "गो कार्ट", "bn": "গো কার্ট", "te": "గో కార్ట్", "mr": "गो कार्ट", "ta": "கோ கார்ட்", "gu": "ગો કાર્ટ", "ur": "گو کارٹ", "kn": "ಗೋ ಕಾರ್ಟ್", "ml": "ഗോ കാർട്ട്", "pa": "ਗੋ ਕਾਰਟ", "or": "ଗୋ କାର୍ଟ", "as": "গ' কাৰ্ট", "es": "Kart", "fr": "Kart", "de": "Kart", "ar": "سيارة كارتينغ", "zh": "卡丁车", "ru": "Карт", "pt": "Kart", "ja": "ゴーカート", "ko": "고카트", "it": "Kart", "tr": "Go-kart", "nl": "Kart", "pl": "Gokart", "id": "Gokart", "th": "โกคาร์ท", "vi": "Xe đua go-kart", "fa": "کارتینگ", "ne": "गो कार्ट", "si": "ගෝ කාර්ට්"},
    {"num": 38, "en": "Skateboard", "hi": "स्केटबोर्ड", "bn": "স্কেটবোর্ড", "te": "స్కేట్‌బోర్డ్", "mr": "स्केटबोर्ड", "ta": "சறுக்குப் பலகை", "gu": "સ્કેટબોર્ડ", "ur": "اسکیٹ بورڈ", "kn": "ಸ್ಕೇಟ್‌ಬೋರ್ಡ್", "ml": "സ്കേറ്റ്ബോർഡ്", "pa": "ਸਕੇਟਬੋਰਡ", "or": "ସ୍ମେଟବୋର୍ଡ", "as": "স্কেটব'ৰ্ড", "es": "Monopatín", "fr": "Planche à roulettes", "de": "Skateboard", "ar": "لوح تزلج", "zh": "滑板", "ru": "Скейтборд", "pt": "Skate", "ja": "スケートボード", "ko": "스케이트보드", "it": "Skateboard", "tr": "Kaykay", "nl": "Skateboard", "pl": "Deskorolka", "id": "Papan Seluncur", "th": "สเก็ตบอร์ด", "vi": "Ván trượt", "fa": "اسکیت‌برد", "ne": "स्केटबोर्ड", "si": "ස්කේට්බෝඩ් එක"},
    {"num": 39, "en": "Roller Skates", "hi": "रोलर स्केट्स", "bn": "রোলার স্কেটিং জুতো", "te": "రోలర్ స్కేట్స్", "mr": "रोलर स्केट्स", "ta": "சக்கர காலணி", "gu": "રોલર સ્કેટ્સ", "ur": "رولر اسکیٹس", "kn": "ರೋಲರ್ ಸ್ಕೇಟ್ಸ್", "ml": "റോളർ സ്കേറ്റ്സ്", "pa": "ਰੋਲਰ ਸਕੇਟਸ", "or": "ରୋଲର ସ୍କେଟ୍ସ", "as": "ৰ'লাৰ স্কেটছ", "es": "Patines de ruedas", "fr": "Patins à roulettes", "de": "Rollschuhe", "ar": "زلاجات بعجلات", "zh": "旱冰鞋", "ru": "Роликовые коньки", "pt": "Patins de rodas", "ja": "ローラースケート", "ko": "롤러스케이트", "it": "Pattini a rotelle", "tr": "Paten", "nl": "Rolschaatsen", "pl": "Wrotki", "id": "Sepatu Roda", "th": "โรลเลอร์สเก็ต", "vi": "Giày trượt patin", "fa": "اسکیت چرخ‌دار", "ne": "रोलर स्केट", "si": "රෝලර් සපත්තු"},
    {"num": 40, "en": "Cable Car", "hi": "उड़न खटोला (केबल कार)", "bn": "রোপওয়ে গাড়ি", "te": "కేబుల్ కార్", "mr": "उडणखटोला", "ta": "கயிறு வழி ஊர்தி", "gu": "ઉડનખટોલા", "ur": "کیبل کار", "kn": "ಕೇಬಲ್ ಕಾರ್", "ml": "കേബിൾ കാർ", "pa": "ਕੇਬਲ ਕਾਰ", "or": "ରୋପୱେ କାର", "as": "কেবুল কাৰ", "es": "Teleférico", "fr": "Téléphérique", "de": "Seilbahn", "ar": "تلفريك", "zh": "缆车", "ru": "Канатная дорога", "pt": "Teleférico", "ja": "ロープウェイ", "ko": "케이블카", "it": "Funivia", "tr": "Teleferik", "nl": "Kabelbaan", "pl": "Kolejka linowa", "id": "Kereta Gantung", "th": "กระเช้าลอยฟ้า", "vi": "Cáp treo", "fa": "تله‌کابین", "ne": "केबल कार", "si": "කේබල් කාර්"},
    {"num": 41, "en": "Sailboat", "hi": "पाल वाली नाव", "bn": "পালতোলা নৌকা", "te": "తెరచాప పడవ", "mr": "शिडाची बोट", "ta": "பாயமரப் படகு", "gu": "પાલવાળી હોડી", "ur": "بادبانی کشتی", "kn": "ಪಟದ ದೋಣಿ", "ml": "പായ്‌വഞ്ചി", "pa": "ਪਾਲ ਵਾਲੀ ਕਿਸ਼ਤੀ", "or": "ପାଲଟଣା ଡଙ୍ଗା", "as": "পালতোলা নাও", "es": "Velero", "fr": "Voilier", "de": "Segelboot", "ar": "مركب شراعي", "zh": "帆船", "ru": "Парусник", "pt": "Veleiro", "ja": "セイルボート", "ko": "범선", "it": "Barca a vela", "tr": "Yelkenli", "nl": "Zeilboot", "pl": "Żaglówka", "id": "Perahu Layar", "th": "เรือใบ", "vi": "Thuyền buồm", "fa": "قایق بادبانی", "ne": "पाल डुङ्गा", "si": "රුවල් බෝට්ටුව"},
    {"num": 42, "en": "Canoe", "hi": "डोंगी नाव", "bn": "ডোঙা", "te": "చిన్న పడవ", "mr": "डोंगी", "ta": "மரப்படகு", "gu": "કેનો હોડી", "ur": "ڈونگی", "kn": "ದೋಣಿ ವಿಶೇಷ", "ml": "കനോ", "pa": "ਡੋਂਗੀ", "or": "ଡଙ୍ଗି", "as": "ডিঙি নাও", "es": "Canoa", "fr": "Canoë", "de": "Kanu", "ar": "زورق كنو", "zh": "独木舟", "ru": "Каноэ", "pt": "Canoa", "ja": "カヌー", "ko": "카누", "it": "Canoa", "tr": "Kano", "nl": "Kano", "pl": "Kanoe", "id": "Kano", "th": "เรือแคนู", "vi": "Xuồng kano", "fa": "کانو", "ne": "डुँगा", "si": "ඔරුව"},
    {"num": 43, "en": "Kayak", "hi": "कयाक", "bn": "কায়াক", "te": "కయాక్", "mr": "कयाक बोट", "ta": "கயாக் படகு", "gu": "કયાક", "ur": "کایاک", "kn": "ಕಯಾಕ್", "ml": "കയാക്", "pa": "ਕਾਇਆਕ", "or": "କାୟାକ", "as": "কায়াক", "es": "Kayak", "fr": "Kayak", "de": "Kajak", "ar": "قارب كاياك", "zh": "皮划艇", "ru": "Каяк", "pt": "Caiaque", "ja": "カヤック", "ko": "카약", "it": "Kayak", "tr": "Kayak", "nl": "Kajak", "pl": "Kajak", "id": "Kayak", "th": "เรือคายัค", "vi": "Thuyền kayak", "fa": "کایاک", "ne": "कायाक", "si": "කයාක් බෝට්ටුව"},
    {"num": 44, "en": "Speedboat", "hi": "स्पीडबोट", "bn": "স্পিডবোট", "te": "స్పీడ్‌బోట్", "mr": "स्पीडबोट", "ta": "வேகப் படகு", "gu": "ઝડપી હોડી", "ur": "اسپیڈ بوٹ", "kn": "ವೇಗದ ದೋಣಿ", "ml": "സ്പീഡ് ബോട്ട്", "pa": "ਸਪੀਡਬੋਟ", "or": "ସ୍ପିଡ଼ବୋଟ", "as": "স্পীডব'ট", "es": "Lancha rápida", "fr": "Canot à moteur rapide", "de": "Motorboot", "ar": "زورق سريع", "zh": "快艇", "ru": "Быстроходный катер", "pt": "Lancha rápida", "ja": "スピードボート", "ko": "모터보트", "it": "Motoscafo", "tr": "Sürat teknesi", "nl": "Speedboot", "pl": "Motorówka", "id": "Perahu Cepat", "th": "เรือเร็ว", "vi": "Cano cao tốc", "fa": "قایق تندرو", "ne": "स्पीडबोट", "si": "වේග බෝට්ටුව"},
    {"num": 45, "en": "Cargo Ship", "hi": "मालवाहक जहाज़", "bn": "মালবাহী জাহাজ", "te": "సరుకు రవాణా నౌక", "mr": "मालवाहू जहाज", "ta": "சரக்குக் கப்பல்", "gu": "માલવાહક વહાણ", "ur": "مال بردار جہاز", "kn": "ಸರಕು ಹಡಗು", "ml": "ചരക്കുകപ്പൽ", "pa": "ਮਾਲਵਾਹਕ ਜਹਾਜ਼", "or": "ମାଲବାହୀ ଜାହାଜ", "as": "মালবাহী জাহাজ", "es": "Barco de carga", "fr": "Cargo", "de": "Frachtschiff", "ar": "سفينة شحن", "zh": "货船", "ru": "Грузовое судно", "pt": "Navio cargueiro", "ja": "貨物船", "ko": "화물선", "it": "Nave da carico", "tr": "Kargo gemisi", "nl": "Vrachtschip", "pl": "Statek towarowy", "id": "Kapal Kargo", "th": "เรือบรรทุกสินค้า", "vi": "Tàu chở hàng", "fa": "کشتی باربری", "ne": "मालवाहक जहाज", "si": "භාණ්ඩ ප්‍රවාහන නෞකාව"},
    {"num": 46, "en": "Rickshaw", "hi": "साइकिल रिक्शा", "bn": "রিকশা", "te": "సైకిల్ రిక్షా", "mr": "हात रिक्षा", "ta": "சைக்கிள் ரிக்ஷா", "gu": "પેડલ રીક્ષા", "ur": "سائیکل رکشہ", "kn": "ಸೈಕಲ್ ರಿಕ್ಷಾ", "ml": "സൈക്കിൾ റിക്ഷ", "pa": "ਰਿਕਸ਼ਾ", "or": "ସାଇକେଲ ରିକ୍ସା", "as": "চাইকেল ৰিক্সা", "es": "Bicitaxi", "fr": "Pousse-pousse vélo", "de": "Rikscha", "ar": "عربة ريكشا", "zh": "人力黄包车", "ru": "Велорикша", "pt": "Bicitáxi", "ja": "輪タク", "ko": "자전거 인력거", "it": "Risciò", "tr": "Rikşa", "nl": "Riksja", "pl": "Riksza", "id": "Becak", "th": "สามล้อถีบ", "vi": "Xe xích lô", "fa": "ریکشا", "ne": "रिक्सा", "si": "රික්ෂෝව"},
    {"num": 47, "en": "Horse Cart", "hi": "घोड़ा गाड़ी (तांगा)", "bn": "ঘোড়ার গাড়ি", "te": "గుర్రపు బండి", "mr": "घोडागाडी (तांगा)", "ta": "குதிரை வண்டி", "gu": "ઘોડાગાડી", "ur": "تانگہ", "kn": "ಕುದುರೆ ಗಾಡಿ", "ml": "കുതിരവണ്ടി", "pa": "ਟਾਂਗਾ", "or": "ଘୋଡ଼ା ଗାଡ଼ି", "as": "ঘোঁৰা গাড়ী", "es": "Carruaje de caballos", "fr": "Calèche", "de": "Pferdekutsche", "ar": "عربة يجرها حصان", "zh": "马车", "ru": "Повозка", "pt": "Carroça de cavalos", "ja": "馬車", "ko": "마차", "it": "Carrozza a cavalli", "tr": "At arabası", "nl": "Paardenkar", "pl": "Wóz konny", "id": "Kereta Kuda", "th": "รถม้า", "vi": "Xe ngựa", "fa": "کالسکه‌", "ne": "घोडा गाडी", "si": "අශ්ව කරත්තය"},
    {"num": 48, "en": "Bullock Cart", "hi": "बैलगाड़ी", "bn": "গরুর গাড়ি", "te": "ఎడ్ల బండి", "mr": "बैलगाडी", "ta": "மாட்டு வண்டி", "gu": "બળદગાડું", "ur": "بیل گاڑی", "kn": "ಎತ್ತಿನ ಗಾಡಿ", "ml": "കാളവണ്ടി", "pa": "ਬੈਲ ਗੱਡੀ", "or": "ବଳଦ ଗାଡ଼ି", "as": "গৰুৰ গাড়ী", "es": "Carreta de bueyes", "fr": "Char à bœufs", "de": "Ochsenkarren", "ar": "عربة ثيران", "zh": "牛车", "ru": "Телега с волами", "pt": "Carro de boi", "ja": "牛車", "ko": "우차", "it": "Carro a buoi", "tr": "Öküz arabası", "nl": "Ossenkar", "pl": "Wóz wołowy", "id": "Gerobak Sapi", "th": "เกวียนวัว", "vi": "Xe bò kéo", "fa": "ارابه گاوی", "ne": "बयलगाडा", "si": "කරත්තය"},
    {"num": 49, "en": "Segway", "hi": "सेगवे (दो पहिया राइडर)", "bn": "সেগওয়ে", "te": "సెగ్వే", "mr": "सेगवे", "ta": "செக்வே ஊர்தி", "gu": "સેગવે", "ur": "سیگوے", "kn": "ಸೆಗ್ವೆ", "ml": "സെഗ്‌വേ", "pa": "ਸੈਗਵੇ", "or": "ସେଗୱେ", "as": "চেগৱে", "es": "Segway", "fr": "Gyropode", "de": "Segway", "ar": "سيجواي", "zh": "平衡车", "ru": "Сигвей", "pt": "Segway", "ja": "セグウェイ", "ko": "세그웨이", "it": "Segway", "tr": "Segway", "nl": "Segway", "pl": "Segway", "id": "Segway", "th": "เซกเวย์", "vi": "Xe tự cân bằng", "fa": "سگ‌وی", "ne": "सेगवे", "si": "සෙග්වේ"},
    {"num": 50, "en": "Quad Bike", "hi": "क्वॉड बाइक (चार पहिया बाइक)", "bn": "কোয়াড বাইক", "te": "క్వాడ్ బైక్", "mr": "क्वाड बाईक", "ta": "நான்கு சக்கர பைக்", "gu": "ક્વાડ બાઇક", "ur": "کواڈ بائیک", "kn": "ಕ್ವಾಡ್ ಬೈಕ್", "ml": "ക്വാഡ് ബൈക്ക്", "pa": "ਕਵਾਡ ਬਾਈਕ", "or": "କ୍ୱାଡ ବାଇକ", "as": "কোৱাড বাইক", "es": "Cuatrimoto (ATV)", "fr": "Quad", "de": "Quad", "ar": "دراجة رباعية", "zh": "四轮全地形车", "ru": "Квадроцикл", "pt": "Quadriciclo", "ja": "四輪バギー", "ko": "사륜오토바이", "it": "Quad", "tr": "ATV", "nl": "Quad", "pl": "Quad", "id": "Motor ATV", "th": "รถเอทีวี", "vi": "Xe địa hình ATV", "fa": "موتور چهارچرخ", "ne": "क्वाड बाइक", "si": "ක්වාඩ් බයිසිකලය"}
]

print(f"Vehicles loaded: {len(VEHICLES)}")
