#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
50 Birds (pakshi) with all 33 language translations.
10 FREE (id 1-10), 40 PREMIUM (id 11-50).
"""

BIRDS = [
    # 1-10 FREE
    {"num": 1, "en": "Parrot", "hi": "तोता", "bn": "তোতা", "te": "చిలుక", "mr": "पोपट", "ta": "கிளி", "gu": "પોપટ", "ur": "طوطا", "kn": "ಗಿಳಿ", "ml": "തത്ത", "pa": "ਤੋਤਾ", "or": "ଶୁଆ", "as": "ভাটৌ", "es": "Loro", "fr": "Perroquet", "de": "Papagei", "ar": "ببغاء", "zh": "鹦鹉", "ru": "Попугай", "pt": "Papagaio", "ja": "オウム", "ko": "앵무새", "it": "Pappagallo", "tr": "Papağan", "nl": "Papegaai", "pl": "Papuga", "id": "Burung Beo", "th": "นกแก้ว", "vi": "Con vẹt", "fa": "طوطی", "ne": "सुगा", "si": "ගිරවා"},
    {"num": 2, "en": "Peacock", "hi": "मोर", "bn": "ময়ূর", "te": "నెమలి", "mr": "मोर", "ta": "மயில்", "gu": "મોર", "ur": "مور", "kn": "ನವಿಲು", "ml": "മയിൽ", "pa": "ਮੋਰ", "or": "ମୟୂର", "as": "ময়ূৰ", "es": "Pavo real", "fr": "Paon", "de": "Pfau", "ar": "طاووس", "zh": "孔雀", "ru": "Павлин", "pt": "Pavão", "ja": "クジャク", "ko": "공작", "it": "Pavone", "tr": "Tavus kuşu", "nl": "Pauw", "pl": "Paw", "id": "Merak", "th": "นกยูง", "vi": "Con công", "fa": "طاووس", "ne": "मयूर", "si": "මොනරා"},
    {"num": 3, "en": "Pigeon", "hi": "कबूतर", "bn": "পায়রা", "te": "పావురం", "mr": "कबुतर", "ta": "புறா", "gu": "કબૂતર", "ur": "کبوتر", "kn": "ಪಾರಿವಾಳ", "ml": "പ്രാവ്", "pa": "ਕਬੂਤਰ", "or": "ପାରା", "as": "পাৰ চৰাই", "es": "Paloma", "fr": "Pigeon", "de": "Taube", "ar": "حمامة", "zh": "鸽子", "ru": "Голубь", "pt": "Pombo", "ja": "ハト", "ko": "비둘기", "it": "Piccione", "tr": "Güvercin", "nl": "Duif", "pl": "Gołąb", "id": "Merpati", "th": "นกพิราบ", "vi": "Bồ câu", "fa": "کبوتر", "ne": "परेवा", "si": "පරවියා"},
    {"num": 4, "en": "Crow", "hi": "कौआ", "bn": "কাক", "te": "కాకి", "mr": "कावळा", "ta": "காகம்", "gu": "કાગડો", "ur": "کوا", "kn": "ಕಾಗೆ", "ml": "കാക്ക", "pa": "ਕਾਂ", "or": "କାଉ", "as": "কাউৰী", "es": "Cuervo", "fr": "Corbeau", "de": "Krähe", "ar": "غراب", "zh": "乌鸦", "ru": "Ворона", "pt": "Corvo", "ja": "カラス", "ko": "까마귀", "it": "Corvo", "tr": "Karga", "nl": "Kraai", "pl": "Wrona", "id": "Gagak", "th": "อีกา", "vi": "Con quạ", "fa": "کلاغ", "ne": "काग", "si": "කපුටා"},
    {"num": 5, "en": "Sparrow", "hi": "गौरैया", "bn": "চড়ুই", "te": "పిచ్చుక", "mr": "चिमणी", "ta": "சிட்டுக்குருவி", "gu": "ચકલી", "ur": "چڑیا", "kn": "ಗುಬ್ಬಚ್ಚಿ", "ml": "അങ്ങാടിക്കുരുവി", "pa": "ਚਿੜੀ", "or": "ଘରଚଟିଆ", "as": "ঘৰচিৰিকা", "es": "Gorrión", "fr": "Moineau", "de": "Spatz", "ar": "عصفور", "zh": "麻雀", "ru": "Воробей", "pt": "Pardal", "ja": "スズメ", "ko": "참새", "it": "Passero", "tr": "Serçe", "nl": "Mus", "pl": "Wróbel", "id": "Burung Gereja", "th": "นกกระจอก", "vi": "Chim sẻ", "fa": "گنجشک", "ne": "भँगेरो", "si": "ගේ කුරුල්ලා"},
    {"num": 6, "en": "Eagle", "hi": "चील", "bn": "ঈগল", "te": "గద్ద", "mr": "गरुड", "ta": "கழுகு", "gu": "ગરુડ", "ur": "عقاب", "kn": "ಹದ್ದು", "ml": "പരുന്ത്", "pa": "ਉਕਾਬ", "or": "ଚିଲ", "as": "ঈগল", "es": "Águila", "fr": "Aigle", "de": "Adler", "ar": "نسر", "zh": "鹰", "ru": "Орёл", "pt": "Águia", "ja": "ワシ", "ko": "독수리", "it": "Aquila", "tr": "Kartal", "nl": "Arend", "pl": "Orzeł", "id": "Elang", "th": "นกอินทรี", "vi": "Đại bàng", "fa": "عقاب", "ne": "चील", "si": "රාජාලියා"},
    {"num": 7, "en": "Owl", "hi": "उल्लू", "bn": "পেঁচা", "te": "గుడ్లగూబ", "mr": "घुबड", "ta": "ஆந்தை", "gu": "ઘુવડ", "ur": "الو", "kn": "ಗೂಬೆ", "ml": "മൂങ്ങ", "pa": "ਉੱਲੂ", "or": "ପେଚା", "as": "ফেঁচা", "es": "Búho", "fr": "Hibou", "de": "Eule", "ar": "بومة", "zh": "猫头鹰", "ru": "Сова", "pt": "Coruja", "ja": "フクロウ", "ko": "올빼미", "it": "Gufo", "tr": "Baykuş", "nl": "Uil", "pl": "Sowa", "id": "Burung Hantu", "th": "นกฮูก", "vi": "Cú mèo", "fa": "جغد", "ne": "उल्लु", "si": "බකමූණා"},
    {"num": 8, "en": "Duck", "hi": "बत्तख", "bn": "হাঁস", "te": "బాతు", "mr": "बदक", "ta": "வாத்து", "gu": "બતક", "ur": "بطخ", "kn": "ಬಾತುಕೋಳಿ", "ml": "താറാവ്", "pa": "ਬੱਤਖ", "or": "ବତକ", "as": "হাঁহ", "es": "Pato", "fr": "Canard", "de": "Ente", "ar": "بطة", "zh": "鸭子", "ru": "Утка", "pt": "Pato", "ja": "アヒル", "ko": "오리", "it": "Anatra", "tr": "Ördek", "nl": "Eend", "pl": "Kaczka", "id": "Bebek", "th": "เป็ด", "vi": "Con vịt", "fa": "اردک", "ne": "हाँस", "si": "තාරාවා"},
    {"num": 9, "en": "Swan", "hi": "हंस", "bn": "রাজহাঁস", "te": "హంస", "mr": "हंस", "ta": "அன்னப்பறவை", "gu": "હંસ", "ur": "ہنس", "kn": "ಹಂಸ", "ml": "അരയന്നം", "pa": "ਹੰਸ", "or": "ହଂସ", "as": "ৰাজহাঁহ", "es": "Cisne", "fr": "Cygne", "de": "Schwan", "ar": "تم", "zh": "天鹅", "ru": "Лебедь", "pt": "Cisne", "ja": "ハクチョウ", "ko": "백조", "it": "Cigno", "tr": "Kuğu", "nl": "Zwaan", "pl": "Łabędź", "id": "Angsa", "th": "หงส์", "vi": "Thiên nga", "fa": "قو", "ne": "राजहंस", "si": "හංසයා"},
    {"num": 10, "en": "Hen", "hi": "मुर्गी", "bn": "মুরগি", "te": "కోడిపెట్ట", "mr": "कोंबडी", "ta": "கோழி", "gu": "મરઘી", "ur": "مرغی", "kn": "ಕೋಳಿ", "ml": "കോഴി", "pa": "ਮੁਰਗੀ", "or": "କୁକୁଡ଼ା", "as": "কুকুৰা", "es": "Gallina", "fr": "Poule", "de": "Henne", "ar": "دجاجة", "zh": "母鸡", "ru": "Курица", "pt": "Galinha", "ja": "メンドリ", "ko": "암탉", "it": "Gallina", "tr": "Tavuk", "nl": "Kip", "pl": "Kura", "id": "Ayam Betina", "th": "แม่ไก่", "vi": "Gà mái", "fa": "مرغ", "ne": "कुखुरा", "si": "කිකිළිය"},

    # 11-50 PREMIUM
    {"num": 11, "en": "Rooster", "hi": "मुर्गा", "bn": "মোরগ", "te": "పుంజు", "mr": "कोंबडा", "ta": "சேவல்", "gu": "કૂકડો", "ur": "مرغا", "kn": "ಹುಂಜ", "ml": "പൂവൻകോഴി", "pa": "ਕੁੱਕੜ", "or": "ଗଞ୍ଜା", "as": "মতা কুকুৰা", "es": "Gallo", "fr": "Coq", "de": "Hahn", "ar": "ديك", "zh": "公鸡", "ru": "Петух", "pt": "Galo", "ja": "オンドリ", "ko": "수탉", "it": "Gallo", "tr": "Horoz", "nl": "Haan", "pl": "Kogut", "id": "Ayam Jantan", "th": "ไก่โต้ง", "vi": "Gà trống", "fa": "خروس", "ne": "भाले", "si": "කුකුළා"},
    {"num": 12, "en": "Kingfisher", "hi": "रामचिरैया", "bn": "মাছরাঙা", "te": "లకుముకిపిట్ట", "mr": "खंड्या", "ta": "மீன்கொத்தி", "gu": "કલકલિયો", "ur": "کنگ فشر", "kn": "ಮೀಂಚುಳ್ಳಿ", "ml": "പൊന്മാൻ", "pa": "ਮੱਛੀਮਾਰ", "or": "ମାଛରଙ୍କା", "as": "মাছৰোকা", "es": "Martín pescador", "fr": "Martin-pêcheur", "de": "Eisvogel", "ar": "رفراف", "zh": "翠鸟", "ru": "Зимородок", "pt": "Guarda-rios", "ja": "カワセミ", "ko": "물총새", "it": "Martin pescatore", "tr": "Yalıçapkını", "nl": "IJsvogel", "pl": "Zimorodek", "id": "Raja Udang", "th": "นกกะเต็น", "vi": "Chim bói cá", "fa": "ماهی‌خورک", "ne": "माछापुच्छ्रे", "si": "පිළිහුඩුවා"},
    {"num": 13, "en": "Woodpecker", "hi": "कठफोड़वा", "bn": "কাঠঠোকরা", "te": "వడ్రంగిపిట్ట", "mr": "सुतार पक्षी", "ta": "மரங்கொத்தி", "gu": "લક્કડખોદ", "ur": "ہدہد", "kn": "ಮರಕುಟಿಗ", "ml": "മരംകൊത്തി", "pa": "ਲੱਕੜਫੋੜ", "or": "କାଠହଣା", "as": "কাঠৰোকা", "es": "Pájaro carpintero", "fr": "Pic vert", "de": "Specht", "ar": "نقار الخشب", "zh": "啄木鸟", "ru": "Дятел", "pt": "Pica-pau", "ja": "キツツキ", "ko": "딱따구리", "it": "Picchio", "tr": "Ağaçkakan", "nl": "Specht", "pl": "Dzięcioł", "id": "Burung Pelatuk", "th": "นกหัวขวาน", "vi": "Chim gõ kiến", "fa": "دارکوب", "ne": "काठखोरो", "si": "කොට්ටෝරුවා"},
    {"num": 14, "en": "Penguin", "hi": "पेंगुइन", "bn": "পেঙ্গুইন", "te": "పెంగ్విన్", "mr": "पेंग्विन", "ta": "பென்குயின்", "gu": "પેંગ્વિન", "ur": "پینگوئن", "kn": "ಪೆಂಗ್ವಿನ್", "ml": "പെൻഗ്വിൻ", "pa": "ਪੈਂਗੁਇਨ", "or": "ପେଙ୍ଗୁଇନ", "as": "পেংগুইন", "es": "Pingüino", "fr": "Manchot", "de": "Pinguin", "ar": "بطريق", "zh": "企鹅", "ru": "Пингвин", "pt": "Pinguim", "ja": "ペンギン", "ko": "펭귄", "it": "Pinguino", "tr": "Penguen", "nl": "Pinguïn", "pl": "Pingwin", "id": "Pinguin", "th": "เพนกวิน", "vi": "Chim cánh cụt", "fa": "پنگوئن", "ne": "पेन्गुइन", "si": "පෙන්ගුයින්"},
    {"num": 15, "en": "Flamingo", "hi": "राजहंस (फ्लेमिंगो)", "bn": "ফ্লেমিঙ্গো", "te": "ఫ్లెమింగో", "mr": "रोहित पक्षी", "ta": "பூநாரை", "gu": "સુરખાબ", "ur": "فلیمنگو", "kn": "ಫ್ಲೆಮಿಂಗೊ", "ml": "ഫ്ലെമിംഗോ", "pa": "ਫਲੇਮਿੰਗੋ", "or": "ମରାଳ", "as": "ফ্লেমিংগো", "es": "Flamenco", "fr": "Flamant rose", "de": "Flamingo", "ar": "نحام", "zh": "火烈鸟", "ru": "Фламинго", "pt": "Flamingo", "ja": "フラミンゴ", "ko": "플라밍고", "it": "Fenicottero", "tr": "Flamingo", "nl": "Flamingo", "pl": "Flaming", "id": "Flamingo", "th": "นกฟลามิงโก", "vi": "Hồng hạc", "fa": "فلامینگو", "ne": "फ्लेमिङ्गो", "si": "හික්මීණා"},
    {"num": 16, "en": "Ostrich", "hi": "शुतुरमुर्ग", "bn": "উটপাখি", "te": "నిప్పుకోడి", "mr": "शहामृग", "ta": "தீக்கோழி", "gu": "શાહમૃગ", "ur": "شترمرغ", "kn": "ಉಷ್ಟ್ರಪಕ್ಷಿ", "ml": "തീപ്പക്ഷി", "pa": "ਸ਼ੁਤਰਮੁਰਗ", "or": "ଓଟପକ୍ଷୀ", "as": "উটপখী", "es": "Avestruz", "fr": "Autruche", "de": "Strauß", "ar": "نعامة", "zh": "鸵鸟", "ru": "Страус", "pt": "Avestruz", "ja": "ダチョウ", "ko": "타조", "it": "Struzzo", "tr": "Deve kuşu", "nl": "Struisvogel", "pl": "Struś", "id": "Burung Unta", "th": "นกกระจอกเทศ", "vi": "Đà điểu", "fa": "شترمرغ", "ne": "अस्ट्रिच", "si": "ඔටුවා පක්ෂියා"},
    {"num": 17, "en": "Hummingbird", "hi": "गुंजन पक्षी", "bn": "হামিংবার্ড", "te": "హమ్మింగ్‌బర్డ్", "mr": "गुंजन पक्षी", "ta": "ஹம்மிங் பறவை", "gu": "હમિંગબર્ડ", "ur": "شکرخورا", "kn": "ಹಮ್ಮಿಂಗ್ ಬರ್ಡ್", "ml": "ഹംമിങ് ബേർഡ്", "pa": "ਹਮਿੰਗਬਰਡ", "or": "ହମିଙ୍ଗବାର୍ଡ", "as": "হামিংবাৰ্ড", "es": "Colibrí", "fr": "Colibri", "de": "Kolibri", "ar": "طائر الطنان", "zh": "蜂鸟", "ru": "Колибри", "pt": "Beija-flor", "ja": "ハチドリ", "ko": "벌새", "it": "Colibrì", "tr": "Sinek kuşu", "nl": "Kolibrie", "pl": "Koliber", "id": "Burung Kolibri", "th": "นกฮัมมิงเบิร์ด", "vi": "Chim ruồi", "fa": "مرغ مگس‌خوار", "ne": "हमिङबर्ड", "si": "හමිං කුරුල්ලා"},
    {"num": 18, "en": "Vulture", "hi": "गिद्ध", "bn": "শকুনি", "te": "రాబందు", "mr": "गिधाड", "ta": "பருந்து", "gu": "ગીધ", "ur": "گدھ", "kn": "ರಣಹದ್ದು", "ml": "കഴുകൻ", "pa": "ਗਿੱਧ", "or": "ଶାଗୁଣା", "as": "শগুন", "es": "Buitre", "fr": "Vautour", "de": "Geier", "ar": "نسر أصلع", "zh": "秃鹫", "ru": "Стервятник", "pt": "Abutre", "ja": "ハゲワシ", "ko": "대머리독수리", "it": "Avvoltoio", "tr": "Akbaba", "nl": "Gier", "pl": "Sęp", "id": "Hering", "th": "อีแร้ง", "vi": "Kền kền", "fa": "کرکس", "ne": "गिद्ध", "si": "ගිජුලිහිණියා"},
    {"num": 19, "en": "Crane", "hi": "सारस", "bn": "সারস", "te": "కొంగ", "mr": "सारस", "ta": "கொக்கு", "gu": "સારસ", "ur": "سارس", "kn": "ಬೆಳ್ಳಕ್ಕಿ", "ml": "കൊക്ക്", "pa": "ਸਾਰਸ", "or": "ସାରସ", "as": "কপৌ চৰাই", "es": "Grulla", "fr": "Grue", "de": "Kranich", "ar": "كركي", "zh": "鹤", "ru": "Журавль", "pt": "Grou", "ja": "ツル", "ko": "두루미", "it": "Gru", "tr": "Turna", "nl": "Kraanvogel", "pl": "Żuraw", "id": "Bangau", "th": "นกกระเรียน", "vi": "Sếu", "fa": "درنا", "ne": "सारस", "si": "කොකා"},
    {"num": 20, "en": "Stork", "hi": "बगुला", "bn": "বক", "te": "నారాయణ పక్షి", "mr": "बगळा", "ta": "செங்கால் நாரை", "gu": "બગલો", "ur": "لقلق", "kn": "ಬಕ", "ml": "ചെങ്ങാലിപ്പക്ഷി", "pa": "ਬਗਲਾ", "or": "ବଗ", "as": "বগলী", "es": "Cigüeña", "fr": "Cigogne", "de": "Storch", "ar": "لقلق", "zh": "鹳", "ru": "Аист", "pt": "Cegonha", "ja": "コウノトリ", "ko": "황새", "it": "Cicogna", "tr": "Leylek", "nl": "Ooievaar", "pl": "Bocian", "id": "Bangau", "th": "นกกระสา", "vi": "Cò", "fa": "لک‌لک", "ne": "बकुल्ला", "si": "මානාවා"},
    {"num": 21, "en": "Pelican", "hi": "पेलिकन", "bn": "গগণবেড়", "te": "గూడబాతు", "mr": "पेण पक्षी", "ta": "கூழைக்கடா", "gu": "પેણ", "ur": "پیلیکن", "kn": "ಹೆಜ್ಜಾರ್ಲೆ", "ml": "കൂഴ", "pa": "ਪੈਲੀਕਨ", "or": "ପେଲିକାନ", "as": "ভেলা চৰাই", "es": "Pelícano", "fr": "Pélican", "de": "Pelikan", "ar": "بجع", "zh": "鹈鹕", "ru": "Пеликан", "pt": "Pelicano", "ja": "ペリカン", "ko": "펠리컨", "it": "Pellicano", "tr": "Pelikan", "nl": "Pelikaan", "pl": "Pelikan", "id": "Pelikan", "th": "นกกระทุง", "vi": "Bồ nông", "fa": "پلیکان", "ne": "पेलिकन", "si": "පැලිකන්"},
    {"num": 22, "en": "Hawk", "hi": "बाज", "bn": "বাজপাখি", "te": "డేగ", "mr": "शिक्रा", "ta": "பருந்து", "gu": "બાજ", "ur": "باز", "kn": "ಗಿಡುಗ", "ml": "പ്രാപ്പിടിയൻ", "pa": "ਬਾਜ਼", "or": "ବାଜ", "as": "শেন চৰাই", "es": "Halcón", "fr": "Faucon", "de": "Habicht", "ar": "صقر", "zh": "老鹰", "ru": "Ястреб", "pt": "Gavião", "ja": "タカ", "ko": "매", "it": "Falco", "tr": "Şahin", "nl": "Havik", "pl": "Jastrząb", "id": "Rajawali", "th": "เหยี่ยว", "vi": "Chim ưng", "fa": "شاهین", "ne": "बाज", "si": "උකුස්සා"},
    {"num": 23, "en": "Falcon", "hi": "शाहीन", "bn": "শালিখ", "te": "ఫాల్కన్", "mr": "फाल्कन", "ta": "வல்லூறு", "gu": "શાહીન", "ur": "شاہین", "kn": "ಫಾಲ್ಕನ್", "ml": "ഫാൽക്കൺ", "pa": "ਸ਼ਾਹੀਨ", "or": "ଫାଲକନ", "as": "ফেলকন", "es": "Halcón peregrino", "fr": "Faucon pèlerin", "de": "Falke", "ar": "شاهين", "zh": "隼", "ru": "Сокол", "pt": "Falcão", "ja": "ハヤブサ", "ko": "송골매", "it": "Falcone", "tr": "Doğan", "nl": "Valk", "pl": "Sokół", "id": "Alap-alap", "th": "เหยี่ยวเพเรกริน", "vi": "Cắt", "fa": "بحری", "ne": "फाल्कन", "si": "කුරුළු රාජාලියා"},
    {"num": 24, "en": "Cuckoo", "hi": "कोयल", "bn": "কোকিল", "te": "కోకిల", "mr": "कोकिळा", "ta": "குயில்", "gu": "કોયલ", "ur": "کوئل", "kn": "ಕೋಗಿಲೆ", "ml": "കുയിൽ", "pa": "ਕੋਇਲ", "or": "କୋଇଲି", "as": "কুলী", "es": "Cuco", "fr": "Coucou", "de": "Kuckuck", "ar": "وقواق", "zh": "布谷鸟", "ru": "Кукушка", "pt": "Cuco", "ja": "カッコウ", "ko": "뻐꾸기", "it": "Cuculo", "tr": "Guguk kuşu", "nl": "Koekoek", "pl": "Kukułka", "id": "Burung Tekukur", "th": "นกคุกคู", "vi": "Chim cu cu", "fa": "فاخته", "ne": "कोइली", "si": "කොහා"},
    {"num": 25, "en": "Goose", "hi": "कलहंस", "bn": "রাজহংসী", "te": "పెద్ద బాతు", "mr": "राजहंस", "ta": "வாத்துப்பறவை", "gu": "રાજહંસ", "ur": "راج ہنس", "kn": "ಬಾತು", "ml": "വാത്ത", "pa": "ਹੰਸਣੀ", "or": "ଗୀଜ", "as": "ৰাজহাঁহ", "es": "Ganso", "fr": "Oie", "de": "Gans", "ar": "إوزة", "zh": "鹅", "ru": "Гусь", "pt": "Ganso", "ja": "ガチョウ", "ko": "거위", "it": "Oca", "tr": "Kaz", "nl": "Gans", "pl": "Gęś", "id": "Angsa", "th": "ห่าน", "vi": "Con ngỗng", "fa": "غاز", "ne": "हाँस", "si": "පාත්තයා"},
    {"num": 26, "en": "Turkey", "hi": "टर्की", "bn": "টার্কি", "te": "టర్కీ కోడి", "mr": "टर्की पक्षी", "ta": "வான்கோழி", "gu": "ટર્કી", "ur": "ٹرکی", "kn": "ಟರ್ಕಿ ಕೋಳಿ", "ml": "ടർക്കി കോഴി", "pa": "ਟਰਕੀ", "or": "ଟର୍କି", "as": "টাৰ্কী", "es": "Pavo", "fr": "Dindon", "de": "Truthahn", "ar": "ديك رومي", "zh": "火鸡", "ru": "Индейка", "pt": "Peru", "ja": "七面鳥", "ko": "칠면조", "it": "Tacchino", "tr": "Hindi", "nl": "Kalkoen", "pl": "Indyk", "id": "Kalkun", "th": "ไก่งวง", "vi": "Gà tây", "fa": "بوقلمون", "ne": "टर्की", "si": "කළුකුමා"},
    {"num": 27, "en": "Quail", "hi": "बटेर", "bn": "কোয়েল পাখি", "te": "కంజు పిట్ట", "mr": "लाव्हा पक्षी", "ta": "காடை", "gu": "બટેર", "ur": "بٹیر", "kn": "ಕಾಡುಕೋಳಿ", "ml": "കാട", "pa": "ਬਟੇਰ", "or": "ବଟେର", "as": "বটা চৰাই", "es": "Codorniz", "fr": "Caille", "de": "Wachtel", "ar": "سمان", "zh": "鹌鹑", "ru": "Перепел", "pt": "Codorna", "ja": "ウズラ", "ko": "메추라기", "it": "Quaglia", "tr": "Bıldırcın", "nl": "Kwartel", "pl": "Przepiórka", "id": "Burung Puyuh", "th": "นกคุ่ม", "vi": "Chim cút", "fa": "بلدرچین", "ne": "बट्टाई", "si": "වටුවා"},
    {"num": 28, "en": "Partridge", "hi": "तीतर", "bn": "তিতির", "te": "తీతువు పిట్ట", "mr": "तीतर", "ta": "கவுதாரி", "gu": "તેતર", "ur": "تیتر", "kn": "ತೀತರ್", "ml": "തീത്തർ", "pa": "ਤੀਤਰ", "or": "ତୀତର", "as": "তিতৰ", "es": "Perdiz", "fr": "Perdrix", "de": "Rebhuhn", "ar": "حجل", "zh": "鹧鸪", "ru": "Куропатка", "pt": "Perdiz", "ja": "ヤマウズラ", "ko": "자고새", "it": "Pernice", "tr": "Keklik", "nl": "Patrijs", "pl": "Kuropatwa", "id": "Burung Alap", "th": "นกกระทา", "vi": "Gà gô", "fa": "کبک", "ne": "तित्रा", "si": "තිත් වටුවා"},
    {"num": 29, "en": "Seagull", "hi": "गंगा-चील", "bn": "গাঙচিল", "te": "సముద్రపు కాకి", "mr": "समुद्री पक्षी", "ta": "கடல் புறா", "gu": "જળકૂકડી", "ur": "بحری بگلا", "kn": "ಸಮುದ್ರ ಹಕ್ಕಿ", "ml": "കടൽക്കാക്ക", "pa": "ਸਮੁੰਦਰੀ ਚਿੜੀ", "or": "ଗାଙ୍ଗଚିଲ", "as": "গাংচিল", "es": "Gaviota", "fr": "Mouette", "de": "Möwe", "ar": "نورس", "zh": "海鸥", "ru": "Чайка", "pt": "Gaivota", "ja": "カモメ", "ko": "갈매기", "it": "Gabbiano", "tr": "Martı", "nl": "Meeuw", "pl": "Mewa", "id": "Burung Camar", "th": "นกนางนวล", "vi": "Mòng biển", "fa": "مرغ نوروزی", "ne": "गंगा चील", "si": "මුහුදු ලිහිණියා"},
    {"num": 30, "en": "Hornbill", "hi": "धनेश पक्षी", "bn": "ধনেশ", "te": "కోకిల పక్షి", "mr": "धनेश", "ta": "இருவாச்சி", "gu": "ચિલોત્રો", "ur": "دھنیش", "kn": "ಮಂಗಟ್ಟೆ", "ml": "വേഴാമ്പൽ", "pa": "ਧਨੇਸ਼", "or": "ଧନେଶ", "as": "ধনেশ", "es": "Calao", "fr": "Calao", "de": "Nashornvogel", "ar": "أبو قرن", "zh": "犀鸟", "ru": "Птица-носорог", "pt": "Calau", "ja": "サイチョウ", "ko": "코뿔새", "it": "Bucero", "tr": "Boynuzgaga", "nl": "Neushoornvogel", "pl": "Dzioborożec", "id": "Burung Rangkong", "th": "นกเงือก", "vi": "Chim hồng hoàng", "fa": "نوک‌شاخ", "ne": "धनेश", "si": "කෑදැත්තා"},
    {"num": 31, "en": "Toucan", "hi": "टूकन", "bn": "টুকান", "te": "టూకాన్", "mr": "टुकन", "ta": "டூக்கன்", "gu": "ટૂકન", "ur": "توکان", "kn": "ಟೂಕನ್", "ml": "ടൂക്കൻ", "pa": "ਟੂਕਨ", "or": "ଟୁକାନ", "as": "টুকান", "es": "Tucán", "fr": "Toucan", "de": "Tukan", "ar": "طوقان", "zh": "巨嘴鸟", "ru": "Тукан", "pt": "Tucano", "ja": "オオハシ", "ko": "투칸", "it": "Tucano", "tr": "Tukan", "nl": "Toekan", "pl": "Tukan", "id": "Tukan", "th": "นกทูแคน", "vi": "Chim toucan", "fa": "توکان", "ne": "टुक्यान", "si": "ටූකන්"},
    {"num": 32, "en": "Canary", "hi": "कैनरी", "bn": "ক্যানারি পাখি", "te": "కనరీ పిట్ట", "mr": "कॅनरी", "ta": "கேனரி பறவை", "gu": "કેનેરી", "ur": "کینری", "kn": "ಕ್ಯಾನರಿ", "ml": "കാനറി", "pa": "ਕੈਨਰੀ", "or": "କାନାରି", "as": "কেনাৰী", "es": "Canario", "fr": "Canari", "de": "Kanarienvogel", "ar": "كناري", "zh": "金丝雀", "ru": "Канарейка", "pt": "Canário", "ja": "カナリア", "ko": "카나리아", "it": "Canarino", "tr": "Kanarya", "nl": "Kanarie", "pl": "Kanarek", "id": "Kenari", "th": "นกคานารี", "vi": "Chim hoàng yến", "fa": "قناری", "ne": "क्यानरी", "si": "කැනරි"},
    {"num": 33, "en": "Nightingale", "hi": "बुलबुल", "bn": "বুলবুল", "te": "కోయిల పిట్ట", "mr": "बुलबुल", "ta": "வானம்பாடி", "gu": "બુલબુલ", "ur": "بلبل", "kn": "ಬುಲ್ ಬುಲ್", "ml": "നൈറ്റിംഗേൽ", "pa": "ਬੁਲਬੁਲ", "or": "ବୁଲବୁଲ", "as": "বুলবুলী", "es": "Ruiseñor", "fr": "Rossignol", "de": "Nachtigall", "ar": "عندليب", "zh": "夜莺", "ru": "Соловей", "pt": "Rouxinol", "ja": "サヨナキドリ", "ko": "나이팅게일", "it": "Usignolo", "tr": "Bülbül", "nl": "Nachtegaal", "pl": "Słowik", "id": "Burung Bulbul", "th": "นกไนติงเกล", "vi": "Họa mi", "fa": "هزاردستان", "ne": "बुलबुल", "si": "නයිටිංගේල්"},
    {"num": 34, "en": "Robin", "hi": "लाल छाती वाली चिड़िया", "bn": "রবিন পাখি", "te": "రాబిన్ పిట్ట", "mr": "रॉबिन", "ta": "ராபின்", "gu": "રોબિન", "ur": "روبن", "kn": "ರಾಬಿನ್", "ml": "റോബിൻ", "pa": "ਰਾਬਿਨ", "or": "ରବିନ", "as": "ৰবিন", "es": "Petirrojo", "fr": "Rouge-gorge", "de": "Rotkehlchen", "ar": "أبو الحناء", "zh": "知更鸟", "ru": "Зарянка", "pt": "Pisco-de-peito-ruivo", "ja": "コマドリ", "ko": "울새", "it": "Pettirosso", "tr": "Kızılgerdan", "nl": "Roodborstje", "pl": "Rudzik", "id": "Burung Robin", "th": "นกโรบิน", "vi": "Chim cổ đỏ", "fa": "سینه‌سرخ", "ne": "रोबिन", "si": "රොබින්"},
    {"num": 35, "en": "Blue Jay", "hi": "नीलकंठ (ब्लू जे)", "bn": "নীলকণ্ঠ", "te": "పాలపిట్ట", "mr": "नीलकंठ", "ta": "நீலச்சிறகி", "gu": "નીલકંઠ", "ur": "نیل کنٹھ", "kn": "ನೀಲಕಂಠ", "ml": "പനങ്കാക്ക", "pa": "ਨੀਲਕੰਠ", "or": "ନୀଳକଣ୍ଠ", "as": "নীলকণ্ঠ", "es": "Arrendajo azul", "fr": "Geai bleu", "de": "Blauhäher", "ar": "قيق أزرق", "zh": "蓝松鸦", "ru": "Голубая сойка", "pt": "Gaio-azul", "ja": "アオカケス", "ko": "어치", "it": "Ghiandaia azzurra", "tr": "Mavi alakarga", "nl": "Blauwe gaai", "pl": "Sójka błękitna", "id": "Blue Jay", "th": "บลูเจย์", "vi": "Giẻ cùi lam", "fa": "جیجاق کبود", "ne": "निलकण्ठ", "si": "නිල් කවුඩා"},
    {"num": 36, "en": "Goldfinch", "hi": "सुनहरी चिड़िया", "bn": "সোনার চড়ুই", "te": "బంగారు పిట్ట", "mr": "सोनकिडा पक्षी", "ta": "தங்கச்சிட்டு", "gu": "સોનેરી પંખી", "ur": "سون چڑیا", "kn": "ಚಿನ್ನದ ಹಕ್ಕಿ", "ml": "സ്വർണ്ണക്കുരുവി", "pa": "ਸੁਨਹਿਰੀ ਚਿੜੀ", "or": "ସୁନେଲି ଚଢେଇ", "as": "সোণালী চৰাই", "es": "Jilguero", "fr": "Chardonneret", "de": "Stieglitz", "ar": "حسون", "zh": "金翅雀", "ru": "Щегол", "pt": "Pintassilgo", "ja": "カワラヒワ", "ko": "방울새", "it": "Cardellino", "tr": "Saka kuşu", "nl": "Putter", "pl": "Szczygieł", "id": "Goldfinch", "th": "โกลด์ฟินช์", "vi": "Sẻ thông vàng", "fa": "سهره طلایی", "ne": "सुनौलो भँगेरो", "si": "රන් කුරුල්ලා"},
    {"num": 37, "en": "Swallow", "hi": "अबाबील", "bn": "আবাবিল", "te": "వానకోయిల", "mr": "भिंगरी पक्षी", "ta": "தகைவிலான்", "gu": "દેવચકલી", "ur": "ابابیل", "kn": "ಬಾನಾಡಿ", "ml": "മീവൽപക്ഷി", "pa": "ਅਬਾਬੀਲ", "or": "ଅବାବିଲ", "as": "বতাহী চৰাই", "es": "Golondrina", "fr": "Hirondelle", "de": "Schwalbe", "ar": "خطاف", "zh": "燕子", "ru": "Ласточка", "pt": "Andorinha", "ja": "ツバメ", "ko": "제비", "it": "Rondine", "tr": "Kırlangıç", "nl": "Zwaluw", "pl": "Jaskółka", "id": "Burung Layang-layang", "th": "นกนางแอ่น", "vi": "Chim én", "fa": "پرستو", "ne": "गौंथली", "si": "වැහි ලිහිණියා"},
    {"num": 38, "en": "Kite", "hi": "चील पक्षी", "bn": "চিল", "te": "గద్దపిట్ట", "mr": "घार", "ta": "பருந்து", "gu": "સમળી", "ur": "چیل", "kn": "ಹಾರುವ ಹದ್ದು", "ml": "പരുന്ത്", "pa": "ਇੱਲ੍ਹ", "or": "ଚିଲ", "as": "চিলনী", "es": "Milano", "fr": "Milan", "de": "Milan", "ar": "حدأة", "zh": "鸢", "ru": "Коршун", "pt": "Milhafre", "ja": "トビ", "ko": "솔개", "it": "Nibbio", "tr": "Çaylak", "nl": "Wouw", "pl": "Kania", "id": "Layang-layang", "th": "เหยี่ยวดำ", "vi": "Diều hâu", "fa": "کورکور", "ne": "चील", "si": "උකුස්සා"},
    {"num": 39, "en": "Kiwi Bird", "hi": "कीवी पक्षी", "bn": "কিউই", "te": "కివీ పక్షి", "mr": "किवी पक्षी", "ta": "கிவி பறவை", "gu": "કિવી", "ur": "کیوی", "kn": "ಕಿವಿ ಪಕ್ಷಿ", "ml": "കിവി പക്ഷി", "pa": "ਕੀਵੀ", "or": "କିୱି", "as": "কিৱি চৰাই", "es": "Kiwi", "fr": "Kiwi", "de": "Kiwi", "ar": "كيوي", "zh": "几维鸟", "ru": "Киви", "pt": "Quiuí", "ja": "キーウィ", "ko": "키위새", "it": "Kiwi", "tr": "Kivi", "nl": "Kiwi", "pl": "Kiwi", "id": "Burung Kiwi", "th": "นกกีวี", "vi": "Chim kiwi", "fa": "کیوی", "ne": "किवी", "si": "කිවි කුරුල්ලා"},
    {"num": 40, "en": "Emu", "hi": "एमू", "bn": "এমু", "te": "ఈము పక్షి", "mr": "इमू", "ta": "ஈமு", "gu": "ઇમુ", "ur": "ایمو", "kn": "ಎಮು", "ml": "എമു", "pa": "ਏਮੂ", "or": "ଏମୁ", "as": "ইমু", "es": "Emú", "fr": "Émeu", "de": "Emu", "ar": "إيمو", "zh": "鸸鹋", "ru": "Эму", "pt": "Emu", "ja": "エミュー", "ko": "에뮤", "it": "Emù", "tr": "Emu", "nl": "Emoe", "pl": "Emu", "id": "Burung Emu", "th": "นกอีมู", "vi": "Đà điểu Úc", "fa": "شترمرغ استرالیایی", "ne": "इमु", "si": "එමු පක්ෂියා"},
    {"num": 41, "en": "Albatross", "hi": "अल्बाट्रॉस", "bn": "অ্যালবাট্রস", "te": "ఆల్బాట్రాస్", "mr": "अल्बाट्रॉस", "ta": "ஆல்பாட்ராஸ்", "gu": "આલ્બેટ્રોસ", "ur": "الباطروس", "kn": "ಆಲ್ಬಾಟ್ರೋಸ್", "ml": "ആൽബട്രോസ്", "pa": "ਐਲਬਾਟ੍ਰਾਸ", "or": "ଆଲବାଟ୍ରୋସ", "as": "এলবাট্ৰছ", "es": "Albatros", "fr": "Albatros", "de": "Albatros", "ar": "قطرس", "zh": "信天翁", "ru": "Альбатрос", "pt": "Albatroz", "ja": "アホウドリ", "ko": "알바트로스", "it": "Albatro", "tr": "Albatros", "nl": "Albatros", "pl": "Albatros", "id": "Albatros", "th": "นกอัลบาทรอส", "vi": "Hải âu", "fa": "آلباتروس", "ne": "अल्बाट्रस", "si": "ඇල්බට්‍රොස්"},
    {"num": 42, "en": "Macaw", "hi": "मकाऊ तोता", "bn": "ম্যাকাও", "te": "మకావ్ చిలుక", "mr": "मकाऊ", "ta": "மக்காவ்", "gu": "મકાઉ", "ur": "مکاؤ", "kn": "ಮಕಾವೋ", "ml": "മക്കാവോ", "pa": "ਮਕਾਓ", "or": "ମାକାଉ", "as": "মাকাও", "es": "Guacamayo", "fr": "Ara", "de": "Ara", "ar": "مكاو", "zh": "金刚鹦鹉", "ru": "Ара", "pt": "Arara", "ja": "コンゴウインコ", "ko": "마코앵무", "it": "Ara", "tr": "Ara papağanı", "nl": "Ara", "pl": "Ara", "id": "Makaw", "th": "นกมาคอว์", "vi": "Vẹt đuôi dài", "fa": "مکائو", "ne": "मकाउ", "si": "මැකෝ ගිරවා"},
    {"num": 43, "en": "Cockatoo", "hi": "काकातुआ", "bn": "কাকাতুয়া", "te": "కోకటూ", "mr": "काकाकुआ", "ta": "காக்கட்டூ", "gu": "કાકાકૌઆ", "ur": "کاکاتو", "kn": "ಕಾಕಟೂ", "ml": "കാക്കത്തൂ", "pa": "ਕਾਕਾਤੂਆ", "or": "କାକାତୁଆ", "as": "কাকাতুৱা", "es": "Cacatúa", "fr": "Cacatoès", "de": "Kakadu", "ar": "كوكاتو", "zh": "凤头鹦鹉", "ru": "Какаду", "pt": "Cacatua", "ja": "オウム", "ko": "코카투", "it": "Cacatua", "tr": "Kakadu", "nl": "Kaketoe", "pl": "Kakadu", "id": "Kakatua", "th": "นกกระตั้ว", "vi": "Vẹt mào", "fa": "طوطی کاکلی", "ne": "काकातुवा", "si": "කොකැටූ ගිරවා"},
    {"num": 44, "en": "Finch", "hi": "फिंच चिड़िया", "bn": "ফিঞ্চ", "te": "ఫించ్ పిట్ట", "mr": "फिंच", "ta": "பிஞ்ச்", "gu": "ફિંચ", "ur": "فنچ", "kn": "ಫಿಂಚ್", "ml": "ഫിഞ്ച്", "pa": "ਫਿੰਚ", "or": "ଫିଞ୍ଚ", "as": "ফিঞ্চ", "es": "Pinzón", "fr": "Pinson", "de": "Fink", "ar": "شرشور", "zh": "雀科鸟", "ru": "Зяблик", "pt": "Tentilhão", "ja": "アトリ", "ko": "되새", "it": "Fringuello", "tr": "İspinoz", "nl": "Vink", "pl": "Zięba", "id": "Finch", "th": "นกฟินช์", "vi": "Chim sẻ đất", "fa": "فنچ", "ne": "फिन्च", "si": "ෆින්ච්"},
    {"num": 45, "en": "Cormorant", "hi": "पनकौआ", "bn": "পানপৌড়ি", "te": "నీటి కాకి", "mr": "पाणकावळा", "ta": "நீர்க்காகம்", "gu": "જળકાગડો", "ur": "پانی کا کوا", "kn": "ನೀರುಕಾಗೆ", "ml": "നീർക്കാക്ക", "pa": "ਪਾਣੀ ਦਾ ਕਾਂ", "or": "ପାଣିକାଉ", "as": "পানীকাউৰী", "es": "Cormorán", "fr": "Cormoran", "de": "Kormoran", "ar": "غاق", "zh": "鸬鹚", "ru": "Баклан", "pt": "Corvo-marinho", "ja": "ウ", "ko": "가마우지", "it": "Cormorano", "tr": "Karabatak", "nl": "Aalscholver", "pl": "Kormoran", "id": "Burung Pecuk", "th": "นกกาน้ำ", "vi": "Cốc đế", "fa": "باکلان", "ne": "जलकाग", "si": "දිය කවුඩා"},
    {"num": 46, "en": "Heron", "hi": "बगुला (हेरॉन)", "bn": "বগা", "te": "కొంగ జాతి", "mr": "राखाडी बगळा", "ta": "நாரை", "gu": "બગલી", "ur": "بگلا", "kn": "ಬೆಳ್ಳಕ್ಕಿ ಜಾತಿ", "ml": "കൊക്ക് വർഗ്ഗം", "pa": "ਬਗਲਾ", "or": "ଧଳା ବଗ", "as": "বগলী", "es": "Garza", "fr": "Héron", "de": "Reiher", "ar": "بلشون", "zh": "苍鹭", "ru": "Цапля", "pt": "Garça", "ja": "サギ", "ko": "왜가리", "it": "Airone", "tr": "Balıkçıl", "nl": "Reiger", "pl": "Czapla", "id": "Kuntul", "th": "นกยาง", "vi": "Diệc", "fa": "حواصیل", "ne": "बकुल्ला", "si": "මැටි කොකා"},
    {"num": 47, "en": "Weaver Bird", "hi": "बया पक्षी", "bn": "বাবুই পাখি", "te": "గిజిగాడు", "mr": "सुगरण पक्षी", "ta": "தூக்கணாங்குருவி", "gu": "સુગરી", "ur": "بیا چڑیا", "kn": "ಗಿಜಿಗ", "ml": "തൂക്കണാംകുരുവി", "pa": "ਬਿਜੜਾ", "or": "ବାୟା ଚଢେଇ", "as": "টোকোৰা চৰাই", "es": "Pájaro tejedor", "fr": "Tisserin", "de": "Webervogel", "ar": "طائر الحباك", "zh": "织雀", "ru": "Ткачик", "pt": "Tecelão", "ja": "ハタオリドリ", "ko": "베짜는새", "it": "Tessitore", "tr": "Dokumacı kuşu", "nl": "Wever", "pl": "Wikłacz", "id": "Burung Tempua", "th": "นกกระจาบ", "vi": "Chim rồng rộc", "fa": "مرغ جولاهه", "ne": "तोपचरा", "si": "වඩුවා කුරුල්ලා"},
    {"num": 48, "en": "Kinglet", "hi": "नन्ही फुदकी", "bn": "কিংলেট", "te": "చిన్న పిట్ట", "mr": "छोटा पक्षी", "ta": "சிட்டுக் குருவி வகை", "gu": "નાની ચકલી", "ur": "کنگلٹ", "kn": "ಕಿಂಗ್ಲೆಟ್", "ml": "കിങ്‌ലെറ്റ്", "pa": "ਨਿੱਕੀ ਚਿੜੀ", "or": "ଛୋଟ ଚଢେଇ", "as": "সৰু চৰাই", "es": "Reyezuelo", "fr": "Roitelet", "de": "Goldhähnchen", "ar": "صعو", "zh": "戴菊", "ru": "Королёк", "pt": "Estrelinha", "ja": "キクイタダキ", "ko": "상모솔새", "it": "Fiorrancino", "tr": "Çalıkuşu", "nl": "Goudhaantje", "pl": "Mysikrólik", "id": "Kinglet", "th": "คิงเล็ต", "vi": "Tước mào vàng", "fa": "تاج‌طلایی", "ne": "सानो चरी", "si": "කුඩා කුරුල්ලා"},
    {"num": 49, "en": "Puffin", "hi": "पफिन पक्षी", "bn": "পাফিন", "te": "పఫిన్", "mr": "पफिन", "ta": "பஃபின்", "gu": "પફિન", "ur": "پفن", "kn": "ಪಫಿನ್", "ml": "പഫിൻ", "pa": "ਪਫਿਨ", "or": "ପଫିନ", "as": "পাফিন", "es": "Frailecillo", "fr": "Macareux", "de": "Papageitaucher", "ar": "بفن", "zh": "海鹦", "ru": "Тупик", "pt": "Papagaio-do-mar", "ja": "ツノメドリ", "ko": "바다퍼핀", "it": "Pulcinella di mare", "tr": "Kutup martısı", "nl": "Papegaaiduiker", "pl": "Maskonur", "id": "Puffin", "th": "นกพัฟฟิน", "vi": "Hải âu cổ rụt", "fa": "طوطی دریایی", "ne": "पफिन", "si": "පෆින්"},
    {"num": 50, "en": "Magpie", "hi": "नीलकंठ कौआ (मैगपाई)", "bn": "দোয়েল পাখি", "te": "మ్యాగ్‌పై", "mr": "भारद्वाज पक्षी", "ta": "வால் காக்கை", "gu": "દેવચકલી", "ur": "نیل کنٹھ", "kn": "ಮ್ಯಾಗ್ಪೈ", "ml": "മാഗ്പൈ", "pa": "ਮੈਗਪਾਈ", "or": "ମ୍ୟାଗପାଇ", "as": "ম্যাগপাই", "es": "Urraca", "fr": "Pie bavarde", "de": "Elster", "ar": "عقعق", "zh": "喜鹊", "ru": "Сорока", "pt": "Pega", "ja": "カササギ", "ko": "까치", "it": "Gazza", "tr": "Saksağan", "nl": "Ekster", "pl": "Sroka", "id": "Burung Murai", "th": "นกกางเขน", "vi": "Chim ác là", "fa": "زاغی", "ne": "रुपी", "si": "පොල්කිචිචා"}
]

print(f"Birds loaded: {len(BIRDS)}")
