#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
50 Animals (janwar) with all 33 language translations.
10 FREE (id 1-10), 40 PREMIUM (id 11-50).
"""

import json

ANIMALS = [
    # 1-10 FREE
    {"num": 1, "en": "Lion", "hi": "शेर", "bn": "সিংহ", "te": "సింహం", "mr": "सिंह", "ta": "சிங்கம்", "gu": "સિંહ", "ur": "شیر", "kn": "ಸಿಂಹ", "ml": "സിംഹം", "pa": "ਸ਼ੇਰ", "or": "ସିଂହ", "as": "সিংহ", "es": "León", "fr": "Lion", "de": "Löwe", "ar": "أسد", "zh": "狮子", "ru": "Лев", "pt": "Leão", "ja": "ライオン", "ko": "사자", "it": "Leone", "tr": "Aslan", "nl": "Leeuw", "pl": "Lew", "id": "Singa", "th": "สิงโต", "vi": "Sư tử", "fa": "شیر", "ne": "सिंह", "si": "සිංහයා"},
    {"num": 2, "en": "Tiger", "hi": "बाघ", "bn": "বাঘ", "te": "పులి", "mr": "वाघ", "ta": "புலி", "gu": "વાઘ", "ur": "باگھ", "kn": "ಹುಲಿ", "ml": "കടുവ", "pa": "ਬਾਘ", "or": "ବାଘ", "as": "বাঘ", "es": "Tigre", "fr": "Tigre", "de": "Tiger", "ar": "نمر", "zh": "老虎", "ru": "Тигр", "pt": "Tigre", "ja": "トラ", "ko": "호랑이", "it": "Tigre", "tr": "Kaplan", "nl": "Tijger", "pl": "Tygrys", "id": "Harimau", "th": "เสือ", "vi": "Hổ", "fa": "ببر", "ne": "बाघ", "si": "කොටියා"},
    {"num": 3, "en": "Elephant", "hi": "हाथी", "bn": "হাতি", "te": "ఏనుగు", "mr": "हत्ती", "ta": "யானை", "gu": "હાથી", "ur": "ہاتھی", "kn": "ಆನೆ", "ml": "ആന", "pa": "ਹਾਥੀ", "or": "ହାତୀ", "as": "হাতী", "es": "Elefante", "fr": "Éléphant", "de": "Elefant", "ar": "فيل", "zh": "大象", "ru": "Слон", "pt": "Elefante", "ja": "ゾウ", "ko": "코끼리", "it": "Elefante", "tr": "Fil", "nl": "Olifant", "pl": "Słoń", "id": "Gajah", "th": "ช้าง", "vi": "Voi", "fa": "فیل", "ne": "हात्ती", "si": "අලියා"},
    {"num": 4, "en": "Dog", "hi": "कुत्ता", "bn": "কুকুর", "te": "కుక్క", "mr": "कुत्रा", "ta": "நாய்", "gu": "કૂતરો", "ur": "کتا", "kn": "ನಾಯಿ", "ml": "പട്ടി", "pa": "ਕੁੱਤਾ", "or": "କୁକୁର", "as": "কুকুৰ", "es": "Perro", "fr": "Chien", "de": "Hund", "ar": "كلب", "zh": "狗", "ru": "Собака", "pt": "Cão", "ja": "犬", "ko": "개", "it": "Cane", "tr": "Köpek", "nl": "Hond", "pl": "Pies", "id": "Anjing", "th": "สุนัข", "vi": "Chó", "fa": "سگ", "ne": "कुकुर", "si": "බල්ලා"},
    {"num": 5, "en": "Cat", "hi": "बिल्ली", "bn": "বিড়াল", "te": "పిల్లి", "mr": "मांजर", "ta": "பூனை", "gu": "બિલાડી", "ur": "بلی", "kn": "ಬೆಕ್ಕು", "ml": "പൂച്ച", "pa": "ਬਿੱਲੀ", "or": "ବିଲେଇ", "as": "মেকুৰী", "es": "Gato", "fr": "Chat", "de": "Katze", "ar": "قطة", "zh": "猫", "ru": "Кошка", "pt": "Gato", "ja": "猫", "ko": "고양이", "it": "Gatto", "tr": "Kedi", "nl": "Kat", "pl": "Kot", "id": "Kucing", "th": "แมว", "vi": "Mèo", "fa": "گربه", "ne": "बिरालो", "si": "පූසා"},
    {"num": 6, "en": "Horse", "hi": "घोड़ा", "bn": "ঘোড়া", "te": "గుర్రం", "mr": "घोडा", "ta": "குதிரை", "gu": "ઘોડો", "ur": "گھوڑا", "kn": "ಕುದುರೆ", "ml": "കുതിര", "pa": "ਘੋੜਾ", "or": "ଘୋଡ଼ା", "as": "ঘোঁৰা", "es": "Caballo", "fr": "Cheval", "de": "Pferd", "ar": "حصان", "zh": "马", "ru": "Лошадь", "pt": "Cavalo", "ja": "馬", "ko": "말", "it": "Cavallo", "tr": "At", "nl": "Paard", "pl": "Koń", "id": "Kuda", "th": "ม้า", "vi": "Ngựa", "fa": "اسب", "ne": "घोडा", "si": "අශ්වයා"},
    {"num": 7, "en": "Cow", "hi": "गाय", "bn": "গরু", "te": "ఆవు", "mr": "गाय", "ta": "பசு", "gu": "ગાય", "ur": "گائے", "kn": "ಹಸು", "ml": "പശു", "pa": "ਗਾਂ", "or": "ଗାଈ", "as": "গৰু", "es": "Vaca", "fr": "Vache", "de": "Kuh", "ar": "بقرة", "zh": "奶牛", "ru": "Корова", "pt": "Vaca", "ja": "牛", "ko": "소", "it": "Mucca", "tr": "İnek", "nl": "Koe", "pl": "Krowa", "id": "Sapi", "th": "วัว", "vi": "Bò", "fa": "گاو", "ne": "गाई", "si": "එළදෙන"},
    {"num": 8, "en": "Monkey", "hi": "बंदर", "bn": "বানর", "te": "కోతి", "mr": "माकड", "ta": "குரங்கு", "gu": "વાંદરો", "ur": "بندر", "kn": "ಕೋತಿ", "ml": "കുരങ്ങ്", "pa": "ਬਾਂਦਰ", "or": "ମାଙ୍କଡ଼", "as": "বান্দৰ", "es": "Mono", "fr": "Singe", "de": "Affe", "ar": "قرد", "zh": "猴子", "ru": "Обезьяна", "pt": "Macaco", "ja": "猿", "ko": "원숭이", "it": "Scimmia", "tr": "Maymun", "nl": "Aap", "pl": "Małpa", "id": "Monyet", "th": "ลิง", "vi": "Khỉ", "fa": "میمون", "ne": "बाँदर", "si": "වඳුරා"},
    {"num": 9, "en": "Bear", "hi": "भालू", "bn": "ভালুক", "te": "ఎలుగుబంటి", "mr": "अस्वल", "ta": "கரடி", "gu": "રીંછ", "ur": "ریچھ", "kn": "ಕರಡಿ", "ml": "കരടി", "pa": "ਭਾਲੂ", "or": "ଭାଲୁ", "as": "ভালুক", "es": "Oso", "fr": "Ours", "de": "Bär", "ar": "دب", "zh": "熊", "ru": "Медведь", "pt": "Urso", "ja": "クマ", "ko": "곰", "it": "Orso", "tr": "Ayı", "nl": "Beer", "pl": "Niedźwiedź", "id": "Beruang", "th": "หมี", "vi": "Gấu", "fa": "خرس", "ne": "भालु", "si": "වලසා"},
    {"num": 10, "en": "Rabbit", "hi": "खरगोश", "bn": "খরগোশ", "te": "కుందేలు", "mr": "ससा", "ta": "முயல்", "gu": "સસલું", "ur": "خرگوش", "kn": "ಮೊಲ", "ml": "മുയൽ", "pa": "ਖ਼ਰਗੋਸ਼", "or": "ଠେକୁଆ", "as": "শহা পহু", "es": "Conejo", "fr": "Lapin", "de": "Kaninchen", "ar": "أرنب", "zh": "兔子", "ru": "Кролик", "pt": "Coelho", "ja": "ウサギ", "ko": "토끼", "it": "Coniglio", "tr": "Tavşan", "nl": "Konijn", "pl": "Królik", "id": "Kelinci", "th": "กระต่าย", "vi": "Thỏ", "fa": "خرگوش", "ne": "खरायो", "si": "හාවා"},
    
    # 11-50 PREMIUM
    {"num": 11, "en": "Deer", "hi": "हिरण", "bn": "হরিণ", "te": "జింక", "mr": "हरिण", "ta": "மான்", "gu": "હરણ", "ur": "ہرن", "kn": "ಜಿಂಕೆ", "ml": "മാൻ", "pa": "ਹਿਰਨ", "or": "ହରିଣ", "as": "হৰিণা", "es": "Ciervo", "fr": "Cerf", "de": "Hirsch", "ar": "غزال", "zh": "鹿", "ru": "Олень", "pt": "Cervo", "ja": "鹿", "ko": "사슴", "it": "Cervo", "tr": "Geyik", "nl": "Hert", "pl": "Jeleń", "id": "Rusa", "th": "กวาง", "vi": "Hươu", "fa": "گوزن", "ne": "मृग", "si": "මුවා"},
    {"num": 12, "en": "Zebra", "hi": "ज़ेबरा", "bn": "জেব্রা", "te": "జీబ్రా", "mr": "झेब्रा", "ta": "வரிக்குதிரை", "gu": "ઝીબ્રા", "ur": "زیبرا", "kn": "ಜೀಬ್ರಾ", "ml": "സീബ്ര", "pa": "ਜ਼ੈਬਰਾ", "or": "ଜେବ୍ରା", "as": "জেব্ৰা", "es": "Cebra", "fr": "Zèbre", "de": "Zebra", "ar": "حمار وحشي", "zh": "斑马", "ru": "Зебра", "pt": "Zebra", "ja": "シマウマ", "ko": "얼룩말", "it": "Zebra", "tr": "Zebra", "nl": "Zebra", "pl": "Zebra", "id": "Zebra", "th": "ม้าลาย", "vi": "Ngựa vằn", "fa": "گورخر", "ne": "जेब्रा", "si": "සීබ්රා"},
    {"num": 13, "en": "Giraffe", "hi": "जिराफ़", "bn": "জিরাফ", "te": "జిరాఫీ", "mr": "जिराफ", "ta": "ஒட்டகச்சிவிங்கி", "gu": "જિરાફ", "ur": "زرافہ", "kn": "ಜಿರಾಫೆ", "ml": "ജിറാഫ്", "pa": "ਜਿਰਾਫ਼", "or": "ଜିରାଫ", "as": "জিৰাফ", "es": "Jirafa", "fr": "Girafe", "de": "Giraffe", "ar": "زرافة", "zh": "长颈鹿", "ru": "Жираф", "pt": "Girafa", "ja": "キリン", "ko": "기린", "it": "Giraffa", "tr": "Zürafa", "nl": "Giraffe", "pl": "Żyrafa", "id": "Jerapah", "th": "ยีราฟ", "vi": "Hươu cao cổ", "fa": "زرافه", "ne": "जिराफ", "si": "ජිරාෆ්"},
    {"num": 14, "en": "Kangaroo", "hi": "कंगारू", "bn": "ক্যাঙ্গারু", "te": "కంగారూ", "mr": "कांगारू", "ta": "கங்காரு", "gu": "કાંગારૂ", "ur": "کنگارو", "kn": "ಕಾಂಗರೂ", "ml": "കംഗാരു", "pa": "ਕੰਗਾਰੂ", "or": "କଙ୍ଗାରୁ", "as": "কেঙ্গাৰু", "es": "Canguro", "fr": "Kangourou", "de": "Känguru", "ar": "كنغر", "zh": "袋鼠", "ru": "Кенгуру", "pt": "Canguru", "ja": "カンガルー", "ko": "캥거루", "it": "Canguro", "tr": "Kanguru", "nl": "Kangoeroe", "pl": "Kangur", "id": "Kanguru", "th": "จิงโจ้", "vi": "Chuột túi", "fa": "کانگورو", "ne": "कङ्गारू", "si": "කැන්ගරු"},
    {"num": 15, "en": "Panda", "hi": "पांडा", "bn": "পান্ডা", "te": "పాండా", "mr": "पांडा", "ta": "பாண்டா", "gu": "પાન્ડા", "ur": "پانڈا", "kn": "ಪಾಂಡಾ", "ml": "പാണ്ട", "pa": "ਪਾਂਡਾ", "or": "ପାଣ୍ଡା", "as": "পাণ্ডা", "es": "Panda", "fr": "Panda", "de": "Panda", "ar": "باندا", "zh": "熊猫", "ru": "Панда", "pt": "Panda", "ja": "パンダ", "ko": "판다", "it": "Panda", "tr": "Panda", "nl": "Panda", "pl": "Panda", "id": "Panda", "th": "แพนด้า", "vi": "Gấu trúc", "fa": "پاندا", "ne": "पाण्डा", "si": "පැන්ඩා"},
    {"num": 16, "en": "Camel", "hi": "ऊंट", "bn": "উট", "te": "ఒంటె", "mr": "उंट", "ta": "ஒட்டகம்", "gu": "ઊંટ", "ur": "اونٹ", "kn": "ಒಂಟೆ", "ml": "ഒട്ടകം", "pa": "ਊਠ", "or": "ଓଟ", "as": "উট", "es": "Camello", "fr": "Chameau", "de": "Kamel", "ar": "جمل", "zh": "骆驼", "ru": "Верблюд", "pt": "Camelo", "ja": "ラクダ", "ko": "낙타", "it": "Cammello", "tr": "Deve", "nl": "Kameel", "pl": "Wielbłąd", "id": "Unta", "th": "อูฐ", "vi": "Lạc đà", "fa": "شتر", "ne": "ऊँट", "si": "ඔටුවා"},
    {"num": 17, "en": "Fox", "hi": "लोमड़ी", "bn": "শেয়াল", "te": "నక్క", "mr": "कोल्हा", "ta": "நரி", "gu": "શિયાળ", "ur": "لومڑی", "kn": "ನರಿ", "ml": "കുറുക്കൻ", "pa": "ਲੂੰਬੜੀ", "or": "କୋକିଶିଆଳୀ", "as": "শিয়াল", "es": "Zorro", "fr": "Renard", "de": "Fuchs", "ar": "ثعلب", "zh": "狐狸", "ru": "Лиса", "pt": "Raposa", "ja": "キツネ", "ko": "여우", "it": "Volpe", "tr": "Tilki", "nl": "Vos", "pl": "Lis", "id": "Rubah", "th": "สุนัขจิ้งจอก", "vi": "Cáo", "fa": "روباه", "ne": "स्याल", "si": "හිවලා"},
    {"num": 18, "en": "Wolf", "hi": "भेड़िया", "bn": "নেকড়ে", "te": "తోడేలు", "mr": "लांडगा", "ta": "ஓநாய்", "gu": "વરુ", "ur": "بھیڑیا", "kn": "ತೋಳ", "ml": "ചെന്നായ്", "pa": "ਬਘਿਆੜ", "or": "ଗଧିଆ", "as": "নেকড়ে বাঘ", "es": "Lobo", "fr": "Loup", "de": "Wolf", "ar": "ذئب", "zh": "狼", "ru": "Волк", "pt": "Lobo", "ja": "オオカミ", "ko": "늑대", "it": "Lupo", "tr": "Kurt", "nl": "Wolf", "pl": "Wilk", "id": "Serigala", "th": "หมาป่า", "vi": "Sói", "fa": "گرگ", "ne": "ब्वाँसो", "si": "වෘකයා"},
    {"num": 19, "en": "Goat", "hi": "बकरी", "bn": "ছাগল", "te": "మేక", "mr": "शेळी", "ta": "ஆடு", "gu": "બકરી", "ur": "بکری", "kn": "ಆಡು", "ml": "ആട്", "pa": "ਬੱਕਰੀ", "or": "ଛେଳି", "as": "ছাগলী", "es": "Cabra", "fr": "Chèvre", "de": "Ziege", "ar": "ماعز", "zh": "山羊", "ru": "Коза", "pt": "Cabra", "ja": "ヤギ", "ko": "염소", "it": "Capra", "tr": "Keçi", "nl": "Geit", "pl": "Koza", "id": "Kambing", "th": "แพะ", "vi": "Dê", "fa": "بز", "ne": "बाख्रा", "si": "එළුවා"},
    {"num": 20, "en": "Sheep", "hi": "भेड़", "bn": "ভেড়া", "te": "గొర్రె", "mr": "मेंढी", "ta": "செம்மறியாடு", "gu": "ઘેટું", "ur": "بھیڑ", "kn": "ಕುರಿ", "ml": "ചെമ്മരിയാട്", "pa": "ਭੇਡ", "or": "ମେଣ୍ଢା", "as": "ভেড়া", "es": "Oveja", "fr": "Mouton", "de": "Schaf", "ar": "خروف", "zh": "绵羊", "ru": "Овца", "pt": "Ovelha", "ja": "羊", "ko": "양", "it": "Pecora", "tr": "Koyun", "nl": "Schaap", "pl": "Owca", "id": "Domba", "th": "แกะ", "vi": "Cừu", "fa": "گوسفند", "ne": "भेंडा", "si": "බැටළුවා"},
    {"num": 21, "en": "Pig", "hi": "सूअर", "bn": "শূকর", "te": "పంది", "mr": "डुक्कर", "ta": "பன்றி", "gu": "ભૂંડ", "ur": "سور", "kn": "ಹಂದಿ", "ml": "പന്നി", "pa": "ਸੂਰ", "or": "ଘୁଷୁରି", "as": "গাহৰি", "es": "Cerdo", "fr": "Cochon", "de": "Schwein", "ar": "خنزير", "zh": "猪", "ru": "Свинья", "pt": "Porco", "ja": "豚", "ko": "돼지", "it": "Maiale", "tr": "Domuz", "nl": "Varken", "pl": "Świnia", "id": "Babi", "th": "หมู", "vi": "Heo", "fa": "خوک", "ne": "सुँगुर", "si": "ඌරා"},
    {"num": 22, "en": "Donkey", "hi": "गधा", "bn": "গাধা", "te": "గాడిద", "mr": "गाढव", "ta": "கழுதை", "gu": "ગધેડો", "ur": "گدھا", "kn": "ಕತ್ತೆ", "ml": "കഴുത", "pa": "ਖੋਤਾ", "or": "ଗଧ", "as": "গাধ", "es": "Burro", "fr": "Âne", "de": "Esel", "ar": "حمار", "zh": "驴", "ru": "Осёл", "pt": "Burro", "ja": "ロバ", "ko": "당나귀", "it": "Asino", "tr": "Eşek", "nl": "Ezel", "pl": "Osioł", "id": "Keledai", "th": "ลา", "vi": "Lừa", "fa": "الاغ", "ne": "गधा", "si": "බූරුවා"},
    {"num": 23, "en": "Squirrel", "hi": "गिलहरी", "bn": "কাঠবিড়ালি", "te": "ఉడుత", "mr": "खार", "ta": "அணில்", "gu": "ખિસકોલી", "ur": "گلہری", "kn": "ಅಳಿಲು", "ml": "അണ്ണാൻ", "pa": "ਗਲਹਿਰੀ", "or": "ଗୁଣ୍ଡୁଚି ମୂଷା", "as": "কেৰ্কেটুৱা", "es": "Ardilla", "fr": "Écureuil", "de": "Eichhörnchen", "ar": "سنجاب", "zh": "松鼠", "ru": "Белка", "pt": "Esquilo", "ja": "リス", "ko": "다람쥐", "it": "Scoiattolo", "tr": "Sincap", "nl": "Eekhoorn", "pl": "Wiewiórka", "id": "Tupai", "th": "กระรอก", "vi": "Sóc", "fa": "سنجاب", "ne": "लोखर्के", "si": "ලේනා"},
    {"num": 24, "en": "Hippopotamus", "hi": "दरियाई घोड़ा", "bn": "জলহস্তী", "te": "నీటి గుర్రం", "mr": "पानघोडा", "ta": "நீர்யானை", "gu": "જળઘોડો", "ur": "دریائی گھوڑا", "kn": "ನೀರಾನೆ", "ml": "നീർക്കുതിര", "pa": "ਦਰਿਆਈ ਘੋੜਾ", "or": "ଜଳହସ୍ତୀ", "as": "জলহস্তী", "es": "Hipopótamo", "fr": "Hippopotame", "de": "Nilpferd", "ar": "فرس النهر", "zh": "河马", "ru": "Бегемот", "pt": "Hipopótamo", "ja": "カバ", "ko": "하마", "it": "Ippopotamo", "tr": "Hipopotam", "nl": "Nijlpaard", "pl": "Hipopotam", "id": "Kuda Nil", "th": "ฮิปโป", "vi": "Hà mã", "fa": "اسب آبی", "ne": "जलहात्ती", "si": "දිය අලියා"},
    {"num": 25, "en": "Rhinoceros", "hi": "गेंदा", "bn": "গন্ডার", "te": "ఖడ్గమృగం", "mr": "गेंडा", "ta": "காண்டாமிருகம்", "gu": "ગેંડો", "ur": "گینڈا", "kn": "ಖಡ್ಗಮೃಗ", "ml": "കാണ്ടാമൃഗം", "pa": "ਗੈਂਡਾ", "or": "ଗଣ୍ଡା", "as": "গঁড়", "es": "Rinoceronte", "fr": "Rhinocéros", "de": "Nashorn", "ar": "وحيد القرن", "zh": "犀牛", "ru": "Носорог", "pt": "Rinoceronte", "ja": "サイ", "ko": "코뿔소", "it": "Rinoceronte", "tr": "Gergedan", "nl": "Neushoorn", "pl": "Nosorożec", "id": "Badak", "th": "แรด", "vi": "Tê giác", "fa": "کرگدن", "ne": "गैंडा", "si": "ඛඩ්ගමෘගයා"},
    {"num": 26, "en": "Gorilla", "hi": "गोरिल्ला", "bn": "গরিলা", "te": "గొరిల్లా", "mr": "गोरिला", "ta": "கொரில்லா", "gu": "ગોરિલા", "ur": "گوریلا", "kn": "ಗೊರಿಲ್ಲಾ", "ml": "ഗൊറില്ല", "pa": "ਗੋਰਿਲਾ", "or": "ଗୋରିଲା", "as": "গৰিলা", "es": "Gorila", "fr": "Gorille", "de": "Gorilla", "ar": "غوريلا", "zh": "大猩猩", "ru": "Горилла", "pt": "Gorila", "ja": "ゴリラ", "ko": "고릴라", "it": "Gorilla", "tr": "Goril", "nl": "Gorilla", "pl": "Goryl", "id": "Gorila", "th": "กอริลลา", "vi": "Khỉ đột", "fa": "گوریل", "ne": "गोरिल्ला", "si": "ගෝරිල්ලා"},
    {"num": 27, "en": "Leopard", "hi": "तेंदुआ", "bn": "চিতাবাঘ", "te": "చిరుతపులి", "mr": "बिबट्या", "ta": "சிறுத்தை", "gu": "દીપડો", "ur": "تیندوا", "kn": "ಚಿರತೆ", "ml": "പുള്ളിപ്പുലി", "pa": "ਤੇਂਦੂਆ", "or": "କଲରାପତରିଆ ବାଘ", "as": "ঢেঁকীয়াপতীয়া বাঘ", "es": "Leopardo", "fr": "Léopard", "de": "Leopard", "ar": "فهد", "zh": "金钱豹", "ru": "Леопард", "pt": "Leopardo", "ja": "ヒョウ", "ko": "표범", "it": "Leopardo", "tr": "Pars", "nl": "Luipaard", "pl": "Lampart", "id": "Macan Tutul", "th": "เสือดาว", "vi": "Báo hoa mai", "fa": "پلنگ", "ne": "चितुवा", "si": "දිවියා"},
    {"num": 28, "en": "Cheetah", "hi": "चीता", "bn": "চিতা", "te": "చీతా", "mr": "चित્તા", "ta": "சீட்டா", "gu": "ચીતો", "ur": "چیتا", "kn": "ಚೀತಾ", "ml": "ചീറ്റ", "pa": "ਚੀਤਾ", "or": "ଚିତା", "as": "চিতা", "es": "Guepardo", "fr": "Guépard", "de": "Gepard", "ar": "فهد صياد", "zh": "猎豹", "ru": "Гепард", "pt": "Guepardo", "ja": "チーター", "ko": "치타", "it": "Ghepardo", "tr": "Çita", "nl": "Jachtluipaard", "pl": "Gepard", "id": "Cetah", "th": "เสือชีตาห์", "vi": "Báo săn", "fa": "یوزپلنگ", "ne": "चितुवा", "si": "චීටා"},
    {"num": 29, "en": "Buffalo", "hi": "भैंस", "bn": "মহিষ", "te": "గేదె", "mr": "म्हैस", "ta": "எருமை", "gu": "ભેંસ", "ur": "بھینس", "kn": "ಕೋಣ", "ml": "പോത്ത്", "pa": "ਮੱਝ", "or": "ମହିଷ", "as": "মহ", "es": "Búfalo", "fr": "Buffle", "de": "Büffel", "ar": "جاموس", "zh": "水牛", "ru": "Буйвол", "pt": "Búfalo", "ja": "水牛", "ko": "물소", "it": "Bufalo", "tr": "Manda", "nl": "Buffel", "pl": "Bawół", "id": "Kerbau", "th": "ควาย", "vi": "Trâu", "fa": "گاومیش", "ne": "भैंसी", "si": "මීහරකා"},
    {"num": 30, "en": "Mouse", "hi": "चूहा", "bn": "ইঁদুর", "te": "ఎలుక", "mr": "उंदीर", "ta": "எலி", "gu": "ઉંદર", "ur": "چوہا", "kn": "ಇಲಿ", "ml": "എലി", "pa": "ਚੂਹਾ", "or": "ମୂଷା", "as": "নিগনি", "es": "Ratón", "fr": "Souris", "de": "Maus", "ar": "فأر", "zh": "老鼠", "ru": "Мышь", "pt": "Rato", "ja": "ネズミ", "ko": "쥐", "it": "Topo", "tr": "Fare", "nl": "Muis", "pl": "Mysz", "id": "Tikus", "th": "หนู", "vi": "Chuột", "fa": "موش", "ne": "मुसो", "si": "මීයා"},
    {"num": 31, "en": "Bat", "hi": "चमगादड़", "bn": "বাদুড়", "te": "గబ్బిలం", "mr": "वटवाघूळ", "ta": "வௌவால்", "gu": "ચામાચીડિયું", "ur": "چمگادڑ", "kn": "ಬಾವಲಿ", "ml": "വവ്വാൽ", "pa": "ਚਮਗਿੱਦੜ", "or": "ବାଦୁଡ଼ି", "as": "বাদুলি", "es": "Murciélago", "fr": "Chauve-souris", "de": "Fledermaus", "ar": "خفاش", "zh": "蝙蝠", "ru": "Летучая мышь", "pt": "Morcego", "ja": "コウモリ", "ko": "박쥐", "it": "Pipistrello", "tr": "Yarasa", "nl": "Vleermuis", "pl": "Nietoperz", "id": "Kelelawar", "th": "ค้างคาว", "vi": "Dơi", "fa": "خفاش", "ne": "चमेरो", "si": "වවුලා"},
    {"num": 32, "en": "Dolphin", "hi": "डॉल्फ़िन", "bn": "ডলফিন", "te": "డాల్ఫిన్", "mr": "डॉल्फिन", "ta": "டால்பின்", "gu": "ડોલ્ફિન", "ur": "ڈولفن", "kn": "ಡಾಲ್ಫಿನ್", "ml": "ഡോൾഫിൻ", "pa": "ਡਾਲਫਿਨ", "or": "ଡଲଫିନ", "as": "ডলফিন", "es": "Delfín", "fr": "Dauphin", "de": "Delfin", "ar": "دلفين", "zh": "海豚", "ru": "Дельфин", "pt": "Golfinho", "ja": "イルカ", "ko": "돌고래", "it": "Delfino", "tr": "Yunus", "nl": "Dolfijn", "pl": "Delfin", "id": "Lumba-lumba", "th": "โลมา", "vi": "Cá heo", "fa": "دلفین", "ne": "डल्फिन", "si": "ඩොල්ෆින්"},
    {"num": 33, "en": "Whale", "hi": "व्हेल", "bn": "তিমি", "te": "తిమింగలం", "mr": "देवमासा", "ta": "திமிங்கலம்", "gu": "વ્હેલ", "ur": "وہیل", "kn": "ತಿಮಿಂಗಿಲ", "ml": "തിമിംഗലം", "pa": "ਵ੍ਹੇਲ", "or": "ତିମି", "as": "তিমি মাছ", "es": "Ballena", "fr": "Baleine", "de": "Wal", "ar": "حوت", "zh": "鲸鱼", "ru": "Кит", "pt": "Baleia", "ja": "クジラ", "ko": "고래", "it": "Balena", "tr": "Balina", "nl": "Walvis", "pl": "Wieloryb", "id": "Paus", "th": "วาฬ", "vi": "Cá voi", "fa": "نهنگ", "ne": "ह्वेल", "si": "තල්මසා"},
    {"num": 34, "en": "Turtle", "hi": "कछुआ", "bn": "কচ্ছপ", "te": "తాబేలు", "mr": "कासव", "ta": "ஆமை", "gu": "કાચબો", "ur": "کچھوا", "kn": "ಆಮೆ", "ml": "ആമ", "pa": "ਕੱਛੂਕੁੰਮਾ", "or": "କଇଁଛ", "as": "কাছ", "es": "Tortuga", "fr": "Tortue", "de": "Schildkröte", "ar": "سلحفاة", "zh": "乌龟", "ru": "Черепаха", "pt": "Tartaruga", "ja": "カメ", "ko": "거북이", "it": "Tartaruga", "tr": "Kaplumbağa", "nl": "Schildpad", "pl": "Żółw", "id": "Kura-kura", "th": "เต่า", "vi": "Rùa", "fa": "لاک‌پشت", "ne": "कछुवा", "si": "ඉබ්බා"},
    {"num": 35, "en": "Crocodile", "hi": "मगरमच्छ", "bn": "কুমির", "te": "మొసలి", "mr": "मगर", "ta": "முதலை", "gu": "મગર", "ur": "مگرمچھ", "kn": "ಮೊಸಳೆ", "ml": "മുതല", "pa": "ਮਗਰਮੱਛ", "or": "କୁମ୍ଭୀର", "as": "ঘঁৰিয়াল", "es": "Cocodrilo", "fr": "Crocodile", "de": "Krokodil", "ar": "تمساح", "zh": "鳄鱼", "ru": "Крокодил", "pt": "Crocodilo", "ja": "ワニ", "ko": "악어", "it": "Coccodrillo", "tr": "Timsah", "nl": "Krokodil", "pl": "Krokodyl", "id": "Buaya", "th": "จระเข้", "vi": "Cá sấu", "fa": "تمساح", "ne": "गोही", "si": "කිඹුලා"},
    {"num": 36, "en": "Snake", "hi": "सांप", "bn": "সাপ", "te": "పాము", "mr": "साप", "ta": "பாம்பு", "gu": "સાપ", "ur": "سانپ", "kn": "ಹಾವು", "ml": "പാമ്പ്", "pa": "ਸੱਪ", "or": "ସାପ", "as": "সাপ", "es": "Serpiente", "fr": "Serpent", "de": "Schlange", "ar": "ثعبان", "zh": "蛇", "ru": "Змея", "pt": "Cobra", "ja": "ヘビ", "ko": "뱀", "it": "Serpente", "tr": "Yılan", "nl": "Slang", "pl": "Wąż", "id": "Ular", "th": "งู", "vi": "Rắn", "fa": "مار", "ne": "सर्प", "si": "නයා"},
    {"num": 37, "en": "Frog", "hi": "मेंढक", "bn": "ব্যাঙ", "te": "కప్ప", "mr": "बेडूक", "ta": "தவளை", "gu": "દેડકો", "ur": "مینڈک", "kn": "ಕಪ್ಪೆ", "ml": "തവള", "pa": "ਡੱਡੂ", "or": "ବେଙ୍ଗ", "as": "ভেকুলী", "es": "Rana", "fr": "Grenouille", "de": "Frosch", "ar": "ضفدع", "zh": "青蛙", "ru": "Лягушка", "pt": "Rã", "ja": "カエル", "ko": "개구리", "it": "Rana", "tr": "Kurbağa", "nl": "Kikker", "pl": "Żaba", "id": "Katak", "th": "กบ", "vi": "Ếch", "fa": "قورباغه", "ne": "भ्यागुतो", "si": "මැඩියා"},
    {"num": 38, "en": "Lizard", "hi": "छिपकली", "bn": "টিকটিকি", "te": "బల్లి", "mr": "पाल", "ta": "பல்லி", "gu": "ગરોળી", "ur": "چھپکلی", "kn": "ಹಲ್ಲಿ", "ml": "പല്ലി", "pa": "ਕਿਰਲੀ", "or": "ଝିଟିପିଟି", "as": "জেঠী", "es": "Lagarto", "fr": "Lézard", "de": "Eidechse", "ar": "سحلية", "zh": "蜥蜴", "ru": "Ящерица", "pt": "Lagarto", "ja": "トカゲ", "ko": "도마뱀", "it": "Lucertola", "tr": "Kertenkele", "nl": "Hagedis", "pl": "Jaszczurka", "id": "Kadal", "th": "จิ้งจก", "vi": "Thằn lằn", "fa": "مارمولک", "ne": "माउसुली", "si": "හූනා"},
    {"num": 39, "en": "Chimpanzee", "hi": "चिंपांज़ी", "bn": "শিম্পাঞ্জি", "te": "చింపాంజీ", "mr": "चिंपांझी", "ta": "சிம்பன்சி", "gu": "ચિમ્પાન્ઝી", "ur": "چمپینزی", "kn": "ಚಿಂಪಾಂಜಿ", "ml": "ചിമ്പാൻസി", "pa": "ਚਿੰਪਾਂਜ਼ੀ", "or": "ଚିମ୍ପାଞ୍ଜି", "as": "চিম্পাঞ্জী", "es": "Chimpancé", "fr": "Chimpanzé", "de": "Schimpanse", "ar": "شمبانزي", "zh": "黑猩猩", "ru": "Шимпанзе", "pt": "Chimpanzé", "ja": "チンパンジー", "ko": "침팬지", "it": "Scimpanzé", "tr": "Şempanze", "nl": "Chimpansee", "pl": "Szympans", "id": "Simpanse", "th": "ชิมแปนซี", "vi": "Tinh tinh", "fa": "شامپانزه", "ne": "चिम्पान्जी", "si": "චිම්පන්සියා"},
    {"num": 40, "en": "Ox", "hi": "बैल", "bn": "ষাঁড়", "te": "ఎద్దు", "mr": "बैल", "ta": "எருது", "gu": "બળદ", "ur": "بیل", "kn": "ಎತ್ತು", "ml": "കാള", "pa": "ਬਲਦ", "or": "ବଳଦ", "as": "বলধ", "es": "Buey", "fr": "Bœuf", "de": "Ochse", "ar": "ثور", "zh": "公牛", "ru": "Бык", "pt": "Boi", "ja": "雄牛", "ko": "황소", "it": "Bue", "tr": "Öküz", "nl": "Os", "pl": "Wół", "id": "Lembu", "th": "วัวตัวผู้", "vi": "Bò đực", "fa": "گاو نر", "ne": "गोरु", "si": "ගොනා"},
    {"num": 41, "en": "Koala", "hi": "कोआला", "bn": "কোয়ালা", "te": "కోలా", "mr": "कोआला", "ta": "கோவாலா", "gu": "કોઆલા", "ur": "کوالا", "kn": "ಕೋಲಾ", "ml": "കൊവാല", "pa": "ਕੋਆਲਾ", "or": "କୋଆଲା", "as": "কোৱালা", "es": "Koala", "fr": "Koala", "de": "Koala", "ar": "كوالا", "zh": "考拉", "ru": "Коала", "pt": "Coala", "ja": "コアラ", "ko": "코알라", "it": "Koala", "tr": "Koala", "nl": "Koala", "pl": "Koala", "id": "Koala", "th": "โคอาลา", "vi": "Gấu túi", "fa": "کوالا", "ne": "कोआला", "si": "කොආලා"},
    {"num": 42, "en": "Otter", "hi": "ऊदबिलाव", "bn": "ভোঁদড়", "te": "నీటిపిల్లి", "mr": "उदमांजर", "ta": "நீர்நாய்", "gu": "જળબિલાડી", "ur": "اودبلاؤ", "kn": "ನೀರನಾಯಿ", "ml": "നീർനായ്", "pa": "ਊਦਬਿਲਾਵ", "or": "ପାଣିଓଧ", "as": "উদ", "es": "Nutria", "fr": "Loutre", "de": "Otter", "ar": "قضاعة", "zh": "水獭", "ru": "Выдра", "pt": "Lontra", "ja": "カワウソ", "ko": "수달", "it": "Lontra", "tr": "Samur", "nl": "Otter", "pl": "Wydra", "id": "Berang-berang", "th": "นาก", "vi": "Rái cá", "fa": "سمور آبی", "ne": "पानी बिरालो", "si": "දිය බල්ලා"},
    {"num": 43, "en": "Hedgehog", "hi": "साही", "bn": "সজারু", "te": "ముళ్ళపంది", "mr": "साळींदर", "ta": "முள்ளம்பன்றி", "gu": "સાહુડી", "ur": "خارپشت", "kn": "ಮುಳ್ಳುಹಂದಿ", "ml": "മുള്ളൻപന്നി", "pa": "ਕੰਡਿਆਲੀ ਚੂਹੀ", "or": "ଝିଙ୍କ", "as": "কেঁতুৰী পহু", "es": "Erizo", "fr": "Hérisson", "de": "Igel", "ar": "قنفذ", "zh": "刺猬", "ru": "Ёж", "pt": "Ouriço", "ja": "ハリネズミ", "ko": "고슴도치", "it": "Riccio", "tr": "Kirpi", "nl": "Egel", "pl": "Jeż", "id": "Landak", "th": "เม่น", "vi": "Nhím", "fa": "جوجه‌تیغی", "ne": "दुम्सी", "si": "ඉත්තෑවා"},
    {"num": 44, "en": "Yak", "hi": "याक", "bn": "ইয়াক", "te": "యాక్", "mr": "याक", "ta": "யாக்", "gu": "યાક", "ur": "یاک", "kn": "ಯಾಕ್", "ml": "യാക്ക്", "pa": "ਯਾਕ", "or": "ୟାକ୍", "as": "য়াক", "es": "Yak", "fr": "Yack", "de": "Yak", "ar": "ياك", "zh": "牦牛", "ru": "Як", "pt": "Iaque", "ja": "ヤク", "ko": "야크", "it": "Yak", "tr": "Yak", "nl": "Jak", "pl": "Jak", "id": "Yak", "th": "จามรี", "vi": "Bò Tây Tạng", "fa": "گاومیش تبتی", "ne": "चौँरी", "si": "යක් ගවයා"},
    {"num": 45, "en": "Skunk", "hi": "स्कंक", "bn": "স্কার্ঙ্ক", "te": "స్కంక్", "mr": "स्कंक", "ta": "ஸ்கங்க்", "gu": "સ્કંક", "ur": "سکَنک", "kn": "ಸ್ಕಂಕ್", "ml": "സ്കങ്ക്", "pa": "ਸਕੰਕ", "or": "ସ୍କଙ୍କ", "as": "স্কংক", "es": "Mofeta", "fr": "Moufette", "de": "Stinktier", "ar": "ظربان", "zh": "臭鼬", "ru": "Скунс", "pt": "Gambá", "ja": "スカンク", "ko": "스컹크", "it": "Moffetta", "tr": "Kokarca", "nl": "Stinkdier", "pl": "Skunks", "id": "Sigung", "th": "สกั๊งค์", "vi": "Chồn hôi", "fa": "راسوی بدبو", "ne": "स्कन्क", "si": "ස්කන්ක්"},
    {"num": 46, "en": "Sloth", "hi": "स्लॉथ", "bn": "স্লথ", "te": "స్లాత్", "mr": "स्लॉथ", "ta": "ஸ்லாத்", "gu": "સ્લોથ", "ur": "سلوتھ", "kn": "ಸ್ಲಾತ್", "ml": "സ്ലോത്ത്", "pa": "ਸਲੌਥ", "or": "ସ୍ଲଥ", "as": "শ্লথ", "es": "Perezoso", "fr": "Paresseux", "de": "Faultier", "ar": "كسلان", "zh": "树懒", "ru": "Ленивец", "pt": "Bicho-preguiça", "ja": "ナマケモノ", "ko": "나무늘보", "it": "Bradipo", "tr": "Tembel hayvan", "nl": "Luiaard", "pl": "Leniwiec", "id": "Kuskus", "th": "สล็อต", "vi": "Lười", "fa": "تنبل", "ne": "स्लोथ", "si": "ස්ලොත්"},
    {"num": 47, "en": "Beaver", "hi": "बीवर", "bn": "বিভার", "te": "బీవర్", "mr": "बीव्हर", "ta": "பீவர்", "gu": "બીવર", "ur": "بیور", "kn": "ಬೀವರ್", "ml": "ബീവർ", "pa": "ਬੀਵਰ", "or": "ବିଭର", "as": "বিভাৰ", "es": "Castor", "fr": "Castor", "de": "Biber", "ar": "قندس", "zh": "海狸", "ru": "Бобр", "pt": "Castor", "ja": "ビーバー", "ko": "비버", "it": "Castoro", "tr": "Kunduz", "nl": "Bever", "pl": "Bóbr", "id": "Berang-berang", "th": "บีเวอร์", "vi": "Hải ly", "fa": "سگ آبی", "ne": "बिभर", "si": "බීවර්"},
    {"num": 48, "en": "Badger", "hi": "बिज्जू", "bn": "ব্যাজার", "te": "బాడ్జర్", "mr": "बिज्जू", "ta": "பேட்ஜர்", "gu": "બિજ્જુ", "ur": "بجو", "kn": "ಬ್ಯಾಡ್ಜರ್", "ml": "ബാഡ്ജർ", "pa": "ਬਿੱਜੂ", "or": "ବ୍ୟାଜର", "as": "বেজাৰ", "es": "Tejón", "fr": "Blaireau", "de": "Dachs", "ar": "غرير", "zh": "獾", "ru": "Барсук", "pt": "Texugo", "ja": "アナグマ", "ko": "오소리", "it": "Tasso", "tr": "Porsuk", "nl": "Das", "pl": "Borsuk", "id": "Luwak", "th": "แบดเจอร์", "vi": "Lửng", "fa": "گورکن", "ne": "बिज्जु", "si": "බැජර්"},
    {"num": 49, "en": "Raccoon", "hi": "रैकून", "bn": "র্যাকুন", "te": "రాకూన్", "mr": "रॅकून", "ta": "ரக்கூன்", "gu": "રેકૂન", "ur": "ریکون", "kn": "ರಾಕೂನ್", "ml": "റാക്കൂൺ", "pa": "ਰੈਕੂਨ", "or": "ରାକୁନ", "as": "ৰেকুন", "es": "Mapache", "fr": "Raton laveur", "de": "Waschbär", "ar": "راكون", "zh": "浣熊", "ru": "Енот", "pt": "Guaxinim", "ja": "アライグマ", "ko": "라쿤", "it": "Procione", "tr": "Rakun", "nl": "Wasbeer", "pl": "Szop pracz", "id": "Rakun", "th": "แรคคูน", "vi": "Gấu trúc Mỹ", "fa": "راکون", "ne": "र्‍याकुन", "si": "රැකූන්"},
    {"num": 50, "en": "Walrus", "hi": "वॉलरस", "bn": "ওয়ালরাস", "te": "వాల్‌రస్", "mr": "वॉलरस", "ta": "வால்ரஸ்", "gu": "વોલરસ", "ur": "والرس", "kn": "ವಾಲ್ರಸ್", "ml": "വാൽറസ്", "pa": "ਵਾਲਰਸ", "or": "ୱାଲରସ", "as": "ৱালৰাছ", "es": "Morsa", "fr": "Morse", "de": "Walross", "ar": "فظ", "zh": "海象", "ru": "Морж", "pt": "Morsa", "ja": "セイウチ", "ko": "바다코끼리", "it": "Tricheco", "tr": "Mors", "nl": "Walrus", "pl": "Mors", "id": "Beruang Laut", "th": "วอลรัส", "vi": "Hải tượng", "fa": "گراز دریایی", "ne": "वालरस", "si": "වෝල්රස්"}
]

print(f"Animals loaded: {len(ANIMALS)}")
