#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
50 Vegetables (sabjiyan) with all 33 language translations.
10 FREE (id 1-10), 40 PREMIUM (id 11-50).
"""

VEGETABLES = [
    # 1-10 FREE
    {"num": 1, "en": "Potato", "hi": "आलू", "bn": "আলু", "te": "బంగాళాదుంప", "mr": "बटाटा", "ta": "உருளைக்கிழங்கு", "gu": "બટાટા", "ur": "آلو", "kn": "ಆಲೂಗಡ್ಡೆ", "ml": "ഉരുളക്കിഴങ്ങ്", "pa": "ਆਲੂ", "or": "ଆଳୁ", "as": "আলু", "es": "Patata", "fr": "Pomme de terre", "de": "Kartoffel", "ar": "بطاطس", "zh": "土豆", "ru": "Картофель", "pt": "Batata", "ja": "ジャガイモ", "ko": "감자", "it": "Patata", "tr": "Patates", "nl": "Aardappel", "pl": "Ziemniak", "id": "Kentang", "th": "มันฝรั่ง", "vi": "Khoai tây", "fa": "سیب‌زمینی", "ne": "आलु", "si": "අර්තාපල්"},
    {"num": 2, "en": "Tomato", "hi": "टमाटर", "bn": "টমেটো", "te": "టమాటా", "mr": "टोमॅटो", "ta": "தக்காளி", "gu": "ટામેટાં", "ur": "ٹماٹر", "kn": "ಟೊಮೆಟೊ", "ml": "തക്കാളി", "pa": "ਟਮਾਟਰ", "or": "ବିଲାତି ବାଇଗଣ", "as": "বিলাহী", "es": "Tomate", "fr": "Tomate", "de": "Tomate", "ar": "طماطم", "zh": "番茄", "ru": "Помидор", "pt": "Tomate", "ja": "トマト", "ko": "토마토", "it": "Pomodoro", "tr": "Domates", "nl": "Tomaat", "pl": "Pomidor", "id": "Tomat", "th": "มะเขือเทศ", "vi": "Cà chua", "fa": "گوجه‌فرنگی", "ne": "गोलभेंडा", "si": "තක්කාලි"},
    {"num": 3, "en": "Onion", "hi": "प्याज़", "bn": "পেঁয়াজ", "te": "ఉల్లిపాయ", "mr": "कांदा", "ta": "வெங்காயம்", "gu": "ડુંગળી", "ur": "پیاز", "kn": "ಈರುಳ್ಳಿ", "ml": "സവാള", "pa": "ਪਿਆਜ਼", "or": "ପିଆଜ", "as": "পিয়াঁজ", "es": "Cebolla", "fr": "Oignon", "de": "Zwiebel", "ar": "بصل", "zh": "洋葱", "ru": "Лук", "pt": "Cebola", "ja": "タマネギ", "ko": "양파", "it": "Cipolla", "tr": "Soğan", "nl": "Ui", "pl": "Cebula", "id": "Bawang Bombay", "th": "หัวหอม", "vi": "Hành tây", "fa": "پیاز", "ne": "प्याज", "si": "ලූනු"},
    {"num": 4, "en": "Carrot", "hi": "गाजर", "bn": "গাজর", "te": "క్యారెట్", "mr": "गाजर", "ta": "கேரட்", "gu": "ગાજર", "ur": "گاجر", "kn": "ಕ್ಯಾರೆಟ್", "ml": "കാരറ്റ്", "pa": "ਗਾਜਰ", "or": "ଗାଜର", "as": "গাজৰ", "es": "Zanahoria", "fr": "Carotte", "de": "Karotte", "ar": "جزر", "zh": "胡萝卜", "ru": "Морковь", "pt": "Cenoura", "ja": "ニンジン", "ko": "당근", "it": "Carota", "tr": "Havuç", "nl": "Wortel", "pl": "Marchewka", "id": "Wortel", "th": "แครอท", "vi": "Cà rốt", "fa": "هویج", "ne": "गाजर", "si": "කැරට්"},
    {"num": 5, "en": "Radish", "hi": "मूली", "bn": "মুলা", "te": "ముల్లంగి", "mr": "मुळा", "ta": "முள்ளங்கி", "gu": "મૂળો", "ur": "مولی", "kn": "ಮೂಲಂಗಿ", "ml": "മുള്ളങ്കി", "pa": "ਮੂਲੀ", "or": "ମୂଳା", "as": "মূলা", "es": "Rábano", "fr": "Radis", "de": "Rettich", "ar": "فجل", "zh": "萝卜", "ru": "Редис", "pt": "Rabanete", "ja": "大根", "ko": "무", "it": "Ravanello", "tr": "Turp", "nl": "Radijs", "pl": "Rzodkiewka", "id": "Lobak", "th": "หัวไชเท้า", "vi": "Củ cải", "fa": "تربچه", "ne": "मुला", "si": "රාබු"},
    {"num": 6, "en": "Cabbage", "hi": "पत्ता गोभी", "bn": "বাঁধাকপি", "te": "క్యాబేజీ", "mr": "कोबी", "ta": "முட்டைக்கோஸ்", "gu": "કોબીજ", "ur": "بند گوبھی", "kn": "ಎಲೆಕೋಸು", "ml": "മുട്ടക്കോസ്", "pa": "ਬੰਦ ਗੋਭੀ", "or": "ବନ୍ଧାକୋବି", "as": "বন্ধাকবি", "es": "Repollo", "fr": "Chou", "de": "Kohl", "ar": "ملفوف", "zh": "卷心菜", "ru": "Капуста", "pt": "Repolho", "ja": "キャベツ", "ko": "양배추", "it": "Cavolo", "tr": "Lahana", "nl": "Kool", "pl": "Kapusta", "id": "Kubis", "th": "กะหล่ำปลี", "vi": "Bắp cải", "fa": "کلم‌پیچ", "ne": "बन्दागोभी", "si": "ගෝවා"},
    {"num": 7, "en": "Cauliflower", "hi": "फूलगोभी", "bn": "ফুলকপি", "te": "క్యాలీఫ్లవర్", "mr": "फ्लॉवर", "ta": "காலிஃபிளவர்", "gu": "ફુલાવર", "ur": "پھول گوبھی", "kn": "ಹೂಕೋಸು", "ml": "കോളിഫ്ലവർ", "pa": "ਫੁੱਲ ਗੋਭੀ", "or": "ଫୁଲକୋବି", "as": "ফুলকবি", "es": "Coliflor", "fr": "Chou-fleur", "de": "Blumenkohl", "ar": "قرنبيط", "zh": "花椰菜", "ru": "Цветная капуста", "pt": "Couve-flor", "ja": "カリフラワー", "ko": "콜리플라워", "it": "Cavolfiore", "tr": "Karnabahar", "nl": "Bloemkool", "pl": "Kalafior", "id": "Kembang Kol", "th": "กะหล่ำดอก", "vi": "Súp lơ trắng", "fa": "گل‌کلم", "ne": "काउली", "si": "මල් ගෝවා"},
    {"num": 8, "en": "Spinach", "hi": "पालक", "bn": "পালং শাক", "te": "పాలకూర", "mr": "पालक", "ta": "பசலைக்கீரை", "gu": "પાલખ", "ur": "پالک", "kn": "ಪಾಲಕ್", "ml": "ചീര", "pa": "ਪਾਲਕ", "or": "ପାଳଙ୍ଗ", "as": "পালং শাক", "es": "Espinaca", "fr": "Épinard", "de": "Spinat", "ar": "سبانخ", "zh": "菠菜", "ru": "Шпинат", "pt": "Espinafre", "ja": "ホウレンソウ", "ko": "시금치", "it": "Spinaci", "tr": "Ispanak", "nl": "Spinazie", "pl": "Szpinak", "id": "Bayam", "th": "ผักโขม", "vi": "Rau chân vịt", "fa": "اسفناج", "ne": "पालुङ्गो", "si": "නිවිති"},
    {"num": 9, "en": "Pea", "hi": "मटर", "bn": "মটরশুঁটি", "te": "బఠానీ", "mr": "मटार", "ta": "பட்டாணி", "gu": "વટાણા", "ur": "مٹر", "kn": "ಬಟಾಣಿ", "ml": "പട്ടாണി", "pa": "ਮਟਰ", "or": "ମଟର", "as": "মটৰ মাহ", "es": "Guisante", "fr": "Pois", "de": "Erbse", "ar": "بازلاء", "zh": "豌豆", "ru": "Горох", "pt": "Ervilha", "ja": "エンドウ豆", "ko": "완두콩", "it": "Piselli", "tr": "Bezelye", "nl": "Erwt", "pl": "Groszek", "id": "Kacang Polong", "th": "ถั่วลันเตา", "vi": "Đậu Hà Lan", "fa": "نخودفرنگی", "ne": "केराउ", "si": "බෝංචි"},
    {"num": 10, "en": "Brinjal", "hi": "बैंगन", "bn": "বেগুন", "te": "వంకాయ", "mr": "वांगे", "ta": "கத்தரிக்காய்", "gu": "રીંગણ", "ur": "بینگن", "kn": "ಬದನೆಕಾಯಿ", "ml": "വഴുതനങ്ങ", "pa": "ਬੈਂਗਣ", "or": "ବାଇଗଣ", "as": "বেঙেনা", "es": "Berenjena", "fr": "Aubergine", "de": "Aubergine", "ar": "باذنجان", "zh": "茄子", "ru": "Баклажан", "pt": "Beringela", "ja": "ナス", "ko": "가지", "it": "Melanzana", "tr": "Patlıcan", "nl": "Aubergine", "pl": "Bakłażan", "id": "Terong", "th": "มะเขือเปราะ", "vi": "Cà tím", "fa": "بادمجان", "ne": "भन्टा", "si": "වම්බටු"},

    # 11-50 PREMIUM
    {"num": 11, "en": "Lady Finger", "hi": "भिंडी", "bn": "ঢ্যাঁড়শ", "te": "బెండకాయ", "mr": "भेंडी", "ta": "வெண்டைக்காய்", "gu": "ભીંડા", "ur": "بھنڈی", "kn": "ಬೆಂಡೆಕಾಯಿ", "ml": "വെണ്ടയ്ക്ക", "pa": "ਭਿੰਡੀ", "or": "ଭେଣ୍ଡି", "as": "ভেণ্ডী", "es": "Okra", "fr": "Gombo", "de": "Okra", "ar": "بامية", "zh": "秋葵", "ru": "Бамия", "pt": "Quiabo", "ja": "オクラ", "ko": "오크라", "it": "Okra", "tr": "Bamya", "nl": "Okra", "pl": "Okra", "id": "Okra", "th": "กระเจี๊ยบเขียว", "vi": "Đậu bắp", "fa": "بامیه", "ne": "भिन्डी", "si": "බණ්ඩක්කා"},
    {"num": 12, "en": "Bottle Gourd", "hi": "लौकी", "bn": "লাউ", "te": "ఆనపకాయ", "mr": "दुधी भोपळा", "ta": "சுரைக்காய்", "gu": "દૂધી", "ur": "لوکی", "kn": "ಸೋರೆಕಾಯಿ", "ml": "ചുരയ്ക്ക", "pa": "ਘੀਆ", "or": "ଲାଉ", "as": "লাউ", "es": "Calabaza de botella", "fr": "Calebassier", "de": "Flaschenkürbis", "ar": "يقطين", "zh": "葫芦", "ru": "Лагенария", "pt": "Cabaça", "ja": "ヒョウタン", "ko": "조롱박", "it": "Zucca a fiasco", "tr": "Su kabağı", "nl": "Fleskalebas", "pl": "Tykwa", "id": "Labu Air", "th": "น้ำเต้า", "vi": "Bầu", "fa": "کدو قلیانی", "ne": "लौका", "si": "දිය ලබු"},
    {"num": 13, "en": "Bitter Gourd", "hi": "करेला", "bn": "করলা", "te": "కాకరకాయ", "mr": "कारले", "ta": "பாகற்காய்", "gu": "કારેલા", "ur": "کریلا", "kn": "ಹಾಗಲಕಾಯಿ", "ml": "പാവയ്ക്ക", "pa": "ਕਰੇਲਾ", "or": "କଲରା", "as": "তিতা কেৰেলা", "es": "Melón amargo", "fr": "Margose", "de": "Bittermelone", "ar": "القرع المر", "zh": "苦瓜", "ru": "Момордика", "pt": "Melão-de-são-caetano", "ja": "ゴーヤ", "ko": "여주", "it": "Zucca amara", "tr": "Kudret narı", "nl": "Bittermeloen", "pl": "Balsamka ogórkowata", "id": "Pare", "th": "มะระ", "vi": "Mướp đắng", "fa": "خربزه تلخ", "ne": "करेला", "si": "කරවිල"},
    {"num": 14, "en": "Ridge Gourd", "hi": "तोरई", "bn": "ঝিঙে", "te": "బీరకాయ", "mr": "दोडके", "ta": "பீர்க்கங்காய்", "gu": "તુરીયા", "ur": "توری", "kn": "ಹೀರೆಕಾಯಿ", "ml": "പീച്ചിങ്ങ", "pa": "ਤੋਰੀ", "or": "ଜାହ୍ନି", "as": "জিকা", "es": "Lufa acutángula", "fr": "Luffa", "de": "Flügelgurke", "ar": "لوف أضلاع", "zh": "棱角丝瓜", "ru": "Остроребристая люффа", "pt": "Luffa", "ja": "トカドヘチマ", "ko": "수세미오이", "it": "Zucca striata", "tr": "Tarak kabağı", "nl": "Ribbelkomkommer", "pl": "Trukwa ostrokątna", "id": "Gambas", "th": "บวบเหลี่ยม", "vi": "Mướp khía", "fa": "توری", "ne": "घिरौँला", "si": "වැටකොළු"},
    {"num": 15, "en": "Pumpkin", "hi": "कद्दू", "bn": "মিষ্টি কুমড়ো", "te": "గుమ్మడికాయ", "mr": "लाल भोपळा", "ta": "பூசணிக்காய்", "gu": "કોળું", "ur": "کدو", "kn": "ಕುಂಬಳಕಾಯಿ", "ml": "മത്തങ്ങ", "pa": "ਕੱਦੂ", "or": "ବୋଇତିକଖାରୁ", "as": "ৰঙালাউ", "es": "Calabaza", "fr": "Citrouille", "de": "Kürbis", "ar": "قرع عسلي", "zh": "南瓜", "ru": "Тыква", "pt": "Abóbora", "ja": "カボチャ", "ko": "호박", "it": "Zucca", "tr": "Balkabağı", "nl": "Pompoen", "pl": "Dynia", "id": "Labu Kuning", "th": "ฟักทอง", "vi": "Bí đỏ", "fa": "کدو تنبل", "ne": "फर्सी", "si": "වට්ටක්කා"},
    {"num": 16, "en": "Capsicum", "hi": "शिमला मिर्च", "bn": "ক্যাপসিকাম", "te": "బెంగళూరు మిరప", "mr": "ढोबळी मिरची", "ta": "குடைமிளகாய்", "gu": "કેપ્સિકમ", "ur": "شملہ مرچ", "kn": "ದಪ್ಪಮೆಣಸಿನಕಾಯಿ", "ml": "ക്യാപ്സിക്കം", "pa": "ਸ਼ਿਮਲਾ ਮਿਰਚ", "or": "ଶିମଳା ଲଙ୍କା", "as": "কেপচিকাম", "es": "Pimiento", "fr": "Poivron", "de": "Paprika", "ar": "فلفل رومي", "zh": "甜椒", "ru": "Болгарский перец", "pt": "Pimentão", "ja": "ピーマン", "ko": "파프리카", "it": "Peperone", "tr": "Biber", "nl": "Paprika", "pl": "Papryka", "id": "Paprika", "th": "พริกหวาน", "vi": "Ớt chuông", "fa": "فلفل دلمه‌ای", "ne": "भेडे खुर्सानी", "si": "මාළු මිරිස්"},
    {"num": 17, "en": "Broccoli", "hi": "ब्रोकोली", "bn": "ব্রকলি", "te": "బ్రోకలీ", "mr": "ब्रोकोली", "ta": "பச்சை பூக்கோசு", "gu": "બ્રોકોલી", "ur": "بروکلی", "kn": "ಬ್ರೊಕೊಲಿ", "ml": "ബ്രൊക്കോളി", "pa": "ਬਰੋਕਲੀ", "or": "ବ୍ରୋକୋଲି", "as": "ব্ৰকলি", "es": "Brócoli", "fr": "Brocoli", "de": "Brokkoli", "ar": "بروكلي", "zh": "西兰花", "ru": "Брокколи", "pt": "Brócolis", "ja": "ブロッコリー", "ko": "브로콜리", "it": "Broccolo", "tr": "Brokoli", "nl": "Broccoli", "pl": "Brokuł", "id": "Brokoli", "th": "บรอกโคลี", "vi": "Bông cải xanh", "fa": "کلم بروکلی", "ne": "ब्रोकाउली", "si": "බ්‍රොකොලි"},
    {"num": 18, "en": "Cucumber", "hi": "खीरा", "bn": "শসা", "te": "దోసకాయ", "mr": "काकडी", "ta": "வெள்ளரிக்காய்", "gu": "કાકડી", "ur": "کھیرا", "kn": "ಸೌತೆಕಾಯಿ", "ml": "വെള്ളരിക്ക", "pa": "ਖੀਰਾ", "or": "କାକୁଡ଼ି", "as": "তিয়ঁহ", "es": "Pepino", "fr": "Concombre", "de": "Gurke", "ar": "خيار", "zh": "黄瓜", "ru": "Огурец", "pt": "Pepino", "ja": "キュウリ", "ko": "오이", "it": "Cetriolo", "tr": "Salatalık", "nl": "Komkommer", "pl": "Ogórek", "id": "Mentimun", "th": "แตงกวา", "vi": "Dưa chuột", "fa": "خیار", "ne": "काँक्रो", "si": "පිපිඤ්ඤා"},
    {"num": 19, "en": "Beetroot", "hi": "चुकंदर", "bn": "বিট", "te": "బీట్‌రూట్", "mr": "बीट", "ta": "பீட்ரூட்", "gu": "બીટ", "ur": "چقندر", "kn": "ಬೀಟ್ರೂಟ್", "ml": "ബീറ്റ്‌റൂട്ട്", "pa": "ਚਕੰਦਰ", "or": "ବିଟ୍", "as": "বীট", "es": "Remolacha", "fr": "Betterave", "de": "Rote Bete", "ar": "شمندر", "zh": "甜菜根", "ru": "Свёкла", "pt": "Beterraba", "ja": "ビーツ", "ko": "비트", "it": "Barbabietola", "tr": "Pancar", "nl": "Biet", "pl": "Burak", "id": "Bit Merah", "th": "บีทรูท", "vi": "Củ dền", "fa": "چغندر", "ne": "चुकन्दर", "si": "බීට්රූට්"},
    {"num": 20, "en": "Ginger", "hi": "अदरक", "bn": "আদা", "te": "అల్లం", "mr": "आले", "ta": "இஞ்சி", "gu": "આદુ", "ur": "ادرک", "kn": "ಶುಂಠಿ", "ml": "ഇഞ്ചി", "pa": "ਅਦਰਕ", "or": "ଅଦା", "as": "আদা", "es": "Jengibre", "fr": "Gingembre", "de": "Ingwer", "ar": "زنجبيل", "zh": "生姜", "ru": "Имбирь", "pt": "Gengibre", "ja": "ショウガ", "ko": "생강", "it": "Zenzero", "tr": "Zencefil", "nl": "Gember", "pl": "Imbir", "id": "Jahe", "th": "ขิง", "vi": "Gừng", "fa": "زنجبیل", "ne": "अदुवा", "si": "ඉඟුරු"},
    {"num": 21, "en": "Garlic", "hi": "लहसुन", "bn": "রসুন", "te": "వెల్లుల్లి", "mr": "लसूण", "ta": "பூண்டு", "gu": "લસણ", "ur": "لہسن", "kn": "ಬೆಳ್ಳುಳ್ಳಿ", "ml": "വെളുത്തുള്ളി", "pa": "ਲਸਣ", "or": "ରସୁଣ", "as": "নহৰু", "es": "Ajo", "fr": "Ail", "de": "Knoblauch", "ar": "ثوم", "zh": "大蒜", "ru": "Чеснок", "pt": "Alho", "ja": "ニンニク", "ko": "마늘", "it": "Aglio", "tr": "Sarımsak", "nl": "Knoflook", "pl": "Czosnek", "id": "Bawang Putih", "th": "กระเทียม", "vi": "Tỏi", "fa": "سیر", "ne": "लसुन", "si": "සුදු ලූනු"},
    {"num": 22, "en": "Green Chilli", "hi": "हरी मिर्च", "bn": "কাঁচা লঙ্কা", "te": "పచ్చిమిరపకాయ", "mr": "हिरवी मिरची", "ta": "பச்சை மிளகாய்", "gu": "લીલા મરચાં", "ur": "ہری مرچ", "kn": "ಹಸಿರು ಮೆಣಸಿನಕಾಯಿ", "ml": "പച്ചമുളക്", "pa": "ਹਰੀ ਮਿਰਚ", "or": "କଞ୍ଚା ଲଙ୍କା", "as": "কেঁচা জলকীয়া", "es": "Chile verde", "fr": "Piment vert", "de": "Grüne Chilischote", "ar": "فلفل أخضر حار", "zh": "青辣椒", "ru": "Зелёный перец чили", "pt": "Pimenta verde", "ja": "青唐辛子", "ko": "청양고추", "it": "Peperoncino verde", "tr": "Yeşil biber", "nl": "Groene peper", "pl": "Zielone chili", "id": "Cabai Hijau", "th": "พริกเขียว", "vi": "Ớt xanh", "fa": "فلفل سبز تند", "ne": "हरियो खुर्सानी", "si": "අමු මිරිස්"},
    {"num": 23, "en": "Coriander", "hi": "धनिया पत्ता", "bn": "ধনে পাতা", "te": "కొత్తిమీర", "mr": "कोथिंबीर", "ta": "கொத்தமல்லி", "gu": "કોથમીર", "ur": "دھنیا", "kn": "ಕೊತ್ತಂಬರಿ ಸೊಪ್ಪು", "ml": "മല്ലിയില", "pa": "ਧਨੀਆ", "or": "ଧନିଆ ପତ୍ର", "as": "ধনিয়া শাক", "es": "Cilantro", "fr": "Coriandre", "de": "Koriander", "ar": "كزبرة", "zh": "香菜", "ru": "Кинза", "pt": "Coentro", "ja": "パクチー", "ko": "고수", "it": "Coriandolo", "tr": "Kişniş", "nl": "Koriander", "pl": "Kolendra", "id": "Ketumbar", "th": "ผักชี", "vi": "Rau mùi", "fa": "گشنیز", "ne": "धनिया", "si": "කොත්තමල්ලි කොළ"},
    {"num": 24, "en": "Mint", "hi": "पुदीना", "bn": "পুদিনা", "te": "పుదీనా", "mr": "पुदिना", "ta": "புதினா", "gu": "ફુદીનો", "ur": "پودینہ", "kn": "ಪುದೀನ", "ml": "പുതിന", "pa": "ਪੁਦੀਨਾ", "or": "ପୋଦିନା", "as": "পদিনা", "es": "Menta", "fr": "Menthe", "de": "Minze", "ar": "نعناع", "zh": "薄荷", "ru": "Мята", "pt": "Hortelã", "ja": "ミント", "ko": "민트", "it": "Menta", "tr": "Nane", "nl": "Munt", "pl": "Mięta", "id": "Daun Mint", "th": "สะระแหน่", "vi": "Bạc hà", "fa": "نعناع", "ne": "पुदिना", "si": "මින්චි"},
    {"num": 25, "en": "Fenugreek", "hi": "मेथी", "bn": "মেথি শাক", "te": "మెంతికూర", "mr": "मेथी", "ta": "வெந்தயக்கீரை", "gu": "મેથી", "ur": "میتھی", "kn": "ಮೆಂತ್ಯ ಸೊಪ್ಪು", "ml": "ഉലുവച്ചീര", "pa": "ਮੇਥੀ", "or": "ମେଥି ଶାଗ", "as": "মেথি শাক", "es": "Alholva", "fr": "Fenugrec", "de": "Bockshornklee", "ar": "حلبة", "zh": "胡芦巴", "ru": "Пажитник", "pt": "Feno-grego", "ja": "フェヌグリーク", "ko": "호로파", "it": "Fieno greco", "tr": "Çemen otu", "nl": "Fenegriek", "pl": "Kozieradka", "id": "Kelabat", "th": "ฟีนูกรีก", "vi": "Cỏ ca ri", "fa": "شنبلیله", "ne": "मेथी", "si": "උළුහාල් කොළ"},
    {"num": 26, "en": "Turnip", "hi": "शलजम", "bn": "শালগম", "te": "తెల్ల ముల్లంగి", "mr": "सलगम", "ta": "நூல் கோல்", "gu": "શલગમ", "ur": "शलجم", "kn": "ನವಿಲುಕೋಸು", "ml": "ടർണിപ്പ്", "pa": "ਸ਼ਲਗਮ", "or": "ଶାଲଗମ", "as": "শালগম", "es": "Nabo", "fr": "Navet", "de": "Steckrübe", "ar": "لفت", "zh": "芜菁", "ru": "Репа", "pt": "Nabo", "ja": "カブ", "ko": "순무", "it": "Rapa", "tr": "Şalgam", "nl": "Knolraap", "pl": "Rzepa", "id": "Lobak Putih", "th": "เทอร์นิพ", "vi": "Củ cải tròn", "fa": "شلغم", "ne": "सलगम", "si": "ටර්නිප්"},
    {"num": 27, "en": "Sweet Potato", "hi": "शकरकंद", "bn": "মিষ্টি আলু", "te": "చిలగడదుంప", "mr": "रताळे", "ta": "சர்க்கரைவள்ளிக்கிழங்கு", "gu": "શક્કરિયાં", "ur": "شکرقندی", "kn": "ಗೆಣಸು", "ml": "മധുരക്കിഴങ്ങ്", "pa": "ਸ਼ਕਰਕੰਦੀ", "or": "କନ୍ଦମୂଳ", "as": "মিঠা আলু", "es": "Batata", "fr": "Patate douce", "de": "Süßkartoffel", "ar": "بطاطا حلوة", "zh": "红薯", "ru": "Батат", "pt": "Batata-doce", "ja": "サツマイモ", "ko": "고구마", "it": "Patata dolce", "tr": "Tatlı patates", "nl": "Zoete aardappel", "pl": "Batat", "id": "Ubi Jalar", "th": "มันเทศ", "vi": "Khoai lang", "fa": "سیب‌زمینی شیرین", "ne": "सखरखण्ड", "si": "බතල"},
    {"num": 28, "en": "Colocasia", "hi": "अरबी", "bn": "কচু", "te": "చామదుంప", "mr": "अळू", "ta": "சேப்பங்கிழங்கு", "gu": "અળવી", "ur": "اروی", "kn": "ಸಾವೆಗಡ್ಡೆ", "ml": "ചേമ്പ്", "pa": "ਅਰਬੀ", "or": "ସାରୁ", "as": "কচু", "es": "Taro", "fr": "Taro", "de": "Taro", "ar": "قلقاس", "zh": "芋头", "ru": "Таро", "pt": "Taro", "ja": "サトイモ", "ko": "토란", "it": "Taro", "tr": "Gölevez", "nl": "Taro", "pl": "Taro", "id": "Talas", "th": "เผือก", "vi": "Khoai môn", "fa": "تارو", "ne": "पिँडालु", "si": "හබරල"},
    {"num": 29, "en": "Mushroom", "hi": "मशरूम (कुकुरमुत्ता)", "bn": "মাশরুম", "te": "పుట్టగొడుగు", "mr": "आळंबी", "ta": "காளான்", "gu": "મશરૂમ", "ur": "کھمبی", "kn": "ಅಣಬೆ", "ml": "കൂൺ", "pa": "ਖੁੰਬ", "or": "ଛତୁ", "as": "ভেঁকুৰ", "es": "Champiñón", "fr": "Champignon", "de": "Pilz", "ar": "فطر", "zh": "蘑菇", "ru": "Гриб", "pt": "Cogumelo", "ja": "キノコ", "ko": "버섯", "it": "Fungo", "tr": "Mantar", "nl": "Paddenstoel", "pl": "Grzyb", "id": "Jamur", "th": "เห็ด", "vi": "Nấm", "fa": "قارچ", "ne": "च्याउ", "si": "හතු"},
    {"num": 30, "en": "Corn", "hi": "मक्का (भुट्टा)", "bn": "ভুট্টা", "te": "మొక్కజొన్న", "mr": "मका", "ta": "மக்காச்சோளம்", "gu": "મકાઈ", "ur": "مکئی", "kn": "ಮುಸುಕಿನ ಜೋಳ", "ml": "ചോളം", "pa": "ਮੱਕੀ", "or": "ମକା", "as": "মাকৈ", "es": "Maíz", "fr": "Maïs", "de": "Mais", "ar": "ذرة", "zh": "玉米", "ru": "Кукуруза", "pt": "Milho", "ja": "トウモロコシ", "ko": "옥수수", "it": "Mais", "tr": "Mısır", "nl": "Maïs", "pl": "Kukurydza", "id": "Jagung", "th": "ข้าวโพด", "vi": "Ngô", "fa": "ذرت", "ne": "मकै", "si": "ඉරිඟු"},
    {"num": 31, "en": "Green Beans", "hi": "हरी फलियां", "bn": "শিম", "te": "చిక్కుడుకాయ", "mr": "फरसबी", "ta": "பீன்ஸ்", "gu": "ફણસી", "ur": "سبز پھلی", "kn": "ಹುರುಳಿಕಾಯಿ", "ml": "പയർ", "pa": "ਫਲੀਆਂ", "or": "ଛୁଇଁ", "as": "উৰহী", "es": "Judías verdes", "fr": "Haricots verts", "de": "Grüne Bohnen", "ar": "فاصوليا خضراء", "zh": "四季豆", "ru": "Стручковая фасоль", "pt": "Feijão-verde", "ja": "サヤインゲン", "ko": "깍지콩", "it": "Fagiolini", "tr": "Taze fasulye", "nl": "Sperziebonen", "pl": "Fasolka szparagowa", "id": "Buncis", "th": "ถั่วแขก", "vi": "Đậu que", "fa": "لوبیا سبز", "ne": "सिमी", "si": "බෝංචි"},
    {"num": 32, "en": "Drumstick", "hi": "सहजन", "bn": "সজনে ডাঁটা", "te": "మునగకాయ", "mr": "शेवग्याची शेंग", "ta": "முருங்கைக்காய்", "gu": "સરગવો", "ur": "سہانجنا", "kn": "ನುಗ್ಗೆಕಾಯಿ", "ml": "മുരിങ്ങക്കായ", "pa": "ਸੁਹਾਂਜਣਾ", "or": "ସଜନା ଛୁଇଁ", "as": "সজিনা", "es": "Moringa", "fr": "Moringa", "de": "Meerrettichbaum", "ar": "مورينجا", "zh": "辣木", "ru": "Моринга", "pt": "Moringa", "ja": "モリンガ", "ko": "드럼스틱", "it": "Moringa", "tr": "Baget sebzesi", "nl": "Moringa", "pl": "Moringa", "id": "Kelor", "th": "มะรุม", "vi": "Chùm ngây", "fa": "گز روغنی", "ne": "मुन्गा", "si": "මුරුංගා"},
    {"num": 33, "en": "Pointed Gourd", "hi": "परवल", "bn": "পটল", "te": "పొట్లకాయ", "mr": "परवळ", "ta": "கொத்தம்படை", "gu": "પરવળ", "ur": "پرول", "kn": "ಪರವಲ", "ml": "പടവലം", "pa": "ਪਰਵਲ", "or": "ପୋଟଳ", "as": "পটল", "es": "Calabaza puntiaguda", "fr": "Gourde pointue", "de": "Spitzkürbis", "ar": "قرع مدبب", "zh": "蛇瓜果", "ru": "Трихозант", "pt": "Abóbora pontiaguda", "ja": "ポインテッドゴード", "ko": "뾰족조롱박", "it": "Zucca a punta", "tr": "Sivri kabak", "nl": "Puntkalebas", "pl": "Tykwa spiczasta", "id": "Parwal", "th": "มะระขี้นกเรียว", "vi": "Bầu nhọn", "fa": "کدو نوک‌تیز", "ne": "पर्वर", "si": "පොයින්ටඩ් ලබු"},
    {"num": 34, "en": "Ivy Gourd", "hi": "कुंदरू", "bn": "কুঁদরি", "te": "దొండకాయ", "mr": "तोंडली", "ta": "கோவைக்காய்", "gu": "ટીંડોરા", "ur": "کندرو", "kn": "ತೊಂಡೆಕಾಯಿ", "ml": "കോവയ്ക്ക", "pa": "ਕੁੰਦਰੂ", "or": "କୁନ୍ଦୁରୀ", "as": "কুন্দুলী", "es": "Calabaza hiedra", "fr": "Courge lierre", "de": "Scharlachranke", "ar": "قرع اللبلاب", "zh": "红瓜", "ru": "Кокциния", "pt": "Coccinia", "ja": "ヤサイカラスウリ", "ko": "아이비조롱박", "it": "Zucca edera", "tr": "Sarmaşık kabağı", "nl": "Kleine kalebas", "pl": "Kocynia", "id": "Kemarogan", "th": "ตำลึง", "vi": "Bình bát dây", "fa": "کدو پیچکی", "ne": "कुन्द्रुक", "si": "කෝවක්කා"},
    {"num": 35, "en": "Cluster Beans", "hi": "ग्वार फली", "bn": "গুয়ার শুঁটি", "te": "గోరుచిక్కుడు", "mr": "गवार", "ta": "கொத்தவரங்காய்", "gu": "ગુવાર", "ur": "گوار پھلی", "kn": "ಗೋರಿಕಾಯಿ", "ml": "കൊത്തമര", "pa": "ਗਵਾਰ ਫਲੀ", "or": "ଗୁଆଁର", "as": "গুৱাৰ মাহ", "es": "Goma guar", "fr": "Haricot guar", "de": "Guarbohne", "ar": "فول الغوار", "zh": "瓜尔豆", "ru": "Гуар", "pt": "Feijão-guar", "ja": "クラスタ豆", "ko": "구아콩", "it": "Fagiolo guar", "tr": "Guer fasulyesi", "nl": "Guarboon", "pl": "Cyamopsis", "id": "Kacang Guar", "th": "ถั่วกัวร์", "vi": "Đậu gua", "fa": "لوبیا گوار", "ne": "ग्वार सिमी", "si": "ගුවාර් බෝංචි"},
    {"num": 36, "en": "Lettuce", "hi": "सलाद पत्ता", "bn": "লেটুস শাক", "te": "లెట్యూస్", "mr": "सलाड पाने", "ta": "சாலட் கீரை", "gu": "લેટ્યુસ", "ur": "سلاد کا پتا", "kn": "ಲೆಟಿಸ್", "ml": "ലെറ്റൂസ്", "pa": "ਸਲਾਦ ਪੱਤਾ", "or": "ଲେଟୁସ", "as": "লেটুচ পাত", "es": "Lechuga", "fr": "Laitue", "de": "Kopfsalat", "ar": "خس", "zh": "生菜", "ru": "Салат-латук", "pt": "Alface", "ja": "レタス", "ko": "상추", "it": "Lattuga", "tr": "Marul", "nl": "Sla", "pl": "Sałata", "id": "Selada", "th": "ผักกาดหอม", "vi": "Xà lách", "fa": "کاهو", "ne": "सलाद पत्ता", "si": "සලාද කොළ"},
    {"num": 37, "en": "Asparagus", "hi": "शतावरी", "bn": "শতমূলী", "te": "పిల్లిపీచర", "mr": "शतावरी", "ta": "தண்ணீர்விட்டான்", "gu": "શતાવરી", "ur": "مارچوبہ", "kn": "ಶತಾವರಿ", "ml": "ശതാവരി", "pa": "ਸ਼ਤਾਵਰੀ", "or": "ଶତାବରୀ", "as": "শতমূল", "es": "Espárrago", "fr": "Asperge", "de": "Spargel", "ar": "هليون", "zh": "芦笋", "ru": "Спаржа", "pt": "Espargo", "ja": "アスパラガス", "ko": "아스파라거스", "it": "Asparago", "tr": "Kuşkonmaz", "nl": "Asperge", "pl": "Szparag", "id": "Asparagus", "th": "หน่อไม้ฝรั่ง", "vi": "Măng tây", "fa": "مارچوبه", "ne": "कुरिलो", "si": "ඇස්පරගස්"},
    {"num": 38, "en": "Zucchini", "hi": "तोरी (ज़ुकिनी)", "bn": "জুকিনি", "te": "జుకిని", "mr": "झुकिनी", "ta": "சுரைக்காய் வகை", "gu": "ઝુકીની", "ur": "زوچینی", "kn": "ಜುಖಿನಿ", "ml": "സുക്കീനി", "pa": "ਜ਼ੁਕੀਨੀ", "or": "ଜୁକିନି", "as": "জুকিনী", "es": "Calabacín", "fr": "Courgette", "de": "Zucchini", "ar": "كوسة", "zh": "西葫芦", "ru": "Цูกкини", "pt": "Abobrinha", "ja": "ズッキーニ", "ko": "주키니", "it": "Zucchina", "tr": "Kabak", "nl": "Courgette", "pl": "Cukinia", "id": "Zukini", "th": "ซูกินี", "vi": "Bí ngòi", "fa": "کدو سبز", "ne": "जुकिनी", "si": "සුකිනි"},
    {"num": 39, "en": "Celery", "hi": "अजमोद", "bn": "শালুক পাতা", "te": "సెలరీ", "mr": "ओवा पाने", "ta": "செலரி", "gu": "અજમોદ", "ur": "اجوائن کا پودا", "kn": "ಸೆಲೆರಿ", "ml": "സെലറി", "pa": "ਸੈਲਰੀ", "or": "ସେଲେରୀ", "as": "চেলৰী", "es": "Apio", "fr": "Céleri", "de": "Sellerie", "ar": "كرفس", "zh": "芹菜", "ru": "Сельдерей", "pt": "Aipo", "ja": "セロリ", "ko": "샐러리", "it": "Sedano", "tr": "Kereviz", "nl": "Selderij", "pl": "Seler", "id": "Seledri", "th": "ขึ้นฉ่าย", "vi": "Cần tây", "fa": "کرفس", "ne": "सेलरी", "si": "සැල්දිරි"},
    {"num": 40, "en": "Leek", "hi": "विलायती प्याज़", "bn": "লিক শাক", "te": "లీక్ కూర", "mr": "पात कांदा जात", "ta": "வெங்காயத்தாள் வகை", "gu": "લીક", "ur": "گندنا", "kn": "ಲೀಕ್", "ml": "ലീക്സ്", "pa": "ਲੀਕ", "or": "ଲିକ୍", "as": "লিক", "es": "Puerro", "fr": "Poireau", "de": "Lauch", "ar": "كراث", "zh": "韭葱", "ru": "Порей", "pt": "Alho-poró", "ja": "リーキ", "ko": "리크", "it": "Porro", "tr": "Pırasa", "nl": "Prei", "pl": "Por", "id": "Bawang Prei", "th": "ต้นกระเทียม", "vi": "Tỏi tây", "fa": "تره‌فرنگی", "ne": "लिक", "si": "ලීක්ස්"},
    {"num": 41, "en": "Artichoke", "hi": "हाथी चक (आर्टिचोक)", "bn": "আর্টিচোক", "te": "ఆర్టిచోక్", "mr": "आर्टिचोक", "ta": "ஆர்டிசோக்", "gu": "આર્ટિચોક", "ur": "ہاتھی چک", "kn": "ಆರ್ಟಿಕೋಕ್", "ml": "ആർട്ടിചോക്ക്", "pa": "ਆਰਟੀਚੋਕ", "or": "ଆର୍ଟିଚୋକ", "as": "আৰ্টিচক", "es": "Alcachofa", "fr": "Artichaut", "de": "Artischocke", "ar": "خرشوف", "zh": "朝鲜蓟", "ru": "Артишок", "pt": "Alcachofra", "ja": "アーティチョーク", "ko": "아티초크", "it": "Carciofo", "tr": "Enginar", "nl": "Artisjok", "pl": "Karczoch", "id": "Artisyok", "th": "อาร์ติโชค", "vi": "A-ti-sô", "fa": "کنگر فرنگی", "ne": "आर्टिचोक", "si": "ආර්ටිචෝක්"},
    {"num": 42, "en": "Brussels Sprout", "hi": "छोटी बंधगोभी", "bn": "ব্রাসেলস স্প্রাউট", "te": "బ్రస్సెల్స్ మొలకలు", "mr": "छोटी कोबी", "ta": "சிறு முட்டைக்கோசு", "gu": "નાની કોબી", "ur": "چھوٹی بند گوبھی", "kn": "ಪುಟ್ಟ ಎಲೆಕೋಸು", "ml": "ബ്രസൽസ് സ്പ്രൗട്ട്", "pa": "ਨਿੱਕੀ ਬੰਦ ਗੋਭੀ", "or": "ଛୋଟ ବନ୍ଧାକୋବି", "as": "সৰু বন্ধাকবি", "es": "Col de Bruselas", "fr": "Chou de Bruxelles", "de": "Rosenkohl", "ar": "كرنب بروكسل", "zh": "抱子甘蓝", "ru": "Брюссельская капуста", "pt": "Couve-de-bruxelas", "ja": "メキャベツ", "ko": "방울양배추", "it": "Cavoletto di Bruxelles", "tr": "Brüksel lahanası", "nl": "Spruitjes", "pl": "Brukselka", "id": "Kubis Brussel", "th": "กะหล่ำดาว", "vi": "Bắp cải Brussels", "fa": "کلم بروکسل", "ne": "सानो बन्दा", "si": "බ්‍රසල්ස් පැළ"},
    {"num": 43, "en": "Kale", "hi": "करमसाग (केल)", "bn": "কেল শাক", "te": "కేల్ ఆకు", "mr": "केल", "ta": "கேல் கீரை", "gu": "કેલ", "ur": "کیل ساگ", "kn": "ಕೇಲ್ ಸೊಪ್ಪು", "ml": "കേൽ ചീര", "pa": "ਕੇਲ", "or": "କେଲ", "as": "কেল শাক", "es": "Col rizada", "fr": "Chou frisé", "de": "Grünkohl", "ar": "كرنب أجعد", "zh": "羽衣甘蓝", "ru": "Кудрявая капуста", "pt": "Couve-galega", "ja": "ケール", "ko": "케일", "it": "Cavolo riccio", "tr": "Kıvırcık lahana", "nl": "Boerenkool", "pl": "Jarmuż", "id": "Kailan", "th": "ผักเคล", "vi": "Cải xoăn", "fa": "کلم برگ", "ne": "केल", "si": "කේල්"},
    {"num": 44, "en": "Spring Onion", "hi": "हरा प्याज़", "bn": "পেঁয়াজ পাতা", "te": "ఉల్లికాడలు", "mr": "पात कांदा", "ta": "வெங்காயத்தாள்", "gu": "લીલી ડુંગળી", "ur": "ہری پیاز", "kn": "ಈರುಳ್ಳಿ ಹೂವು", "ml": "ഉള്ളിച്ചെടി", "pa": "ਹਰਾ ਪਿਆਜ਼", "or": "ପିଆଜ ସଣ୍ଢା", "as": "পিয়াঁজ পাত", "es": "Cebolleta", "fr": "Ciboule", "de": "Frühlingszwiebel", "ar": "بصل أخضر", "zh": "大葱", "ru": "Зелёный лук", "pt": "Cebolinha", "ja": "ワケギ", "ko": "쪽파", "it": "Cipollotto", "tr": "Yeşil soğan", "nl": "Lente-ui", "pl": "Dymka", "id": "Daun Bawang", "th": "ต้นหอม", "vi": "Hành lá", "fa": "پیازچه", "ne": "छ्यापी", "si": "ලූනු කොළ"},
    {"num": 45, "en": "Yam", "hi": "जिमीकंद (सूरन)", "bn": "ওল কচু", "te": "కందగడ్డ", "mr": "सुरण", "ta": "சேனைக்கிழங்கு", "gu": "સૂરણ", "ur": "زمینکند", "kn": "ಸುವರ್ಣ ಗಡ್ಡೆ", "ml": "ചേന", "pa": "ਜ਼ਿਮੀਕੰਦ", "or": "ଓଲ", "as": "ওলকচু", "es": "Ñame", "fr": "Igname", "de": "Yamswurzel", "ar": "يام", "zh": "山药", "ru": "Ямс", "pt": "Inhame", "ja": "ヤムイモ", "ko": "참마", "it": "Igname", "tr": "Hint yerelması", "nl": "Jam", "pl": "Jams", "id": "Ubi", "th": "มันเสา", "vi": "Khoai mỡ", "fa": "سیب‌زمینی هندی", "ne": "तरुल", "si": "රාජ අල"},
    {"num": 46, "en": "Ash Gourd", "hi": "पेठा", "bn": "চালকুমড়ো", "te": "బూడిద గుమ్మడి", "mr": "कोहळा", "ta": "சாம்பல் பூசணி", "gu": "પેઠા", "ur": "پیٹھا", "kn": "ಬೂದು ಕುಂಬಳ", "ml": "കുമ്പളങ്ങ", "pa": "ਪੇਠਾ", "or": "ପାଣିକଖାରୁ", "as": "কোমোৰা", "es": "Calabaza de cera", "fr": "Courge cireuse", "de": "Wachskürbis", "ar": "القرع الشمعي", "zh": "冬瓜", "ru": "Белая тыква", "pt": "Abóbora-d'água", "ja": "トウガン", "ko": "동아", "it": "Zucca cerosa", "tr": "Kül kabağı", "nl": "Waskalebas", "pl": "Woskownica", "id": "Kundur", "th": "ฟักเขียว", "vi": "Bí đao", "fa": "کدو مومی", "ne": "कुभिन्डो", "si": "පුහුල්"},
    {"num": 47, "en": "Snake Gourd", "hi": "चिचिंडा", "bn": "চিচিঙ্গা", "te": "పొట్లకాయ", "mr": "पडवळ", "ta": "புடலங்காய்", "gu": "પડવળ", "ur": "چچنڈا", "kn": "ಪಡವಲಕಾಯಿ", "ml": "പടവലങ്ങ", "pa": "ਚਚਿੰਡਾ", "or": "ଛଚିନ୍ଦ୍ରା", "as": "ধুন্দুলী", "es": "Calabaza serpiente", "fr": "Gourde serpent", "de": "Schlangengurke", "ar": "قرع الحية", "zh": "蛇豆", "ru": "Змеиная тыква", "pt": "Abóbora-serpente", "ja": "ヘビウリ", "ko": "뱀오이", "it": "Zucca serpente", "tr": "Yılan kabağı", "nl": "Slangenkalebas", "pl": "Wężowa tykwa", "id": "Pare Belut", "th": "บวบงู", "vi": "Mướp rắn", "fa": "کدو مارپیچ", "ne": "चिचिन्डा", "si": "පතෝල"},
    {"num": 48, "en": "Red Cabbage", "hi": "लाल पत्ता गोभी", "bn": "লাল বাঁধাকপি", "te": "ఎర్ర క్యాబేజీ", "mr": "लाल कोबी", "ta": "சிவப்பு முட்டைகோசு", "gu": "લાલ કોબી", "ur": "لال بند گوبھی", "kn": "ಕೆಂಪು ಎಲೆಕೋಸು", "ml": "ചുവന്ന ക്യാബേജ്", "pa": "ਲਾਲ ਪੱਤਾ ਗੋਭੀ", "or": "ନାଲି ବନ୍ଧାକୋବି", "as": "ৰঙা বন্ধাকবি", "es": "Lombarda", "fr": "Chou rouge", "de": "Rotkohl", "ar": "ملفوف أحمر", "zh": "紫甘蓝", "ru": "Краснокочанная капуста", "pt": "Couve-roxa", "ja": "紫キャベツ", "ko": "적양배추", "it": "Cavolo rosso", "tr": "Kırmızı lahana", "nl": "Rodekool", "pl": "Czerwona kapusta", "id": "Kubis Merah", "th": "กะหล่ำปลีม่วง", "vi": "Bắp cải tím", "fa": "کلم قرمز", "ne": "रातो बन्दा", "si": "රතු ගෝවා"},
    {"num": 49, "en": "Parsnip", "hi": "चुकंदर गाजर (पार्सनिप)", "bn": "পার্সনিপ", "te": "పార్స్‌నిప్", "mr": "पार्सनिप", "ta": "வெள்ளை கேரட்", "gu": "પાર્સનિપ", "ur": "سفید گاجر", "kn": "ಬಿಳಿ ಕ್ಯಾರೆಟ್", "ml": "പാഴ്സ്നിപ്", "pa": "ਪਾਰਸਨਿਪ", "or": "ପାର୍ସନିପ", "as": "পাৰ্ছনিপ", "es": "Chirivía", "fr": "Panais", "de": "Pastinake", "ar": "جزر أبيض", "zh": "欧洲防风", "ru": "Пастернак", "pt": "Pastinaca", "ja": "パースニップ", "ko": "파스닙", "it": "Pastinaca", "tr": "Yabani havuç", "nl": "Pastinaak", "pl": "Pasternak", "id": "Pastinak", "th": "พาร์สนิป", "vi": "Củ cải vàng", "fa": "هویج وحشی", "ne": "पार्सनिप", "si": "පාස්නිප්"},
    {"num": 50, "en": "Bamboo Shoot", "hi": "बांस की कोपल", "bn": "বাঁশের কোঁড়ল", "te": "వెదురు చిగురు", "mr": "बांबू कोंब", "ta": "மூங்கில் குருத்து", "gu": "વાંસના કૂંપળ", "ur": "بانس کا تنا", "kn": "ಬಿದಿರಿನ ಚಿಗುರು", "ml": "മുളങ്കൂമ്പ്", "pa": "ਬਾਂਸ ਦੀਆਂ ਕਰੂੰਬਲਾਂ", "or": "କରଡ଼ି", "as": "বাঁহৰ গাজ", "es": "Brote de bambú", "fr": "Pousse de bambou", "de": "Bambussprossen", "ar": "براعم الخيزران", "zh": "竹笋", "ru": "Побеги бамбука", "pt": "Broto de bambu", "ja": "タケノコ", "ko": "죽순", "it": "Germogli di bambù", "tr": "Bambu filizi", "nl": "Bamboescheuten", "pl": "Pędy bambusa", "id": "Rebung", "th": "หน่อไม้", "vi": "Măng tre", "fa": "جوانه خیزران", "ne": "तामा", "si": "උණ බට පැළ"}
]

print(f"Vegetables loaded: {len(VEGETABLES)}")
