#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
50 Fruits (fal) with all 33 language translations.
10 FREE (id 1-10), 40 PREMIUM (id 11-50).
"""

FRUITS = [
    # 1-10 FREE
    {"num": 1, "en": "Apple", "hi": "सेब", "bn": "আপেল", "te": "యాపిల్", "mr": "सफरचंद", "ta": "ஆப்பிள்", "gu": "સફરજન", "ur": "سیب", "kn": "ಸೇಬು", "ml": "ആപ്പിൾ", "pa": "ਸੇਬ", "or": "ସେଓ", "as": "আপেল", "es": "Manzana", "fr": "Pomme", "de": "Apfel", "ar": "تفاح", "zh": "苹果", "ru": "Яблоко", "pt": "Maçã", "ja": "リンゴ", "ko": "사과", "it": "Mela", "tr": "Elma", "nl": "Appel", "pl": "Jabłko", "id": "Apel", "th": "แอปเปิ้ล", "vi": "Táo", "fa": "سیب", "ne": "स्याउ", "si": "ඇපල්"},
    {"num": 2, "en": "Banana", "hi": "केला", "bn": "কলা", "te": "అరటిపండు", "mr": "केळे", "ta": "வாழைப்பழம்", "gu": "કેળું", "ur": "کیلا", "kn": "ಬಾಳೆಹಣ್ಣು", "ml": "വാഴപ്പഴം", "pa": "ਕੇਲਾ", "or": "କଦଳୀ", "as": "কল", "es": "Plátano", "fr": "Banane", "de": "Banane", "ar": "موز", "zh": "香蕉", "ru": "Банан", "pt": "Banana", "ja": "バナナ", "ko": "바나나", "it": "Banana", "tr": "Muz", "nl": "Banaan", "pl": "Banan", "id": "Pisang", "th": "กล้วย", "vi": "Chuối", "fa": "موز", "ne": "केरा", "si": "කෙසෙල්"},
    {"num": 3, "en": "Mango", "hi": "आम", "bn": "আম", "te": "మామిడిపండు", "mr": "आंबा", "ta": "மாம்பழம்", "gu": "કેરી", "ur": "آم", "kn": "ಮಾವಿನಹಣ್ಣು", "ml": "മാങ്ങ", "pa": "ਅੰਬ", "or": "ଆମ୍ବ", "as": "আম", "es": "Mango", "fr": "Mangue", "de": "Mango", "ar": "مانجو", "zh": "芒果", "ru": "Манго", "pt": "Manga", "ja": "マンゴー", "ko": "망고", "it": "Mango", "tr": "Mango", "nl": "Mango", "pl": "Mango", "id": "Mangga", "th": "มะม่วง", "vi": "Xoài", "fa": "انبه", "ne": "आँप", "si": "අඹ"},
    {"num": 4, "en": "Orange", "hi": "संतरा", "bn": "কমলালেবু", "te": "నారింజపండు", "mr": "संत्रे", "ta": "ஆரஞ்சு", "gu": "સંતરા", "ur": "سنترا", "kn": "ಕಿತ್ತಳೆ", "ml": "ഓറഞ്ച്", "pa": "ਸੰਤਰਾ", "or": "କମଳା", "as": "কমলা", "es": "Naranja", "fr": "Orange", "de": "Orange", "ar": "برتقال", "zh": "橙子", "ru": "Апельсин", "pt": "Laranja", "ja": "オレンジ", "ko": "오렌지", "it": "Arancia", "tr": "Portakal", "nl": "Sinaasappel", "pl": "Pomarańcza", "id": "Jeruk", "th": "ส้ม", "vi": "Cam", "fa": "پرتقال", "ne": "सुन्तला", "si": "දොඩම්"},
    {"num": 5, "en": "Grapes", "hi": "अंगूर", "bn": "আঙ্গুর", "te": "ద్రాక్ష", "mr": "द्राक्षे", "ta": "திராட்சை", "gu": "દ્રાક્ષ", "ur": "انگور", "kn": "ದ್ರಾಕ್ಷಿ", "ml": "മുന്തിരി", "pa": "ਅੰਗੂਰ", "or": "ଅଙ୍ଗୁର", "as": "আঙুৰ", "es": "Uvas", "fr": "Raisin", "de": "Weintrauben", "ar": "عنب", "zh": "葡萄", "ru": "Виноград", "pt": "Uvas", "ja": "ブドウ", "ko": "포도", "it": "Uva", "tr": "Üzüm", "nl": "Druiven", "pl": "Winogrona", "id": "Anggur", "th": "องุ่น", "vi": "Nho", "fa": "انگور", "ne": "अङ्गुर", "si": "මිදි"},
    {"num": 6, "en": "Papaya", "hi": "पपीता", "bn": "পেঁপে", "te": "బొప్పాయి", "mr": "पपई", "ta": "பப்பாளி", "gu": "પપૈયું", "ur": "پپیتا", "kn": "ಪಪ್ಪಾಯಿ", "ml": "പപ്പായ", "pa": "ਪਪੀਤਾ", "or": "ଅମୃତଭଣ୍ଡା", "as": "অমিতা", "es": "Papaya", "fr": "Papaye", "de": "Papaya", "ar": "بابايا", "zh": "木瓜", "ru": "Папайя", "pt": "Mamão", "ja": "パパイヤ", "ko": "파파야", "it": "Papaya", "tr": "Papaya", "nl": "Papaja", "pl": "Papaja", "id": "Pepaya", "th": "มะละกอ", "vi": "Đu đủ", "fa": "پاپایا", "ne": "मेवा", "si": "පැපොල්"},
    {"num": 7, "en": "Guava", "hi": "अमरूद", "bn": "পেয়ারা", "te": "జామపండు", "mr": "पेरू", "ta": "கொய்யாப்பழம்", "gu": "જામફળ", "ur": "امرود", "kn": "ಸೀಬೆಹಣ್ಣು", "ml": "പേരയ്ക്ക", "pa": "ਅਮਰੂਦ", "or": "ପିଜୁଳି", "as": "মধুৰিআম", "es": "Guayaba", "fr": "Goyave", "de": "Guave", "ar": "جوافة", "zh": "番石榴", "ru": "Гуава", "pt": "Goiaba", "ja": "グアバ", "ko": "구아바", "it": "Guava", "tr": "Guava", "nl": "Guave", "pl": "Gujawa", "id": "Jambu Biji", "th": "ฝรั่ง", "vi": "Ổi", "fa": "گواوا", "ne": "अम्बा", "si": "පේර"},
    {"num": 8, "en": "Watermelon", "hi": "तरबूज", "bn": "তরমুজ", "te": "పుచ్చకాయ", "mr": "कलिंगड", "ta": "தர்பூசணி", "gu": "તરબૂચ", "ur": "تربوز", "kn": "ಕಲ್ಲಂಗಡಿ", "ml": "തണ്ണിമത്തൻ", "pa": "ਤਰਬੂਜ਼", "or": "ତରଭୁଜ", "as": "তৰমুজ", "es": "Sandía", "fr": "Pastèque", "de": "Wassermelone", "ar": "بطيخ", "zh": "西瓜", "ru": "Арбуз", "pt": "Melancia", "ja": "スイカ", "ko": "수박", "it": "Anguria", "tr": "Karpuz", "nl": "Watermeloen", "pl": "Arbuz", "id": "Semangka", "th": "แตงโม", "vi": "Dưa hấu", "fa": "هندوانه", "ne": "तरबुजा", "si": "පැණි කොමඩු"},
    {"num": 9, "en": "Pineapple", "hi": "अनानास", "bn": "আনারস", "te": "అనాసపండు", "mr": "अननस", "ta": "அன்னாசிப்பழம்", "gu": "અનાનસ", "ur": "انناس", "kn": "ಅನಾನಸ್", "ml": "കൈതച്ചക്ക", "pa": "ਅਨਾਨਾਸ", "or": "ସପୁରୀ", "as": "আনাৰস", "es": "Piña", "fr": "Ananas", "de": "Ananas", "ar": "أناناس", "zh": "菠萝", "ru": "Ананас", "pt": "Abacaxi", "ja": "パイナップル", "ko": "파인애플", "it": "Ananas", "tr": "Ananas", "nl": "Ananas", "pl": "Ananas", "id": "Nanas", "th": "สับปะรด", "vi": "Dứa", "fa": "آناناس", "ne": "भुइँकटर", "si": "අන්නාසි"},
    {"num": 10, "en": "Pomegranate", "hi": "अनार", "bn": "বেদানা", "te": "దానిమ్మపండు", "mr": "डाळिंब", "ta": "மாதுளம்பழம்", "gu": "દાડમ", "ur": "انار", "kn": "ದಾಳಿಂಬೆ", "ml": "മാതളനാരങ്ങ", "pa": "ਅਨਾਰ", "or": "ଡାଳିମ୍ବ", "as": "ডালিম", "es": "Granada", "fr": "Grenade", "de": "Granatapfel", "ar": "رمان", "zh": "石榴", "ru": "Гранат", "pt": "Romã", "ja": "ザクロ", "ko": "석류", "it": "Melograno", "tr": "Nar", "nl": "Granaatappel", "pl": "Granat", "id": "Delima", "th": "ทับทิม", "vi": "Lựu", "fa": "انار", "ne": "अनार", "si": "දෙළුම්"},

    # 11-50 PREMIUM
    {"num": 11, "en": "Strawberry", "hi": "स्ट्रॉबेरी", "bn": "স্ট্রবেরি", "te": "స్ట్రాబెర్రీ", "mr": "स्ट्रॉबेरी", "ta": "ஸ்ட்ராபெர்ரி", "gu": "સ્ટ્રોબેરી", "ur": "اسٹرابیری", "kn": "ಸ್ಟ್ರಾಬೆರ್ರಿ", "ml": "സ്ട്രോബെറി", "pa": "ਸਟ੍ਰਾਬੇਰੀ", "or": "ଷ୍ଟ୍ରବେରୀ", "as": "ষ্ট্ৰবেৰী", "es": "Fresa", "fr": "Fraise", "de": "Erdbeere", "ar": "فراولة", "zh": "草莓", "ru": "Клубника", "pt": "Morango", "ja": "イチゴ", "ko": "딸기", "it": "Fragola", "tr": "Çilek", "nl": "Aardbei", "pl": "Truskawka", "id": "Stroberi", "th": "สตรอว์เบอร์รี", "vi": "Dâu tây", "fa": "توت‌فرنگی", "ne": "स्ट्रबेरी", "si": "ස්ට්‍රෝබෙරි"},
    {"num": 12, "en": "Cherry", "hi": "चेरी", "bn": "চেরি", "te": "చెర్రీ", "mr": "चेरी", "ta": "செர்ரி", "gu": "ચેરી", "ur": "چیری", "kn": "ಚೆರ್ರಿ", "ml": "ചെറി", "pa": "ਚੈਰੀ", "or": "ଚେରୀ", "as": "চেৰী", "es": "Cereza", "fr": "Cerise", "de": "Kirsche", "ar": "كرز", "zh": "樱桃", "ru": "Вишня", "pt": "Cereja", "ja": "サクランボ", "ko": "체리", "it": "Ciliegia", "tr": "Kiraz", "nl": "Kers", "pl": "Wiśnia", "id": "Ceri", "th": "เชอร์รี่", "vi": "Anh đào", "fa": "گیلاس", "ne": "पैयुँ", "si": "චෙරි"},
    {"num": 13, "en": "Peach", "hi": "आड़ू", "bn": "পীচ", "te": "పీచుపండు", "mr": "पीच", "ta": "பீச் பழம்", "gu": "પીચ", "ur": "آڑو", "kn": "ಪೀಚ್", "ml": "പീച്ച്", "pa": "ਆੜੂ", "or": "ପିଚ୍", "as": "পীচ", "es": "Melocotón", "fr": "Pêche", "de": "Pfirsich", "ar": "خوخ", "zh": "桃子", "ru": "Персик", "pt": "Pêssego", "ja": "モモ", "ko": "복숭아", "it": "Pesca", "tr": "Şeftali", "nl": "Perzik", "pl": "Brzoskwinia", "id": "Persik", "th": "ลูกพีช", "vi": "Đào", "fa": "هلو", "ne": "आरु", "si": "පීච්"},
    {"num": 14, "en": "Plum", "hi": "आलू बुखारा", "bn": "আলুবোখরা", "te": "ఆలూబుఖారా", "mr": "आलूबुखारा", "ta": "பிளம்ஸ்", "gu": "આલુબુખારા", "ur": "آلو بخارا", "kn": "ಪ್ಲಮ್", "ml": "പ്ലം", "pa": "ਆਲੂਬੁਖਾਰਾ", "or": "ଆଲୁବୋଖରା", "as": "আলুবোখৰা", "es": "Ciruela", "fr": "Prune", "de": "Pflaume", "ar": "برقوق", "zh": "李子", "ru": "Слива", "pt": "Ameixa", "ja": "プラム", "ko": "자두", "it": "Prugna", "tr": "Erik", "nl": "Pruim", "pl": "Śliwka", "id": "Prem", "th": "ลูกพลัม", "vi": "Mận", "fa": "آلو", "ne": "आरुबखडा", "si": "ප්ලම්"},
    {"num": 15, "en": "Pear", "hi": "नाशपाती", "bn": "নাশপাতি", "te": "బేరిపండు", "mr": "नाशपाती", "ta": "பேரிக்காய்", "gu": "નાસપતી", "ur": "ناشپاتی", "kn": "ಬೇರಿಹಣ್ಣು", "ml": "സബര്ജല്ലി", "pa": "ਨਾਸ਼ਪਾਤੀ", "or": "ନାସପାତି", "as": "নাসপতি", "es": "Pera", "fr": "Poire", "de": "Birne", "ar": "كمثرى", "zh": "梨", "ru": "Груша", "pt": "Pera", "ja": "ナシ", "ko": "배", "it": "Pera", "tr": "Armut", "nl": "Peer", "pl": "Gruszka", "id": "Pir", "th": "ลูกแพร์", "vi": "Lê", "fa": "گلابی", "ne": "नासपाती", "si": "පෙයාර්ස්"},
    {"num": 16, "en": "Kiwi", "hi": "कीवी", "bn": "কিউই ফল", "te": "కివీ పండు", "mr": "किवी", "ta": "கிவி பழம்", "gu": "કીવી", "ur": "کیوی", "kn": "ಕಿವಿ ಹಣ್ಣು", "ml": "കിവി", "pa": "ਕੀਵੀ", "or": "କିୱି ଫଳ", "as": "কিৱি ফল", "es": "Kiwi", "fr": "Kiwi", "de": "Kiwi", "ar": "كيوي", "zh": "奇异果", "ru": "Киви", "pt": "Quiuí", "ja": "キウイ", "ko": "키위", "it": "Kiwi", "tr": "Kivi", "nl": "Kiwi", "pl": "Kiwi", "id": "Kiwi", "th": "กีวี", "vi": "Kiwi", "fa": "کیوی", "ne": "किवी फल", "si": "කිවි"},
    {"num": 17, "en": "Lemon", "hi": "नींबू", "bn": "লেবু", "te": "నిమ్మకాయ", "mr": "लिंबू", "ta": "எலுமிச்சை", "gu": "લીંબુ", "ur": "لیموں", "kn": "ನಿಂಬೆಹಣ್ಣು", "ml": "നാരങ്ങ", "pa": "ਨਿੰਬੂ", "or": "ଲେମ୍ବୁ", "as": "নেমু", "es": "Limón", "fr": "Citron", "de": "Zitrone", "ar": "ليمون", "zh": "柠檬", "ru": "Лимон", "pt": "Limão", "ja": "レモン", "ko": "레몬", "it": "Limone", "tr": "Limon", "nl": "Citroen", "pl": "Cytryna", "id": "Lemon", "th": "มะนาวเหลือง", "vi": "Chanh vàng", "fa": "لیموترش", "ne": "कागती", "si": "දෙහි"},
    {"num": 18, "en": "Coconut", "hi": "नारियल", "bn": "নারকেল", "te": "కొబ్బరికాయ", "mr": "नारळ", "ta": "தேங்காய்", "gu": "નાળિયેર", "ur": "ناریل", "kn": "ತೆಂಗಿನಕಾಯಿ", "ml": "തേങ്ങ", "pa": "ਨਾਰੀਅਲ", "or": "ନଡ଼ିଆ", "as": "নাৰিকল", "es": "Coco", "fr": "Noix de coco", "de": "Kokosnuss", "ar": "جوز الهند", "zh": "椰子", "ru": "Кокос", "pt": "Coco", "ja": "ココナッツ", "ko": "코코넛", "it": "Cocco", "tr": "Hindistan cevizi", "nl": "Kokosnoot", "pl": "Kokos", "id": "Kelapa", "th": "มะพร้าว", "vi": "Dừa", "fa": "نارگیل", "ne": "नारिवल", "si": "පොල්"},
    {"num": 19, "en": "Lychee", "hi": "लीची", "bn": "লিচু", "te": "లిచీ", "mr": "लीची", "ta": "லிச்சி", "gu": "લીચી", "ur": "لیچی", "kn": "ಲಿಚಿ", "ml": "ലിച്ചി", "pa": "ਲੀਚੀ", "or": "ଲିଚୁ", "as": "লেচু", "es": "Lichi", "fr": "Litchi", "de": "Litschi", "ar": "ليتشي", "zh": "荔枝", "ru": "Личи", "pt": "Lichia", "ja": "ライチ", "ko": "리치", "it": "Litchi", "tr": "Liçi", "nl": "Lychee", "pl": "Liczi", "id": "Leci", "th": "ลิ้นจี่", "vi": "Vải", "fa": "سرخالو", "ne": "लिची", "si": "ලචී"},
    {"num": 20, "en": "Fig", "hi": "अंजीर", "bn": "ডুমুর", "te": "అత్తిపండు", "mr": "अंजीर", "ta": "அத்திப்பழம்", "gu": "અંજીર", "ur": "انجیر", "kn": "ಅಂಜೂರ", "ml": "അത്തിപ്പഴം", "pa": "ਅੰਜੀਰ", "or": "ଡିମ୍ବିରି", "as": "ডিমৰু", "es": "Higo", "fr": "Figue", "de": "Feige", "ar": "تين", "zh": "无花果", "ru": "Инжир", "pt": "Figo", "ja": "イチジク", "ko": "무화과", "it": "Fico", "tr": "İncir", "nl": "Vijg", "pl": "Figa", "id": "Ara", "th": "มะเดื่อ", "vi": "Sung", "fa": "انجیر", "ne": "अन्जिर", "si": "අත්තික්කා"},
    {"num": 21, "en": "Custard Apple", "hi": "शरीफा", "bn": "আতাফল", "te": "సీతాఫలం", "mr": "सीताफळ", "ta": "சீத்தாப்பழம்", "gu": "સીતાફળ", "ur": "شریفہ", "kn": "ಸೀತಾಫಲ", "ml": "ആത്തച്ചക്ക", "pa": "ਸ਼ਰੀਫਾ", "or": "ଆତ", "as": "আতাফল", "es": "Chirimoya", "fr": "Pomme cannelle", "de": "Zimtapfel", "ar": "قشطة", "zh": "释迦果", "ru": "Сахарное яблоко", "pt": "Fruta-do-conde", "ja": "カスタードアップル", "ko": "슈가애플", "it": "Cirimoia", "tr": "Kastard elması", "nl": "Kassave-appel", "pl": "Flaszowiec", "id": "Srikaya", "th": "น้อยหน่า", "vi": "Mãng cầu ta", "fa": "کاستارد اپل", "ne": "सरीफा", "si": "අනෝදා"},
    {"num": 22, "en": "Apricot", "hi": "खुबानी", "bn": "এপ্রিকট", "te": "జర్దాలు", "mr": "जर्दाळू", "ta": "சர்க்கரை பாதாமி", "gu": "જરદાળુ", "ur": "خوبانی", "kn": "ಜರ್ದಾಳು", "ml": "ആപ്രിക്കോട്ട്", "pa": "ਖੁਰਮਾਨੀ", "or": "ଆପ୍ରିକଟ", "as": "এপ্ৰিকট", "es": "Albaricoque", "fr": "Abricot", "de": "Aprikose", "ar": "مشمش", "zh": "杏子", "ru": "Абрикос", "pt": "Damasco", "ja": "アンズ", "ko": "살구", "it": "Albicocca", "tr": "Kayısı", "nl": "Abrikoos", "pl": "Morela", "id": "Aprikot", "th": "แอปริคอต", "vi": "Mơ", "fa": "زردآلو", "ne": "खुर्पानी", "si": "ඇප්රිකොට්"},
    {"num": 23, "en": "Blueberry", "hi": "नीलबदरी (ब्लूबेरी)", "bn": "ব্লুবেরি", "te": "బ్లూబెర్రీ", "mr": "ब्लूबेरी", "ta": "அவுரிநெல்லி", "gu": "બ્લૂબેરી", "ur": "نیل بیری", "kn": "ಬ್ಲೂಬೆರ್ರಿ", "ml": "ബ്ലൂബെറി", "pa": "ਬਲੂਬੈਰੀ", "or": "ବ୍ଲୁବେରୀ", "as": "ব্লুবেৰী", "es": "Arándano azul", "fr": "Myrtille", "de": "Blaubeere", "ar": "توت أزرق", "zh": "蓝莓", "ru": "Черника", "pt": "Mirtilo", "ja": "ブルーベリー", "ko": "블루베리", "it": "Mirtillo", "tr": "Yaban mersini", "nl": "Blauwe bes", "pl": "Borówka", "id": "Bluberi", "th": "บลูเบอร์รี", "vi": "Việt quất", "fa": "بلوبری", "ne": "ब्लुबेरी", "si": "බ්ලූබෙරි"},
    {"num": 24, "en": "Blackberry", "hi": "जामुन (ब्लैकबेरी)", "bn": "ব্ল্যাকবেরি", "te": "నల్ల ద్రాక్ష", "mr": "ब्लॅकबेरी", "ta": "நாகப்பழம் வகை", "gu": "બ્લેકબેરી", "ur": "بلیک بیری", "kn": "ಬ್ಲ್ಯಾಕ್‌ಬೆರ್ರಿ", "ml": "ബ്ലാക്ക്ബെറി", "pa": "ਬਲੈਕਬੈਰੀ", "or": "ବ୍ଲାକବେରୀ", "as": "ব্লেকবেৰী", "es": "Mora", "fr": "Mûre", "de": "Brombeere", "ar": "عليق", "zh": "黑莓", "ru": "Ежевика", "pt": "Amora-preta", "ja": "ブラックベリー", "ko": "블랙베리", "it": "Mora", "tr": "Böğürtlen", "nl": "Braam", "pl": "Jeżyna", "id": "Blackberry", "th": "แบล็กเบอร์รี", "vi": "Mâm xôi đen", "fa": "شاه‌توت", "ne": "ब्ल्याकबेरी", "si": "බ්ලැක්බෙරි"},
    {"num": 25, "en": "Raspberry", "hi": "रसभरी", "bn": "রাস্পবেরি", "te": "రాస్ప్‌బెర్రీ", "mr": "रास्पबेरी", "ta": "ராஸ்பெர்ரி", "gu": "રાસબરી", "ur": "رس بھری", "kn": "ರಾಸ್ಪ್ಬೆರ್ರಿ", "ml": "റാസ്പ്ബെറി", "pa": "ਰਸਭਰੀ", "or": "ରାସବେରୀ", "as": "ৰাছবেৰী", "es": "Frambuesa", "fr": "Framboise", "de": "Himbeere", "ar": "توت العليق", "zh": "覆盆子", "ru": "Малина", "pt": "Framboesa", "ja": "ラズベリー", "ko": "라즈베리", "it": "Lampone", "tr": "Ahududu", "nl": "Framboos", "pl": "Malina", "id": "Frambos", "th": "ราสเบอร์รี", "vi": "Mâm xôi đỏ", "fa": "تمشک", "ne": "ऐँसेलु", "si": "රැස්බෙරි"},
    {"num": 26, "en": "Cranberry", "hi": "करौंदा", "bn": "ক্র্যানবেরি", "te": "క్రాన్‌బెర్రీ", "mr": "क्रॅनबेरी", "ta": "கிரான்பெர்ரி", "gu": "ક્રેનબેરી", "ur": "کروندا", "kn": "ಕ್ರಾನ್‌ಬೆರ್ರಿ", "ml": "ക്രാൻബെറി", "pa": "ਕਰੌਂਦਾ", "or": "କ୍ରାନବେରୀ", "as": "ক্ৰেনবেৰী", "es": "Arándano rojo", "fr": "Canneberge", "de": "Cranberry", "ar": "توت بري", "zh": "蔓越莓", "ru": "Клюква", "pt": "Oxicoco", "ja": "クランベリー", "ko": "크랜베리", "it": "Mirtillo rosso", "tr": "Turna yemişi", "nl": "Veenbes", "pl": "Żurawina", "id": "Kranberi", "th": "แครนเบอร์รี", "vi": "Nam việt quất", "fa": "کرنبری", "ne": "क्र्यानबेरी", "si": "ක්‍රැන්බෙරි"},
    {"num": 27, "en": "Mulberry", "hi": "शहतूत", "bn": "তুঁত", "te": "మల్బరీ పండు", "mr": "तुती", "ta": "மல்பெரி", "gu": "શેતૂર", "ur": "شہتوت", "kn": "ಹಿಪ್ಪುನೇರಳೆ", "ml": "മൾബറി", "pa": "ਤੂਤ", "or": "ତୁତକୋଳି", "as": "নুনি", "es": "Mora de árbol", "fr": "Mûre blanche", "de": "Maulbeere", "ar": "توت", "zh": "桑葚", "ru": "Шелковица", "pt": "Amora", "ja": "クワの実", "ko": "오디", "it": "Gelso", "tr": "Dut", "nl": "Moerbei", "pl": "Morwa", "id": "Murbei", "th": "หม่อน", "vi": "Dâu tằm", "fa": "توت", "ne": "किम्बु", "si": "ඇඹිල්ල"},
    {"num": 28, "en": "Date", "hi": "खजूर", "bn": "খেজুর", "te": "ఖర్జూరం", "mr": "खजूर", "ta": "பேரீச்சம்பழம்", "gu": "ખજૂર", "ur": "کھجور", "kn": "ಖರ್ಜೂರ", "ml": "ഈന്തപ്പഴം", "pa": "ਖਜੂਰ", "or": "ଖଜୁରୀ", "as": "খেজুৰ", "es": "Dátil", "fr": "Datte", "de": "Dattel", "ar": "تمر", "zh": "枣子", "ru": "Финик", "pt": "Tâmara", "ja": "デーツ", "ko": "대추야자", "it": "Dattero", "tr": "Hurma", "nl": "Dadel", "pl": "Daktyle", "id": "Kurma", "th": "อินทผลัม", "vi": "Chà là", "fa": "خرما", "ne": "खजुर", "si": "රටඉඳි"},
    {"num": 29, "en": "Dragon Fruit", "hi": "ड्रैगन फ्रूट", "bn": "ড্রাগন ফল", "te": "డ్రాగన్ ఫ్రూట్", "mr": "ड्रॅगन फ्रूट", "ta": "டிராகன் பழம்", "gu": "ડ્રેગન ફ્રૂટ", "ur": "ڈریگن فروٹ", "kn": "ಡ್ರ್ಯಾಗನ್ ಹಣ್ಣು", "ml": "ഡ്രാഗൺ ഫ്രൂട്ട്", "pa": "ਡ੍ਰੈਗਨ ਫਲ", "or": "ଡ୍ରାଗନ ଫଳ", "as": "ড্ৰেগন ফল", "es": "Pitahaya", "fr": "Fruit du dragon", "de": "Drachenfrucht", "ar": "فاكهة التنين", "zh": "火龙果", "ru": "Питахайя", "pt": "Pitaia", "ja": "ドラゴンフルーツ", "ko": "용과", "it": "Frutto del drago", "tr": "Ejder meyvesi", "nl": "Drakenvrucht", "pl": "Pitaja", "id": "Buah Naga", "th": "แก้วมังกร", "vi": "Thanh long", "fa": "میوه اژدها", "ne": "ड्रागन फल", "si": "ඩ්‍රැගන් ෆෘට්"},
    {"num": 30, "en": "Avocado", "hi": "एवोकैडो", "bn": "অ্যাভোকাডো", "te": "వెన్న పండు", "mr": "अवोकॅडो", "ta": "வெண்ணெய் பழம்", "gu": "એવોકાડો", "ur": "ایواکاڈو", "kn": "ಬೆಣ್ಣೆಹಣ್ಣು", "ml": "വെണ്ണപ്പഴം", "pa": "ਐਵੋਕਾਡੋ", "or": "ଆଭୋକାଡୋ", "as": "এভোকাডো", "es": "Aguacate", "fr": "Avocat", "de": "Avocado", "ar": "أفوكادو", "zh": "牛油果", "ru": "Авокадо", "pt": "Abacate", "ja": "アボカド", "ko": "아보카도", "it": "Avocado", "tr": "Avokado", "nl": "Avocado", "pl": "Awokado", "id": "Alpukat", "th": "อะโวคาโด", "vi": "Bơ", "fa": "آووکادو", "ne": "घ्यूफल", "si": "අලිගැටපේර"},
    {"num": 31, "en": "Passion Fruit", "hi": "कृष्णा फल", "bn": "প্যাশন ফল", "te": "ప్యాషన్ ఫ్రూట్", "mr": "पॅशन फ्रूट", "ta": "கொடித்தோடை", "gu": "પેશન ફ્રૂટ", "ur": "پیشن فروٹ", "kn": "ಪ್ಯಾಶನ್ ಹಣ್ಣು", "ml": "പാഷൻ ഫ്രൂട്ട്", "pa": "ਪੈਸ਼ਨ ਫਲ", "or": "ପ୍ୟାସନ ଫଳ", "as": "পেশ্বন ফল", "es": "Maracuyá", "fr": "Fruit de la passion", "de": "Passionsfrucht", "ar": "فاكهة الآلام", "zh": "百香果", "ru": "Маракуйя", "pt": "Maracujá", "ja": "パッションフルーツ", "ko": "패션프루트", "it": "Frutto della passione", "tr": "Çarkıfelek", "nl": "Passievrucht", "pl": "Marakuja", "id": "Markisa", "th": "เสาวรส", "vi": "Chanh dây", "fa": "پشن فروت", "ne": "प्यासन फल", "si": "පැෂන් ෆෘට්"},
    {"num": 32, "en": "Star Fruit", "hi": "कमरख", "bn": "কামরাঙ্গা", "te": "స్టార్ ఫ్రూట్", "mr": "करमळ", "ta": "விளிம்பிப்பழம்", "gu": "કમરખ", "ur": "کمرکھ", "kn": "ನಕ್ಷತ್ರ ಹಣ್ಣು", "ml": "ചതുരപ്പുളി", "pa": "ਕਮਰਖ", "or": "କରମଙ୍ଗା", "as": "কৰ্দ্দৈ", "es": "Carambola", "fr": "Carambole", "de": "Sternfrucht", "ar": "فاكهة النجمة", "zh": "杨桃", "ru": "Карамбола", "pt": "Carambola", "ja": "スターフルーツ", "ko": "스타프루트", "it": "Carambola", "tr": "Yıldız meyvesi", "nl": "Strenvrucht", "pl": "Karambola", "id": "Belimbing", "th": "มะเฟือง", "vi": "Khế", "fa": "میوه ستاره‌ای", "ne": "कमरक", "si": "කාමරංගා"},
    {"num": 33, "en": "Jackfruit", "hi": "कटहल", "bn": "কাঁঠাল", "te": "పనసపండు", "mr": "फणस", "ta": "பலாப்பழம்", "gu": "ફણસ", "ur": "کٹہل", "kn": "ಹಲಸಿನಹಣ್ಣು", "ml": "ചക്ക", "pa": "ਕਟਹਲ", "or": "ପଣସ", "as": "কঁঠাল", "es": "Yaca", "fr": "Jacque", "de": "Jackfrucht", "ar": "كاكايا", "zh": "波罗蜜", "ru": "Джекфрут", "pt": "Jaca", "ja": "ジャックフルーツ", "ko": "잭프루트", "it": "Giacca", "tr": "Ekmek ağacı", "nl": "Nangka", "pl": "Dżakfrut", "id": "Nangka", "th": "ขนุน", "vi": "Mít", "fa": "جک‌فروت", "ne": "कटहर", "si": "කොස්"},
    {"num": 34, "en": "Sapodilla", "hi": "चीकू", "bn": "সফেদা", "te": "సపోటా", "mr": "चिकू", "ta": "சப்போட்டா", "gu": "ચીકુ", "ur": "چیکو", "kn": "ಸಪೋಟ", "ml": "സപ്പോട്ട", "pa": "ਚੀਕੂ", "or": "ସପେଟା", "as": "সফেদা", "es": "Chicozapote", "fr": "Sapotille", "de": "Sapodilla", "ar": "سبوتة", "zh": "人心果", "ru": "Саподилла", "pt": "Sapotizeiro", "ja": "サポジラ", "ko": "사포딜라", "it": "Sapodilla", "tr": "Sapodilla", "nl": "Sapodilla", "pl": "Sapodilla", "id": "Sawo", "th": "ละมุด", "vi": "Hồng xiêm", "fa": "ساپودیلا", "ne": "चिकु", "si": "සැපතිල්ලා"},
    {"num": 35, "en": "Muskmelon", "hi": "खरबूजा", "bn": "খরমুজ", "te": "కర్బూజ", "mr": "खरबूज", "ta": "முலாம் பழம்", "gu": "ટેટી", "ur": "خربوزہ", "kn": "ಕರ್ಬೂಜ", "ml": "തൈര്മത്തൻ", "pa": "ਖ਼ਰਬੂਜ਼ਾ", "or": "ଖରଭୁଜ", "as": "খাৰমুজা", "es": "Melón", "fr": "Melon", "de": "Zuckermelone", "ar": "شمام", "zh": "甜瓜", "ru": "Дыня", "pt": "Melão", "ja": "メロン", "ko": "참외", "it": "Melone", "tr": "Kavun", "nl": "Meloen", "pl": "Melon", "id": "Melon", "th": "แคนตาลูปไทย", "vi": "Dưa lưới", "fa": "خربزه", "ne": "खर्बुजा", "si": "කැන්ටලූප්"},
    {"num": 36, "en": "Sweet Lime", "hi": "मौसंबी", "bn": "মৌসাম্বি", "te": "బత్తాయి", "mr": "मोसंबी", "ta": "சாத்துக்குடி", "gu": "મોસંબી", "ur": "موسمبی", "kn": "ಮೋಸಂಬಿ", "ml": "മൊസാംബി", "pa": "ਮੌਸਮੀ", "or": "ମୌସୁମ୍ବି", "as": "মৌচুম্বী", "es": "Lima dulce", "fr": "Limette douce", "de": "Süße Limette", "ar": "ليمون حلو", "zh": "甜酸橙", "ru": "Сладкий лайм", "pt": "Lima-doce", "ja": "スイートライム", "ko": "스위트라임", "it": "Limone dolce", "tr": "Tatlı misket limonu", "nl": "Zoete limoen", "pl": "Słodka limonka", "id": "Jeruk Manis", "th": "มะนาวหวาน", "vi": "Chanh ngọt", "fa": "لیمو شیرین", "ne": "मौसम", "si": "පැණි දෙහි"},
    {"num": 37, "en": "Gooseberry", "hi": "आंवला", "bn": "আমলকী", "te": "ఉసిరికాయ", "mr": "आवळा", "ta": "நெல்லிக்காய்", "gu": "આંબળા", "ur": "آملہ", "kn": "ನೆಲ್ಲಿಕಾಯಿ", "ml": "നെല്ലിക്ക", "pa": "ਔਂਵਲਾ", "or": "ଅଁଳା", "as": "আমলখি", "es": "Grosella espinosa", "fr": "Groseille à maquereau", "de": "Stachelbeere", "ar": "عنب الثعلب", "zh": "醋栗", "ru": "Крыжовник", "pt": "Groselha", "ja": "スグリ", "ko": "구즈베리", "it": "Uva spina", "tr": "Bektaşi üzümü", "nl": "Kruisbes", "pl": "Agrest", "id": " Gooseberry", "th": "มะขามป้อม", "vi": "Quả lý gai", "fa": "انگور فرنگی", "ne": "अमला", "si": "නෙල්ලි"},
    {"num": 38, "en": "Tamarind", "hi": "इमली", "bn": "তেঁতুল", "te": "చింతపండు", "mr": "चिंच", "ta": "புளி", "gu": "આંબલી", "ur": "املی", "kn": "ಹುಣಸೆಹಣ್ಣು", "ml": "വാളൻപുളി", "pa": "ਇਮਲੀ", "or": "ତେନ୍ତୁଳି", "as": "তেতেলী", "es": "Tamarindo", "fr": "Tamarin", "de": "Tamarinde", "ar": "تمر هندي", "zh": "罗望子", "ru": "Тамаринд", "pt": "Tamarindo", "ja": "タマリンド", "ko": "타มารින්드", "it": "Tamarindo", "tr": "Demirhindi", "nl": "Tamarinde", "pl": "Tamarynd", "id": "Asam Jawa", "th": "มะขาม", "vi": "Me", "fa": "تمبر هندی", "ne": "तित्री", "si": "සියඹලා"},
    {"num": 39, "en": "Olive", "hi": "जैतून", "bn": "জলপাই", "te": "ఆలివ్ పండు", "mr": "ऑलिव्ह", "ta": "ஆலிவ் பழம்", "gu": "જૈતૂન", "ur": "زیتون", "kn": "ಆಲಿವ್", "ml": "ഒലിവ്", "pa": "ਜੈਤੂਨ", "or": "ଜଳପାଇ", "as": "জলফাই", "es": "Aceituna", "fr": "Olive", "de": "Olive", "ar": "زيتون", "zh": "橄榄", "ru": "Оливка", "pt": "Azeitona", "ja": "オリーブ", "ko": "올리브", "it": "Oliva", "tr": "Zeytin", "nl": "Olijf", "pl": "Oliwka", "id": "Zaitun", "th": "มะกอก", "vi": "Ô liu", "fa": "زیتون", "ne": "जैतुन", "si": "ඔලිව්"},
    {"num": 40, "en": "Cantaloupe", "hi": "खरबूज", "bn": "ফুটি", "te": "క్యాంటాలూప్", "mr": "खरबूज जात", "ta": "மஞ்சள் முலாம் பழம்", "gu": "શક્કરટેટી", "ur": "گرما", "kn": "ಮಸ್ಕ್ ಮೆಲನ್", "ml": "കസ്തൂരിമത്തൻ", "pa": "ਖਰਬੂਜਾ", "or": "ଖରବୁଜା", "as": "ফুটি", "es": "Cantelupo", "fr": "Cantaloup", "de": "Kantalup-Melone", "ar": "شمام كوز العسل", "zh": "哈密瓜", "ru": "Канталупа", "pt": "Cantaloupe", "ja": "カンタロープ", "ko": "칸탈루프", "it": "Cantalupo", "tr": "Kantalup", "nl": "Cantaloupe", "pl": "Kantalupa", "id": "Blewah", "th": "แคนตาลูป", "vi": "Dưa vàng", "fa": "طالبی", "ne": "चिप्ले खर्बुजा", "si": "කැන්ටලූප්"},
    {"num": 41, "en": "Grapefruit", "hi": "चकोतरा", "bn": "বাতাবি লেবু", "te": "పంపరపనస", "mr": "पपनस", "ta": "பப்ளிமாஸ்", "gu": "ચકોતરો", "ur": "چکوترا", "kn": "ಚಕೋತ", "ml": "ബബ്ലൂസ് നാരങ്ങ", "pa": "ਚਕੋਤਰਾ", "or": "ବାତାପି", "as": "ৰবাব টেঙা", "es": "Pomelo", "fr": "Pamplemousse", "de": "Grapefruit", "ar": "جريب فروت", "zh": "西柚", "ru": "Грейпфрут", "pt": "Toranja", "ja": "グレープフルーツ", "ko": "자몽", "it": "Pompelmo", "tr": "Greyfurt", "nl": "Grapefruit", "pl": "Grejpfrut", "id": "Jeruk Bali", "th": "เกรปฟรุต", "vi": "Bưởi chùm", "fa": "گریپ‌فروت", "ne": "भोगटे", "si": "ජම්බෝල"},
    {"num": 42, "en": "Durian", "hi": "ड्यूरियन", "bn": "ডুরিয়ান", "te": "డూరియన్", "mr": "ड्युरियन", "ta": "துரியன் பழம்", "gu": "ડ્યુરિયન", "ur": "ڈوریان", "kn": "ಡ್ಯೂರಿಯನ್", "ml": "ഡൂറിയൻ", "pa": "ਡਿਊਰੀਅਨ", "or": "ଡୁରିଆନ", "as": "ডুৰিয়ান", "es": "Durián", "fr": "Durian", "de": "Durian", "ar": "دوريان", "zh": "榴莲", "ru": "Дуриан", "pt": "Durião", "ja": "ドリアン", "ko": "두리안", "it": "Durian", "tr": "Duryan", "nl": "Doerian", "pl": "Durian", "id": "Durian", "th": "ทุเรียน", "vi": "Sầu riêng", "fa": "خارگیل", "ne": "डुरियन", "si": "දුරියන්"},
    {"num": 43, "en": "Mangosteen", "hi": "मैंगोस्टीन", "bn": "ম্যাঙ্গোস্টিন", "te": "మాంగోస్టీన్", "mr": "मँगोस्टीन", "ta": "மங்குஸ்தான்", "gu": "મેંગોસ્ટીન", "ur": "مینگوسٹین", "kn": "ಮ್ಯಾಂಗೋಸ್ಟೀನ್", "ml": "മാംഗോസ്റ്റീൻ", "pa": "ਮੈਂਗੋਸਟੀਨ", "or": "ମାଙ୍ଗୋଷ୍ଟିନ", "as": "মেংগোষ্টিন", "es": "Mangostán", "fr": "Mangoustan", "de": "Mangostane", "ar": "مانغوستين", "zh": "山竹", "ru": "Мангостан", "pt": "Mangostão", "ja": "マンゴスチン", "ko": "망고스틴", "it": "Mangostano", "tr": "Mangostan", "nl": "Mangistan", "pl": "Garcinia", "id": "Manggis", "th": "มังคุด", "vi": "Măng cụt", "fa": "منگوستین", "ne": "म्याङ्गोस्टिन", "si": "මැංගුස්"},
    {"num": 44, "en": "Persimmon", "hi": "तेंदू फल", "bn": "পার্সিমন", "te": "పెర్సిమోన్", "mr": "झाडू फळ", "ta": "சீமைப்பனிச்சை", "gu": "પર્સિમોન", "ur": "جاپانی پھل", "kn": "ಪರ್ಸಿಮನ್", "ml": "പെർസിമൺ", "pa": "ਅਮਲੋਕ", "or": "କେନ୍ଦୁ ଫଳ", "as": "কেন্দু ফল", "es": "Caqui", "fr": "Kaki", "de": "Kaki", "ar": "كاكي", "zh": "柿子", "ru": "Хурма", "pt": "Caqui", "ja": "カキ", "ko": "감", "it": "Cachi", "tr": "Trabzon hurması", "nl": "Kaki", "pl": "Kaki", "id": "Kesemek", "th": "ลูกพลับ", "vi": "Hồng", "fa": "خرمالو", "ne": "हलुवाबेद", "si": "පර්සිමන්"},
    {"num": 45, "en": "Quince", "hi": "श्रीफल (क्विंस)", "bn": "শ্রীফল", "te": "క్విన్స్", "mr": "श्रीफळ", "ta": "சீமை மாதுளை", "gu": "શ્રીફળ", "ur": "بہی", "kn": "ಕ್ವಿನ್ಸ್", "ml": "ക്വിൻസ്", "pa": "ਬਹੀ ਦਾ ਫਲ", "or": "ଶ୍ରୀଫଳ", "as": "শ্ৰীফল", "es": "Membrillo", "fr": "Coing", "de": "Quitte", "ar": "سفرجل", "zh": "榅桲", "ru": "Айва", "pt": "Marmelo", "ja": "マルメロ", "ko": "모과", "it": "Mela cotogna", "tr": "Ayva", "nl": "Kweepeer", "pl": "Pigwa", "id": "Kwit", "th": "ควินซ์", "vi": "Mộc qua", "fa": "به", "ne": "क्विन्स", "si": "ක්වින්ස්"},
    {"num": 46, "en": "Longan", "hi": "आंख फल (लोंगन)", "bn": "আঁশফল", "te": "లాంగన్", "mr": "लोंगन", "ta": "லாங்கன்", "gu": "લોંગન", "ur": "لونگن", "kn": "ಲಾಂಗನ್", "ml": "ലോംഗൻ", "pa": "ਲੋਂਗਨ", "or": "ଆଁସଫଳ", "as": "আঁহফল", "es": "Longan", "fr": "Longane", "de": "Longan", "ar": "لونجان", "zh": "龙眼", "ru": "Лонган", "pt": "Longan", "ja": "リュウガン", "ko": "용안", "it": "Longan", "tr": "Longan", "nl": "Longan", "pl": "Longan", "id": "Lengkeng", "th": "ลำไย", "vi": "Nhãn", "fa": "چشم اژدها", "ne": "लोङ्गन", "si": "ලෝන්ගන්"},
    {"num": 47, "en": "Rambutan", "hi": "रामबुटान", "bn": "রামবুটান", "te": "రాంబుటాన్", "mr": "राम्बुतान", "ta": "ரம்புட்டான்", "gu": "રામબુટાન", "ur": "رامبوتان", "kn": "ರಂಬುಟಾನ್", "ml": "റംബുട്ടാൻ", "pa": "ਰਾਂਬੁਟਾਨ", "or": "ରାମବୁଟାନ", "as": "ৰামবুটান", "es": "Rambután", "fr": "Ramboutan", "de": "Rambutan", "ar": "رامبوتان", "zh": "红毛丹", "ru": "Рамбутан", "pt": "Rambutão", "ja": "ランブータン", "ko": "람부탄", "it": "Rambutan", "tr": "Rambutan", "nl": "Ramboetan", "pl": "Rambutan", "id": "Rambutan", "th": "เงาะ", "vi": "Chôm chôm", "fa": "رامبوتان", "ne": "रामबुतान", "si": "රඹුටන්"},
    {"num": 48, "en": "Kumquat", "hi": "कमक्वाट", "bn": "কামকোয়াট", "te": "కమ్‌క్వాట్", "mr": "कमक्वॉट", "ta": "கம்வாட்", "gu": "કમક્વાટ", "ur": "کمکواٹ", "kn": "ಕಮ್ಕ್ವಾಟ್", "ml": "കംക്വാട്ട്", "pa": "ਕਮਕੁਆਟ", "or": "କମକ୍ବାଟ", "as": "কামকুৱাট", "es": "Kumquat", "fr": "Kumquat", "de": "Kumquat", "ar": "كمكوات", "zh": "金桔", "ru": "Кумкват", "pt": "Quincã", "ja": "キンカン", "ko": "금귤", "it": "Kumquat", "tr": "Kamkat", "nl": "Kumquat", "pl": "Kumkwat", "id": "Kumkuat", "th": "ส้มจี๊ด", "vi": "Quất", "fa": "کامکوات", "ne": "कुमक्वाट", "si": "කුම්කට්"},
    {"num": 49, "en": "Clementine", "hi": "क्लेमेंटाइन संतरा", "bn": "ক্লেমেন্টাইন", "te": "క్లెమెంటిన్", "mr": "क्लेमेंटाइन", "ta": "கிளெமெண்டைன்", "gu": "ક્લેમેન્ટાઇન", "ur": "کلیمینٹائن", "kn": "ಕ್ಲೆಮೆಂಟೈನ್", "ml": "ക്ലെമന്റൈൻ", "pa": "ਕਲੇਮੈਂਟਾਈਨ", "or": "କ୍ଲେମେଣ୍ଟାଇନ", "as": "ক্লেমেণ্টাইন", "es": "Clementina", "fr": "Clémentine", "de": "Clementine", "ar": "كلمنتینا", "zh": "小柑橘", "ru": "Клементин", "pt": "Clementina", "ja": "クレメンティン", "ko": "클레멘타인", "it": "Clementina", "tr": "Klementin", "nl": "Clementine", "pl": "Klementynka", "id": "Jeruk Clementine", "th": "ส้มเคลเมนไทน์", "vi": "Quýt Clementine", "fa": "کلمانتین", "ne": "क्लेमेन्टाइन", "si": "ක්ලෙමන්ටයින්"},
    {"num": 50, "en": "Plantain", "hi": "कच्चा केला", "bn": "কাঁচকলা", "te": "కూర అరటి", "mr": "रांधलेले केळे", "ta": "நேந்திரங்காய்", "gu": "કાચું કેળું", "ur": "پکانے والا کیلا", "kn": "ಬಾಳೆಕಾಯಿ", "ml": "നേന്ത്രക്കായ", "pa": "ਕੱਚਾ ਕੇਲਾ", "or": "କଞ୍ଚା କଦଳୀ", "as": "কাঁচকল", "es": "Plátano macho", "fr": "Banane plantain", "de": "Kochbanane", "ar": "موز الجنة", "zh": "芭蕉", "ru": "Плантан", "pt": "Plátano", "ja": "プランテン", "ko": "플랜틴", "it": "Platano", "tr": "Yemeklik muz", "nl": "Bakbanaan", "pl": "Plantan", "id": "Pisang Olahan", "th": "กล้วยทำอาหาร", "vi": "Chuối lá", "fa": "موز پختنی", "ne": "काँचो केरा", "si": "අළු කෙසෙල්"}
]

print(f"Fruits loaded: {len(FRUITS)}")
